Repository Ben987/Bondage-College, pull requests merged in 2020-10, with the labels that each got.

#1502 Code cleanup
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/Skill.js
Labels: refactor

#1501 Slave collar, extra precautions
  BondageClub/Screens/Character/Login/Login.js
Labels: improvement

#1514 Bugfix: Prevents players from colouring items they shouldn't be able to
  BondageClub/Scripts/Dialog.js
Labels: fix

#1517 New items
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Glasses/Preview/SunGlassesClear.png
  BondageClub/Assets/Female3DCG/Glasses/SunGlassesClear.png
  BondageClub/Assets/Female3DCG/Mask/FuturisticVisor.png
  BondageClub/Assets/Female3DCG/Mask/Preview/FuturisticVisor.png
Labels: asset

#1521 Optimized Scripted Assets
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
Labels: refactor

#1522 Confirm safeword
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: improvement

#1523 Fix fetish in arousal screen
  BondageClub/Screens/Character/Preference/Preference.js
Labels: fix

#1527 Fix dialog leave
  BondageClub/Scripts/Dialog.js
Labels: fix

#1529 Missing assets
  BondageClub/Assets/Female3DCG/HairAccessory1/Suspension/Ribbons2.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/Ribbons2.png
Labels: asset, fix

#1531 Random kidnappers can't remove lover items
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
Labels: change

#1520 Futuristic Panel Gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagPlug_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Ball.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Mask.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Straps.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagPlug_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGag_Ball.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGag_Mask.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/FuturisticHarnessPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/FuturisticPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth2/FuturisticPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth2/FuturisticPanelGag_Ball.png
  BondageClub/Assets/Female3DCG/ItemMouth2/FuturisticPanelGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth2/FuturisticPanelGag_Strap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/FuturisticPanelGag.png
  BondageClub/Assets/Female3DCG/ItemMouth3/FuturisticPanelGag_Ball.png
  BondageClub/Assets/Female3DCG/ItemMouth3/FuturisticPanelGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth3/FuturisticPanelGag_Strap.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/Ball.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/Padded.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/Plug.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/Ball.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/Padded.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/Plug.png
  BondageClub/index.html
Labels: asset

#1532 Interactive Visor
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisor.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorBlind.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorBlind_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorFace.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorFace_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorHeavyTint.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorHeavyTint_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorLightTint.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorLightTint_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisor_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/InteractiveVisor.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/Blind.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/HeavyTint.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/InteractiveVisor.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/LightTint.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/Transparent.png
  BondageClub/index.html
Labels: asset

#1534 Futuristic chastity belt
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVisorLightTint_Mask.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/FuturisticChastityBelt.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/OpenBack.png
  BondageClub/index.html
Labels: asset

#1535 Futuristic bra
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Large_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Large_Display.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Lock.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Normal_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Normal_Display.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Small_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Small_Display.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLarge_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLarge_Display.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/Preview/FuturisticBra.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1477 New item: wooden sign
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/WoodenSign.png
  BondageClub/Assets/Female3DCG/ItemMisc/WoodenSign_Rope.png
  BondageClub/Assets/Female3DCG/ItemMisc/WoodenSign_Sign.png
  BondageClub/Assets/Female3DCG/ItemMisc/WoodenSign_Text.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CHANGELOG.md
  BondageClub/CSS/Styles.css
  BondageClub/Fonts/Calligraffitti/Calligraffitti-Regular.ttf
  BondageClub/Fonts/Calligraffitti/LICENSE.txt
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/index.html
Labels: asset

#1478 Change: Custom tag to use multi color system
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Text.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
Labels: change

#1497 Handheld Toys Refactor + Ruler item
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysRuler.png
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Ruler.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset, refactor

#1536 Fix: Login NPC Collar
  BondageClub/Screens/Character/Login/Login.js
Labels: beta-fix, fix

#1538 Crash fix
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Scripts/Character.js
Labels: beta-fix, hotfix, priority

#1539 Fix teddies
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/Familiar.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/FamiliarCat.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/FamiliarParrot.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/FamiliarSkeleton.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/LittleMonster.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/LittleMonsterBlue.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/LittleMonsterGreen.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/LittleMonsterRed.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBear.PNG
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBearBunny.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBearFox.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBearKitty.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBearPony.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/TeddyBearPup.png
Labels: asset, beta-fix

#1540 Yoked mermaid tail
  BondageClub/Assets/Female3DCG/ItemLegs/Yoked/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/Yoked/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/Yoked/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/Yoked/MermaidTail_XLarge.png
Labels: asset, beta-fix, priority

#1541 missing locks
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderStrap_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderWrapStrap_Lock.png
Labels: asset, beta-fix

#1542 Fix limited permission
  BondageClub/Scripts/Server.js
Labels: beta-fix, hotfix, priority

#1543 Beta Fix: Replaces calls to removed extended item functions
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ExtendedItem.js
Labels: beta-fix, hotfix, priority

#1544 Fix color picker
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix, hotfix, priority

#1545 locked belt
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OrnateChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/PolishedChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/StuddedChastityBelt.js
Labels: asset, beta-fix

#1546 Beta bugfix: Removes public class fields
  BondageClub/Scripts/Text.js
Labels: beta-fix, hotfix, priority

#1547 Fixed coffin interaction
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
Labels: asset, beta-fix

#1548 Expose torso with the bolero
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, beta-fix

#1551 Beta bugfix: Disallow items on movie studio props
  BondageClub/Screens/Room/MovieStudio/MovieStudio.js
Labels: Ben, beta-fix

#1555 Fix: Simple Hogtie Prerequisites
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
Labels: beta-fix, fix

#1554 Fix: Bluetooth Earbuds option selection
  BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/BluetoothEarbuds.js
Labels: beta-fix, fix

#1557 Beta bugfix: Don't set auto AFK if it's already set.
  BondageClub/Scripts/AfkTimer.js
Labels: beta-fix, fix

#1558 Chat Search Friends Position fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#1561 Leather Armbinder Lock Positions Fix
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderStrap_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderWrapStrap_Lock.png
Labels: beta-fix, fix

#1563 Fix CSV order
  BondageClub/Assets/Female3DCG/Female3DCG.csv
Labels: asset, beta-fix

#1562 Bugfix: Hide colour picker buttons for non-colourable items
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Dialog.js
Labels: fix

#1565 Beta bugfix: Makes ItemColorExit more resilient
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Element.js
Labels: beta-fix, fix

#1567 fix text
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1572 Movie studio typos
  BondageClub/Screens/Room/MovieStudio/Dialog_NPC_MovieStudio_Director.csv
  BondageClub/Screens/Room/MovieStudio/Dialog_NPC_MovieStudio_Interview_Mistress.csv
Labels: beta-fix

#1568 Fix: Online drinks
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid.csv
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
Labels: beta-fix, fix

#1573 Fix: asylum bedroom softlocks
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#1575 Fix Diaper Harness Layering
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, beta-fix, fix

#1579 Fixed griefing with wooden sign
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#1583 Interactive visor dressing fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/InteractiveVisor.js
Labels: asset, hotfix

#1584 Bugfix: Skin colour change fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: hotfix

#1587 fix cloak
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, hotfix

#1585 Bugfix: Fixes effect consistency on the futuristic panel gags
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: asset, hotfix

#1588 Automatic Shock Collar/Unit
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/AutoShockCollarBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemNeck/AutoShockCollarBlink_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/AutoShockCollar_Collar.png
  BondageClub/Assets/Female3DCG/ItemNeck/AutoShockCollar_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/AutoShockCollar.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarAutoShockUnitBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarAutoShockUnitBlink_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarAutoShockUnit_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarAutoShockUnit_Unit.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/Preview/CollarAutoShockUnit.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/AutoShockCollar/AutoShockCollar.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/index.html
Labels: asset, change

#1589 Futuristic Collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/FuturisticCollar_Band.png
  BondageClub/Assets/Female3DCG/ItemNeck/FuturisticCollar_Display.png
  BondageClub/Assets/Female3DCG/ItemNeck/FuturisticCollar_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/FuturisticCollar.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Audio/FuturisticApply.mp3
  BondageClub/Audio/HydraulicLock.mp3
  BondageClub/Audio/HydraulicUnlock.mp3
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Scripts/Audio.js
  BondageClub/index.html
Labels: asset, has-dependencies

#1586 Futuristic Gag Update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagBall_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagLightBall_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagLightBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagPlug_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGagPlug_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessPanelGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagBall_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagLightBall_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagLightBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagPlug_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGagPlug_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticPanelGag_Light.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/LightBall.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/LightBall.png
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/red.png
  BondageClub/Scripts/Audio.js
Labels: asset, has-dependencies

#1581 Futuristic Chastity Belt Update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
Labels: asset, has-dependencies

#1591 Bugfix: Various minor asset fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1590 Fixed and added gag difficulties
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#1570 Improvement: Adjustments to the inflatable straight leotard
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/InflatableStraightLeotard.js
Labels: asset, change

#1556 Foam Sword Complete
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysSword.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysSword.png
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/EgyptianExhibit.jpg
  BondageClub/Backgrounds/PoolBottom.jpg
  BondageClub/Backgrounds/PoolBottomDark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Sword.png
Labels: asset

#1549 Bunny & Cow tail strap variant
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/CowtailStrap.png
  BondageClub/Assets/Female3DCG/TailStraps/CowtailStrap.png
  BondageClub/Assets/Female3DCG/TailStraps/Preview/BunnyTailStrap.png
  BondageClub/Assets/Female3DCG/TailStraps/Preview/CowtailStrap.png
Labels: asset

#1550 Import/Export Colors
  BondageClub/Icons/Export.png
  BondageClub/Icons/Import.png
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: improvement

#1604 Graphical fixes for the futuristic bra
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeHeart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeSolid_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Large_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalHeart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalSolid_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Normal_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeHeart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeSolid_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLarge_Bra.png
Labels: asset, fix

#1603 Bugfix: Colour picker error
  BondageClub/Scripts/ColorPicker.js
Labels: fix

#1602 Futuristic Sound Effect Changes
  BondageClub/Audio/AccessDenied.mp3
  BondageClub/Audio/SciFiConfigure.mp3
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Scripts/Audio.js
Labels: asset, change

#1599 Preferences Homepage
  BondageClub/Icons/Arousal.png
  BondageClub/Icons/General.png
  BondageClub/Icons/Security.png
  BondageClub/Icons/Visibility.png
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: change

#1564 Maid Button
  BondageClub/Icons/ServiceBell.png
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/MainHall/Text_MainHall.csv
Labels: feature

#1606 Automatic Maids Change
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: fix

#1607 Fixed futuristic Collar text
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset, fix

#1609 Help Kneel/Stand Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1610 Strait Dress & Chains fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1611 Bolero Alpha Masks fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1612 Succubus Heart Tail Fix
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/SuccubusHeartButtPlug_Heart.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/SuccubusHeartButtPlug_Tail.png
  BondageClub/Assets/Female3DCG/ItemButt/SuccubusHeartButtPlug_Heart.png
  BondageClub/Assets/Female3DCG/ItemButt/SuccubusHeartButtPlug_Tail.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/SuccubusHeartTailStrap_Heart.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/SuccubusHeartTailStrap_Tail.png
  BondageClub/Assets/Female3DCG/TailStraps/SuccubusHeartTailStrap_Heart.png
  BondageClub/Assets/Female3DCG/TailStraps/SuccubusHeartTailStrap_Tail.png
Labels: asset, fix

#1608 Futuristic Armbinder Lock Icon Fix
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticArmbinderTight_lock.png
Labels: asset, fix

#1613 Inherit Colour improvement & Latex Hood Open Hair split
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/LatexHoodOpenHair.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHoodOpenHair_Hair.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHoodOpenHair_Hood.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Scripts/CommonDraw.js
Labels: asset, improvement

#1614 Block Category Hovertext fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#1615 Hair Mismatch Fix
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1616 Vibrating Dildo Multi-color
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemVulva/VibratingDildo_Dildo.png
  BondageClub/Assets/Female3DCG/ItemVulva/VibratingDildo_End.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1530 Ability to suspend maid service
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_FirstSub.csv
  BondageClub/Screens/Room/Gambling/Gambling.js
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid.csv
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
  BondageClub/Screens/Room/Photographic/Photographic.js
Labels: feature

#1617 Handheld Toy fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Belt.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/CandleWax.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Cane.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/CattleProd.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Crop.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/ElectricToothbrush.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Feather.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/FeatherDuster.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Flogger.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Hairbrush.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/HeartCrop.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/IceCube.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/LargeDildo.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Lotion.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Paddle.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/PetToy.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Ruler.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/ShockWand.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SmallDildo.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SmallVibratingWand.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Sword.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/TennisRacket.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Toothbrush.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/VibratingWand.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Vibrator.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/WartenbergWheel.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Whip.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/WhipPaddle.png
  BondageClub/Scripts/Dialog.js
Labels: asset, fix

#1622 Vibrating Dildo Default color
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1623 Vibrators Edged Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Character.js
Labels: fix

#1624 Spreading Items Kneel Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1625 Blocked Handheld Toy - Inventory Order fix
  BondageClub/Scripts/Dialog.js
Labels: fix

#1620 OOC chat and whisper garbling
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
Labels: change

#1559 Vibe VFX
  BondageClub/Screens/Character/Player/ArousalMeter.png
  BondageClub/Screens/Character/Player/ArousalMeterAutomatic.png
  BondageClub/Screens/Character/Player/ArousalMeterOrgasm.png
  BondageClub/Screens/Character/Player/ArousalMeterOrgasmAutomatic.png
  BondageClub/Screens/Character/Player/ArousalMeter_Glow_0.png
  BondageClub/Screens/Character/Player/ArousalMeter_Glow_1.png
  BondageClub/Screens/Character/Player/ArousalMeter_Glow_2.png
  BondageClub/Screens/Character/Player/ArousalMeter_Glow_3.png
  BondageClub/Screens/Character/Player/ArousalMeter_Glow_4.png
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Timer.js
Labels: improvement
