Repository Ben987/Bondage-College, pull requests merged in 2020-12, with the labels that each got.

#1723 Bugfix: Fixes a rare issue on chatroom relog
  BondageClub/Scripts/Server.js
Labels: fix

#1663 Password Lock
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/PasswordPadlock.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMisc/CombinationPadlock/CombinationPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: asset, feature

#1726 Preview fix + 2 Piercings
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/FuturisticMittens.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/CrossedStraightPiercing_Large.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/CrossedStraightPiercing_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/CrossedStraightPiercing_Normal.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/CrossedStraightPiercing_Small.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/CrossedStraightPiercing_XLarge.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/CrossedStraightPiercing_Large.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/CrossedStraightPiercing_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/CrossedStraightPiercing_Normal.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/CrossedStraightPiercing_Small.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/CrossedStraightPiercing_XLarge.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/Preview/CrossedStraightPiercing.png
  BondageClub/Assets/Female3DCG/ItemNose/BarbelPiercing.png
  BondageClub/Assets/Female3DCG/ItemNose/Preview/BarbelPiercing.png
Labels: asset, fix

#1727 1 New gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth3/CageMuzzle_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth3/CageMuzzle_Muzzle.png
  BondageClub/Assets/Female3DCG/ItemMouth3/CageMuzzle_Strap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/Preview/CageMuzzle.png
Labels: asset

#1729 Default colors for Bed and Covers
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1730 Password Lock Preview
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/PasswordPadlock.png
Labels: asset, improvement

#1731 Futuristic Collar Open Permission Setting
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: asset

#1732 Barefoot Sandals
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Shoes/BarefootSandals1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/BarefootSandals1_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/BarefootSandals1_Small.png
  BondageClub/Assets/Female3DCG/Shoes/BarefootSandals1_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/BarefootSandals1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/BarefootSandals1_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/BarefootSandals1_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/BarefootSandals1_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/BarefootSandals1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/BarefootSandals1_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/BarefootSandals1_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/BarefootSandals1_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandal1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandals1_Small.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandals1_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandals_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Preview/BarefootSandals1.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals1_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals_Small.png
Labels: asset

#1733 Bugfix: Item colour resilience
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
Labels: fix

#1734 Reindeer Hairband
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/Preview/ReindeerBand.png
  BondageClub/Assets/Female3DCG/Hat/ReindeerBand.png
  BondageClub/Assets/Female3DCG/Hat/Suspension/ReindeerBand.png
Labels: asset

#1737 Missing asset
  BondageClub/Assets/Female3DCG/ItemVulva/Kneel/VibratingDildo_End.png
Labels: asset, fix

#1741 Beta hotfix - remove ?.
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix, hotfix

#1744 Futuristic Items hotfix
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Mesh.png
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: beta-fix

#1745 Fix: removed allfours from the pose menu
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1747 Futuristic mittens can be unlocked by self in gloves mode
  BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
Labels: asset, change

#1748 Fix leashing with lover and owner locks
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1749 Bugfix: Fixes the filename casing on two Futuristic Chastity Bra assets
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallHeart_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Small_Text.png
Labels: beta-fix

#1750 Bugfix: Adds the Wiggle activity to the ItemButt group
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1751 Single-Player Room Hide fix
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: beta-fix

#1753 Bugfix: Adds missing lock assets for the heavy latex corset
  BondageClub/Assets/Female3DCG/ItemTorso/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/HeavyLatexCorset_Lock.png
Labels: beta-fix

#1754 Fix hood properties
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1755 Pink orgasm filter does not change size depending on player count
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1759 Fix dialog for some futuristic things
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#1760 Fixed over panties crotch rope to have a dialog
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#1762 Bring MouseEars1/2 and ElfEars values in line with other ear items
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1763 fix activity
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1765 Many missing assets
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_LargeStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_NormalStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_SmallStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/HeavyLatexCorset_XLargeStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_LargeStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_NormalStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_SmallStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/HeavyLatexCorset_XLargeStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/HeavyLatexCorset_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/HeavyLatexCorsetStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/HeavyLatexCorset_Lock.png
Labels: beta-fix

#1766 ItemHood in Arousal menu
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: beta-fix

#1768 Minor changes to the gwenhood
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1769 Gwen hood adjustments
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1770 Rope Over Panties message fix
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#1771 Text fit profile screen
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
  BondageClub/Scripts/Drawing.js
Labels: change

#1767 Mittens with pose menu
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: change

#1774 Missing asset
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Boots1_XLarge_Shoes.png
Labels: beta-fix

#1776 Bugfix: Fixes floating characters when leaving the dialog screen via the escape key
  BondageClub/Scripts/Dialog.js
Labels: fix

#1777 Anklets in Random Clothes
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1779 More missing assets
  BondageClub/Assets/Female3DCG/ItemArms/LatexArmbinder_Large_Strap2.png
  BondageClub/Assets/Female3DCG/ItemArms/LatexArmbinder_Normal_Strap2.png
  BondageClub/Assets/Female3DCG/ItemArms/LatexArmbinder_Small_Strap2.png
Labels: beta-fix

#1780 GP-9 Gas Mask fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1781 Bugfix: Fixes chatroom messages on the futuristic gags
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: beta-fix

#1782 Remove On Remove - Type fix
  BondageClub/Scripts/Inventory.js
Labels: fix

#1783 Bugfix: Fixes chatroom messages for the futuristic collar
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: beta-fix

#1785 Fix: Error for leashed player when leash holder fails to enter a room
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Server.js
Labels: beta-fix

#1787 Fix crash when friendnames are corrupted
  BondageClub/Screens/Character/Login/Login.js
Labels: beta-fix

#1793 Bugfix: Allow selection of legs/feet, while keeping floating character fix
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#1800 Bugfix: Reverts change to the lock asset for the leather cuffs in the yoked pose
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_Lock.png
Labels: beta-fix

#1802 Clears friendlist, room admin, and other inputs when leashed out
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: hotfix

#1803 R63 fixes
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
Labels: hotfix

#1810 Fix: Leash actions on character in boxes/cages/lockers
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1809 Bugfix: Makes the login credits independent of framerate
  BondageClub/Screens/Character/Login/Login.js
Labels: fix

#1808 New Item: Latex Ankle Shoes
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/LatexAnkleShoes_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/LatexAnkleShoes_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/LatexAnkleShoes_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/LatexAnkleShoes_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/LatexAnkleShoes_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/LatexAnkleShoes_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/LatexAnkleShoes_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/LatexAnkleShoes_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LatexAnkleShoes_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LatexAnkleShoes_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/LatexAnkleShoes_Small.png
  BondageClub/Assets/Female3DCG/Shoes/LatexAnkleShoes_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/LatexAnkleShoes_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/LatexAnkleShoes_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/LatexAnkleShoes_Small.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/LatexAnkleShoes_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Preview/LatexAnkleShoes.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/LatexAnkleShoes_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/LatexAnkleShoes_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/LatexAnkleShoes_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/LatexAnkleShoes_XLarge.png
Labels: asset

#1807 Whisper Emoticon
  BondageClub/Assets/Female3DCG/Emoticon/Whisper/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/Whisper/Icon.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1798 Feature: Changes the "OnBed" prerequisite to use a new "OnBed" effect
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Inventory.js
Labels: change

#1796 Spread eagle ropes (Arms, Feet) as extended item for hemp rope
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_LargeBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_NormalBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_SmallBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_XLargeBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemFeet/HempRope_LargeBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemFeet/HempRope_NormalBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemFeet/HempRope_SmallBedSpreadEagle.png
  BondageClub/Assets/Female3DCG/ItemFeet/HempRope_XLargeBedSpreadEagle.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/HempRope/BedSpreadEagle.png
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemFeet/HempRope/BedSpreadEagle.png
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
Labels: asset

#1792 Scroll Chat Down with Esc Key
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/index.html
Labels: improvement

#1789 Login NPC Overwrite fix
  BondageClub/Screens/Character/Login/Login.js
Labels: fix

#1784 Beta: Custom eyes closed blindness
  BondageClub/Icons/BlindToggle1.png
  BondageClub/Icons/BlindToggle2.png
  BondageClub/Icons/BlindToggle3.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: change

#1756 Futuristic Chastity Belt Reskin
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Belt.pdn
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Plug.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Normal_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Normal_Plug.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Small_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Small_Plug.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_XLarge_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_XLarge_Plug.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Normal_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Small_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_XLarge_Screen.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/FuturisticChastityBelt2.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/FuturisticChastityBelt2.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/OpenBack.png
  BondageClub/index.html
Labels: asset

#1757 Futuristic Bra Reskin
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2NoDisplay_Lock.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Display.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Large_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Large_Straps.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Lock.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Normal_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Normal_Straps.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Small_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_Small_Straps.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_XLarge_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra2_XLarge_Straps.png
  BondageClub/Assets/Female3DCG/ItemBreast/Preview/FuturisticBra2.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/Display.png
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/NoDisplay.png
  BondageClub/index.html
Labels: asset

#1758 Futuristic Harness
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/OverTheHead/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/FuturisticHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1511 Improvement: Introducing memoization and using it for extended items
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticArmbinder/FuturisticArmbinder.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
  BondageClub/Screens/Inventory/ItemArms/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
  BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/InteractiveVisor.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
Labels: asset, change

#1811 Login Character Dialog fix
  BondageClub/Screens/Character/Login/Dialog_NPC_Login.csv
Labels: fix

#1813 Improvement: Optimisation of prerequisite checking
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Scripts/Inventory.js
Labels: improvement

#1812 Fixed bug with futuristic chastity panties publish message
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/FuturisticChastityBelt2.js
Labels: fix

#1816 Bugfix: Ensures FriendNames & SubmissivesList are initialised on character creation
  BondageClub/Screens/Character/Creation/Creation.js
Labels: fix

#1814 New Item: Strict Leather Pet Crawler
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Preview/StrictLeatherPetCrawler.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Large_Arms.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Large_Legs.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Normal_Arms.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Normal_Legs.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Small_Arms.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_Small_Legs.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_XLarge_Arms.png
  BondageClub/Assets/Female3DCG/ItemArms/StrictLeatherPetCrawler_XLarge_Legs.png
Labels: asset

#1815 New Item: Elegant Heart Necklace
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Necklace/ElegantHeartNecklace_Jewels.png
  BondageClub/Assets/Female3DCG/Necklace/ElegantHeartNecklace_Necklace.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/ElegantHeartNecklace.png
Labels: asset

#1817 Funnel Gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/FunnelGagFunnel_Funnel.png
  BondageClub/Assets/Female3DCG/ItemMouth/FunnelGag_Base.png
  BondageClub/Assets/Female3DCG/ItemMouth/FunnelGag_Straps.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/FunnelGag.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/FunnelGag/Funnel.png
  BondageClub/Screens/Inventory/ItemMouth/FunnelGag/FunnelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FunnelGag/None.png
  BondageClub/index.html
Labels: asset

#1818 Improvement: Refactor cup holder gag
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/CupholderGag/CupholderGag.js
Labels: asset, refactor

#1805 New Item: Noble Corset
  BondageClub/Assets/Female3DCG/Corset/Corset6_Large_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Large_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Large_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Normal_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Normal_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Small_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Small_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_Small_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_XLarge_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Corset6_XLarge_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Large_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Large_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Large_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Normal_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Normal_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Small_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Small_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_Small_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_XLarge_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Hogtied/Corset6_XLarge_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Preview/Corset6.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Large_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Large_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Large_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Normal_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Normal_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Small_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Small_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_Small_Leather.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_XLarge_Buttons.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/Corset/Yoked/Corset6_XLarge_Leather.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1764 Pose Menu in Photography room
  BondageClub/Scripts/Dialog.js
Labels: change

#1772 Photography Room - NPC Poses
  BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
  BondageClub/Screens/Room/Photographic/Photographic.js
Labels: improvement

#1819 Bugfix: Fixes condition for the character actions dialogue option
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1820 Leash Dialog fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
Labels: fix

#1821 Bugfix: Fixes validation functions on futuristic mittens and breast harness
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
  BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
Labels: fix

#1387 Allow owners to lock lovers locks
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/GameLog.js
  BondageClub/Scripts/Server.js
Labels: feature

#1786 New: choose your background when you have a private room
  BondageClub/Icons/BedroomBackground.png
  BondageClub/Icons/CollegeBackground.png
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Private/Text_Private.csv
Labels: feature

#1773 Remove offline friends from first tab
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/FriendList/Text_FriendList.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: change

#1037 Fix: Adult baby harness mitten chain in the magic theatre corrected
  BondageClub/Screens/Room/Magic/Magic.js
Labels: fix

#1778 New Item: Medical Bed Restraints
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_Base.png
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_Large_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_Normal_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_Small_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/MedicalBedRestraints_XLarge_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/MedicalBedRestraints.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_Base.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_Large_Straps.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_Lock.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_Normal_Straps.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_Small_Straps.png
  BondageClub/Assets/Female3DCG/ItemFeet/MedicalBedRestraints_XLarge_Straps.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/MedicalBedRestraints.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_Base.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_Large_Straps.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_Lock.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_Normal_Straps.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_Small_Straps.png
  BondageClub/Assets/Female3DCG/ItemLegs/MedicalBedRestraints_XLarge_Straps.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/MedicalBedRestraints.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse.csv
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
Labels: asset

#1823 Bugfix: Fix for ServerAppearanceLoadFromBundle for private room NPCs
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Server.js
Labels: hotfix

#1825 Colour Name Validation
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
  BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
  BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js
  BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
  BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Inventory.js
Labels: fix

#1790 Leash improvements
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement

#1801 Fix: Leash actions with lover/owner lock on leash
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Server.js
Labels: hotfix

#1799 Feature: Ability to change text fonts
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Online/Game/OnlineGame.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Element.js
  BondageClub/Tools/Translation/Tools/TranslationStatus.html
Labels: feature

#1791 Improvement to pose system: Partial movement
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: improvement

#1794 New FixedHead effect
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
  BondageClub/Scripts/Activity.js
Labels: asset, change

#1832 Fix for spread pose on futuristic ankle cuffs
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FuturisticAnkleCuffs_Display.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FuturisticAnkleCuffs_Lock.png
Labels: asset, fix

#1830 Bugfix: LoverOnly/OwnerOnly items getting removed on relog
  BondageClub/Scripts/Server.js
Labels: fix

#1829 Bugfix: Fixes alpha masks for the open crotch straitdress
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1827 Improvement: Font system refinements
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Common.js
Labels: improvement

#1713 New titles
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet.csv
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_DE.txt
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_FR.txt
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_RU.txt
  BondageClub/Screens/Character/Title/English Titles.txt
  BondageClub/Screens/Character/Title/Text_Title.csv
  BondageClub/Screens/Character/Title/Text_Title_DE.txt
  BondageClub/Screens/Character/Title/Text_Title_FR.txt
  BondageClub/Screens/Character/Title/Text_Title_RU.txt
  BondageClub/Screens/Character/Title/Title.js
  BondageClub/Screens/Room/Sarah/Sarah.js
Labels: feature

#1670 Immersion Option: Return to chat room on relog
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Room/AsylumBedroom/AsylumBedroom.js
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Server.js
Labels: feature

#1836 Return to chatroom fixes
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: fix

#1840 Bed Spread-Eagle Relog Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#1838 Improvement for Activities
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/Zipties/Zipties.js
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Inventory.js
Labels: improvement
