Repository Ben987/Bondage-College, pull requests merged in 2020-09, with the labels that each got.

#1324 Advanced feature: Dynamic assets
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/Preview/CustomCollarTag.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Animation.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/index.html
Labels: feature, priority

#1384 fix eslint so it is more simple to run
  .gitignore
  BondageClub/Tools/ESLint/package.json
Labels: improvement

#1343 Refactor: Merge round and weighted nipple piercings
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercingWeightedChain_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercingWeighted_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_LargeWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_LargeWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_NormalWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_NormalWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_SmallWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_SmallWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_XLargeWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/RoundPiercing_XLargeWeightedChain.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
  BondageClub/Screens/Inventory/ItemArms/Zipties/Zipties.js
  BondageClub/Screens/Inventory/ItemDevices/Locker/Locker.js
  BondageClub/Screens/Inventory/ItemDevices/SmallLocker/SmallLocker.js
  BondageClub/Screens/Inventory/ItemDevices/SmallVentlessLocker/SmallVentlessLocker.js
  BondageClub/Screens/Inventory/ItemDevices/VentlessLocker/VentlessLocker.js
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemFeet/Zipties/Zipties.js
  BondageClub/Screens/Inventory/ItemLegs/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemLegs/Zipties/Zipties.js
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/RoundPiercing.js
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/Weighted.png
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/WeightedChain.png
  BondageClub/Screens/Inventory/ItemNipplesPiercings/WeightedPiercing/WeightedPiercing.js
  BondageClub/Screens/Inventory/ItemPelvis/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemTorso/HempRopeHarness/HempRopeHarness.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/index.html
Labels: asset, refactor

#1291 Improvement: wardrobe selection
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#1294 Feature: Extended Necklaces
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/NecklaceKey.js
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/Normal.png
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/Tucked.png
  BondageClub/Screens/Inventory/Necklace/NecklaceLock/NecklaceLock.js
  BondageClub/Screens/Inventory/Necklace/NecklaceLock/Normal.png
  BondageClub/Screens/Inventory/Necklace/NecklaceLock/Tucked.png
  BondageClub/index.html
Labels: asset

#1326 Extended Items Conversion
  BondageClub/Screens/Inventory/ItemLegs/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemPelvis/HempRope/HempRope.js
Labels: asset, fix, refactor

#1383 Request about new backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/RainyForestPathDay.jpg
  BondageClub/Backgrounds/RainyForestPathDayDark.jpg
  BondageClub/Backgrounds/RainyForstPathNight.jpg
  BondageClub/Backgrounds/RainyForstPathNightDark.jpg
  BondageClub/Backgrounds/RainyStreetDay.jpg
  BondageClub/Backgrounds/RainyStreetDayDark.jpg
  BondageClub/Backgrounds/RainyStreetNight.jpg
  BondageClub/Backgrounds/RainyStreetNightDark.jpg
  BondageClub/Backgrounds/SnowyChaletDay.jpg
  BondageClub/Backgrounds/SnowyChaletDayDark.jpg
  BondageClub/Backgrounds/SnowyChaletNight.jpg
  BondageClub/Backgrounds/SnowyChaletNightDark.jpg
  BondageClub/Backgrounds/SnowyDeepForest.jpg
  BondageClub/Backgrounds/SnowyDeepForestDark.jpg
  BondageClub/Backgrounds/SnowyForestPathDay.jpg
  BondageClub/Backgrounds/SnowyForestPathDayDark.jpg
  BondageClub/Backgrounds/SnowyForestPathNight.jpg
  BondageClub/Backgrounds/SnowyForestPathNightDark.jpg
  BondageClub/Backgrounds/SnowyLakeNight.jpg
  BondageClub/Backgrounds/SnowyLakeNightDark.jpg
  BondageClub/Backgrounds/SnowyStreetDay1.jpg
  BondageClub/Backgrounds/SnowyStreetDay1Dark.jpg
  BondageClub/Backgrounds/SnowyStreetDay2.jpg
  BondageClub/Backgrounds/SnowyStreetDay2Dark.jpg
  BondageClub/Backgrounds/SnowyStreetNight2.jpg
  BondageClub/Backgrounds/SnowyStreetNight2Dark.jpg
  BondageClub/Backgrounds/SnowyTown1.jpg
  BondageClub/Backgrounds/SnowyTown1Dark.jpg
  BondageClub/Backgrounds/SnowyTown2.jpg
  BondageClub/Backgrounds/SnowyTown2Dark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#1363 Fix: Asylum therapy click handler
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
Labels: hotfix

#1380 Fix: InventoryLock verification
  BondageClub/Scripts/Inventory.js
Labels: fix

#1367 Improvement: JSDoc comments added to Private.js
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv
  BondageClub/Screens/Room/Private/Private.js
Labels: improvement

#1365 Improvement: JSDoc comments added to Management.js
  BondageClub/Screens/Room/Management/Management.js
Labels: improvement

#1351 Refactor: Wrist Shackle extended menu conversion
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/WristShackles_LargeBehind.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/WristShackles_LockBehind.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/WristShackles_NormalBehind.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/WristShackles_SmallBehind.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/WristShackles_XLargeBehind.png
  BondageClub/Screens/Inventory/ItemArms/WristShackles/WristShackles.js
Labels: asset, refactor

#1369 Improvement: JSDoc comments added to Chatroom.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement

#1374 Fix: Missing locks
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchExtraPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchFullJacket_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchLiningStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchPaddedLining_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchPulledLining_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchPulledPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketCrotchPulledStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketExtraPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketFullJacket_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketPaddedLining_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketPulledPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/TightJacketPulledStraps_Lock.png
Labels: asset, fix

#1377 Fix: Pony Hood and Pencil skirt
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1355 HiddenItem rework
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Chains_Suspension.png
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_Suspension.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinder_Strap.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinder_WrapStrap.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/LeatherArmbinderStrap.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/LeatherArmbinderWrapStrap.png
  BondageClub/Assets/Female3DCG/ItemHidden/Preview/SuspensionChains.png
  BondageClub/Assets/Female3DCG/ItemHidden/Preview/SuspensionHempRope.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/LeatherArmbinder.js
  BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/None.png
  BondageClub/Screens/Inventory/ItemHidden/LeatherArmbinderStrap/LeatherArmbinderStrap.js
  BondageClub/Screens/Inventory/ItemHidden/LeatherArmbinderWrapStrap/LeatherArmbinderWrapStrap.js
  BondageClub/Screens/Inventory/ItemHidden/LeatherArmbinderWrapStrap/None.png
  BondageClub/Screens/Room/Magic/Magic.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/index.html
Labels: feature, refactor

#1388 Extended Item Option Layout Enhancement
  BondageClub/Scripts/ExtendedItem.js
Labels: improvement

#1327 Feature: Advanced Vibrator Modes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Icons/Online.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemButt/VibratingDildoPlug/VibratingDildoPlug.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemNipples/VibeNippleClamp/VibeNippleClamp.js
  BondageClub/Screens/Inventory/ItemNipplesPiercings/VibeHeartPiercings/VibeHeartPiercings.js
  BondageClub/Screens/Inventory/ItemVulva/LoversVibrator/LoversVibrator.js
  BondageClub/Screens/Inventory/ItemVulva/VibratingDildo/VibratingDildo.js
  BondageClub/Screens/Inventory/ItemVulvaPiercings/VibeHeartClitPiercing/VibeHeartClitPiercing.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/VibratorMode.js
  BondageClub/index.html
Labels: asset, feature

#1346 Refactor: Audio.js
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
Labels: priority, refactor

#1398 Online settings fix
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
Labels: hotfix

#1381 Fix: gas mask text
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset, fix

#1325 Feature: Adds a blinking light to the shock collar
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/ShockCollarBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemNeck/ShockCollar_Collar.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarShockUnitBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarShockUnit_Unit.png
  BondageClub/Screens/Inventory/ItemNeck/ShockCollar/ShockCollar.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
Labels: asset

#1373 New Item: Leather Bolero
  BondageClub/Assets/Female3DCG/Bra/Hogtied/LeatherCorsetTop1_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/LeatherCorsetTop1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/LeatherCorsetTop1_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/LeatherCorsetTop1_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/LeatherCorsetTop1_Large.png
  BondageClub/Assets/Female3DCG/Bra/LeatherCorsetTop1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/LeatherCorsetTop1_Small.png
  BondageClub/Assets/Female3DCG/Bra/LeatherCorsetTop1_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/LeatherCorsetTop1.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/LeatherCorsetTop1_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/LeatherCorsetTop1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/LeatherCorsetTop1_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/LeatherCorsetTop1_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Bolero/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/Bolero/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/Bolero/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/Bolero/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Horse/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/Horse/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/Horse/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/Horse/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Preview/LeatherBolero.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/LeatherBolero_Large.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/LeatherBolero_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/LeatherBolero_Small.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/LeatherBolero_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1362 Improvements: More wardrobe changes
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Scripts/Drawing.js
Labels: feature, improvement

#1389 Bugfix: Removes a duplicate DrawCanvas function
  BondageClub/Scripts/Drawing.js
Labels: fix, hotfix

#1395 Refactor: petsuit
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/BitchSuit/BitchSuit.js
Labels: asset, refactor

#1366 new clothing added
  BondageClub/Assets/Female3DCG/Bra/CowPrintedBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/CowPrintedBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/CowPrintedBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/CowPrintedBra_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/CowPrintedBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/CowPrintedBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/CowPrintedBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/CowPrintedBra_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/CowPrintedBra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CowPrintedBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CowPrintedBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CowPrintedBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CowPrintedBra_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/JeansShorts.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/StraitDressOpen/JeansShorts_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/StraitDressOpen/JeansShorts_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/StraitDressOpen/JeansShorts_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/StraitDressOpen/JeansShorts_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Panties/CowPrintedPanties_Large.png
  BondageClub/Assets/Female3DCG/Panties/CowPrintedPanties_Normal.png
  BondageClub/Assets/Female3DCG/Panties/CowPrintedPanties_Small.png
  BondageClub/Assets/Female3DCG/Panties/CowPrintedPanties_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Preview/CowPrintedPanties.png
Labels: asset

#1396 Refactor: Belt refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/OpenBack.png
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OpenBack.png
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OrnateChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/OpenBack.png
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/PolishedChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/ClosedBack.png
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/OpenBack.png
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/StuddedChastityBelt.js
  BondageClub/Scripts/Asset.js
Labels: asset, improvement, refactor

#1390 Fix: Typo fix for ear phones
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/BluetoothEarbuds.js
  BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
Labels: fix, improvement

#1400 Removed leftover file
  BondageClub/Assets/Female3DCG/HairAccessory1/ElfEars_Lower.png
Labels: asset, hotfix

#1410 Missing locks
  BondageClub/Assets/Female3DCG/ItemNeck/ShockCollarBlink_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CollarShockUnitBlink_Lock.png
Labels: asset, hotfix

#1405 Hotfix for audio.js
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
Labels: hotfix

#1415 Refactor: Duct Tape for Legs
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Scripts/ExtendedItem.js
Labels: asset, refactor

#1408 Refactor Toe tape to extended item
  BondageClub/Screens/Inventory/ItemBoots/ToeTape/ToeTape.js
Labels: asset, refactor

#1403 Refactor: Plug gag
  BondageClub/Screens/Inventory/ItemMouth/PlugGag/PlugGag.js
Labels: asset, refactor

#1393 Refactor: Leather strait jacket to extended items
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/LeatherStraitJacket/LeatherStraitJacket.js
Labels: asset, refactor

#1311 Colorable blush, emoticons, and fluids
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: improvement

#1385 Reduce CharacterRefresh calls as #639
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Inventory.js
Labels: improvement

#1401 Fix: Rope conversion.
  BondageClub/Screens/Inventory/ItemTorso/NylonRopeHarness/NylonRopeHarness.js
Labels: asset, hotfix

#1428 Fix: Grey rooms
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#1336 Feature: Active pose system rework + Enhanced character menu
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/LeatherCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/LeatherCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/LeatherCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/LeatherCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/LeatherCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Large_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Normal_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_Small_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/OrnateCuffs_XLarge_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/LeatherCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Large_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Normal_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_Small_Gems.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/OrnateCuffs_XLarge_Gems.png
  BondageClub/Icons/Poses/BackBoxTie.png
  BondageClub/Icons/Poses/BackCuffs.png
  BondageClub/Icons/Poses/BackElbowTouch.png
  BondageClub/Icons/Poses/BaseLower.png
  BondageClub/Icons/Poses/BaseUpper.png
  BondageClub/Icons/Poses/Kneel.png
  BondageClub/Icons/Poses/LegsClosed.png
  BondageClub/Icons/Poses/OverTheHead.png
  BondageClub/Icons/Poses/Yoked.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Cutscene/NPCCollaring/NPCCollaring.js
  BondageClub/Screens/Cutscene/PlayerCollaring/PlayerCollaring.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
  BondageClub/Screens/Room/Cell/Cell.js
  BondageClub/Screens/Room/DailyJob/DailyJob.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Screens/Room/Nursery/Nursery.js
  BondageClub/Screens/Room/Photographic/Photographic.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: feature, fix, improvement, priority, server

#1429 Fix for leg and active poses
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: hotfix

#1414 Asset has type: lock
  BondageClub/Scripts/CommonDraw.js
Labels: hotfix, priority

#1402 Refactor: cloth gag conversion
  BondageClub/Screens/Inventory/ItemMouth/ClothGag/ClothGag.js
  BondageClub/Screens/Inventory/ItemMouth2/ClothGag/ClothGag.js
  BondageClub/Screens/Inventory/ItemMouth3/ClothGag/ClothGag.js
Labels: asset, fix, refactor

#1382 More disabled buttons
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/ExtendedItem.js
Labels: improvement

#1386 remove expensive JSON.stringify call from Dialog draw
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: improvement, priority

#1409 Refactor: Anal hook to extended item script
  BondageClub/Screens/Inventory/ItemButt/AnalHook/AnalHook.js
Labels: asset, refactor

#1331 Random Asset Selection
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Icons/WearRandom.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Inventory.js
Labels: feature

#1397 Refactor: Item arms ornate cuffs to extended item
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/OrnateCuffs/OrnateCuffs.js
Labels: asset, refactor

#1425 Refactor: Bottle
  BondageClub/Screens/Inventory/ItemMouth/MilkBottle/MilkBottle.js
Labels: asset, refactor

#1424 Refactor: Armbinder
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/LeatherArmbinder.js
Labels: asset, refactor

#1423 Refactor: Crib
  BondageClub/Screens/Inventory/ItemDevices/Crib/Crib.js
Labels: asset, refactor

#1427 New Item: Rhinestone Sandals
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/SandalsRS_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/SandalsRS_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/SandalsRS_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/SandalsRS_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/SandalsRS_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/SandalsRS_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/SandalsRS_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/SandalsRS_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/SandalsRS_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/SandalsRS_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/SandalsRS_Small.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/SandalsRS_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Preview/SandalsRS.png
  BondageClub/Assets/Female3DCG/Shoes/SandalsRS_Large.png
  BondageClub/Assets/Female3DCG/Shoes/SandalsRS_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/SandalsRS_Small.png
  BondageClub/Assets/Female3DCG/Shoes/SandalsRS_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/SandalsRS_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/SandalsRS_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/SandalsRS_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/SandalsRS_XLarge.png
Labels: asset

#1411 Fix inventory refresh with locks
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: hotfix, priority

#1407 Refactor: Strait jacket to extended item
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/StraitJacket/StraitJacket.js
Labels: asset, has-dependencies, refactor

#1433 New Handheld item: shock wand
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysShockWand.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/ShockWand.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#1404 Refactor: Mouth duct tape
  BondageClub/Screens/Inventory/ItemMouth/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemMouth2/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemMouth3/DuctTape/DuctTape.js
Labels: asset, refactor

#1416 Refactor: Chains for Legs
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
Labels: asset, refactor

#1437 Fixed stuff like ̺̺ͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩ…
  BondageClub/CSS/Styles.css
Labels: fix

#1368 Feature: Multi Colouring
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_CrotchStrapsDouble.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_CrotchStrapsSingle.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_CrotchStrapsTriple.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Large_StrapsBack.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Large_StrapsFront.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Large_StrapsLoose.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Normal_StrapsBack.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Normal_StrapsFront.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Normal_StrapsLoose.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Small_StrapsBack.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Small_StrapsFront.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_Small_StrapsLoose.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_XLarge_StrapsBack.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_XLarge_StrapsFront.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacket_XLarge_StrapsLoose.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.csv
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Mouse.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Text.js
  BondageClub/index.html
Labels: change, feature

#1364 Fix: slave collar change
  BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress.csv
  BondageClub/Screens/Room/Management/Management.js
Labels: fix

#1378 New Item: Mermaid outfit
  BondageClub/Assets/Female3DCG/Bra/Clamshell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Clamshell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Clamshell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Clamshell_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Clamshell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Clamshell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Clamshell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Clamshell_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/Clamshell.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Clamshell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Clamshell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Clamshell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Clamshell_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/Preview/Snorkel.png
  BondageClub/Assets/Female3DCG/ItemHead/Snorkel_Lens.png
  BondageClub/Assets/Female3DCG/ItemHead/Snorkel_Mask.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackBoxTie/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackBoxTie/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackBoxTie/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackBoxTie/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackCuffs/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackCuffs/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackCuffs/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackCuffs/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackElbowTouch/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackElbowTouch/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackElbowTouch/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/BackElbowTouch/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/MermaidTail_Lock.png
  BondageClub/Assets/Female3DCG/ItemLegs/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/OverTheHead/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/OverTheHead/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/OverTheHead/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/OverTheHead/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/MermaidTail.png
  BondageClub/Assets/Female3DCG/ItemLegs/TapedHands/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/TapedHands/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/TapedHands/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/TapedHands/MermaidTail_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/yoked/MermaidTail_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/yoked/MermaidTail_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/yoked/MermaidTail_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/yoked/MermaidTail_XLarge.png
  BondageClub/Screens/Inventory/ItemLegs/MermaidTail/MermaidTail.js
  BondageClub/Scripts/Inventory.js
  BondageClub/index.html
Labels: asset

#1419 Fix: lower suit
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1333 Improvement: Optional slave collar (a.k.a The one)
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Server.js
Labels: improvement

#1399 Wardrobe permissions
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairAccessory3/GiantBow1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/HairFeathers1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/HairFlower1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/GiantBow1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/HairFeathers1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/HairFlower1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/Ribbons1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/Ribbons2.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/Ribbons3.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/Ribbons4.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/WeddingVeil1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Ribbons1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Ribbons2.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Ribbons3.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Ribbons4.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/GiantBow1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/HairFeathers1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/HairFlower1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/Ribbons1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/Ribbons3.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/Ribbons4.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Suspension/WeddingVeil1.png
  BondageClub/Assets/Female3DCG/HairAccessory3/WeddingVeil1.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Character.js
Labels: feature, server

#1447 Improvement: Multi Colour Button
  BondageClub/Icons/MultiColor.png
  BondageClub/Icons/MultiColorPick.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/Dialog.js
Labels: improvement

#1413 Refactor: ornate cuffs (ItemFeet)
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemFeet/OrnateAnkleCuffs/Closed.png
  BondageClub/Screens/Inventory/ItemFeet/OrnateAnkleCuffs/None.png
  BondageClub/Screens/Inventory/ItemFeet/OrnateAnkleCuffs/OrnateAnkleCuffs.js
Labels: asset, refactor

#1418 Refactor: Tape (ItemFeet)
  BondageClub/Screens/Inventory/ItemFeet/DuctTape/DuctTape.js
Labels: asset, refactor

#1420 Refactor: inflatable body bag
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/InflatableBodyBag/InflatableBodyBag.js
Labels: asset, refactor

#1421 Refactor: teddy bear
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Bear.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Bunny.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Fox.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Kitty.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Pony.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/Pup.png
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/TeddyBear.js
Labels: asset, refactor

#1422 Refactor: bondage bench straps + clean up
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/BondageBenchStraps.js
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
Labels: asset, refactor

#1448 Bugdix: Fixes head colour for Bondage College NPCs
  BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
  BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
  BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js
  BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
  BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
  BondageClub/Screens/Room/Sarah/Sarah.js
Labels: fix

#1450 Fix when given mittens in the nursery
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
Labels: fix

#1451 Fix tray check when talking to cafe maid
  BondageClub/Screens/Room/Cafe/Cafe.js
Labels: fix

#1446 New handheld: Lotion bottle
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysLotion.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Lotion.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#1455 Fix: Hair group 3 hide properties
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, hotfix

#1443 Improvement: Remove loop variable modification
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Room/Magic/Magic.js
  BondageClub/Screens/Room/Stable/Stable.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Translation.js
Labels: refactor

#1456 Fix enclose in item properties
  BondageClub/Scripts/Inventory.js
Labels: fix

#1332 Feature: Keep NPCs from removing Cosplay items
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
Labels: change

#1460 fix EnableAfkTimer in prefernece init
  BondageClub/Screens/Character/Preference/Preference.js
Labels: fix

#1436 Refactor: ClitSuctionCup to extended item
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulva/ClitSuctionCup/ClitSuctionCup.js
  BondageClub/Scripts/ExtendedItem.js
Labels: asset, refactor

#1457 Change: SelfUnlock
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: change, fix

#1430 Improvement: Pose behavior
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: improvement

#1458 fix chatroom chat character escape garbling and '&'
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1461 Refactor: Use IsNpc instead of string compares
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Server.js
Labels: refactor

#1467 Fix isnpc
  BondageClub/Scripts/Server.js
Labels: hotfix

#1468 Login Random Character Fix
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
Labels: hotfix

#1439 Refactor: Nipple suction cups to extended items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNipples/NippleSuctionCups/NippleSuctionCups.js
Labels: asset, refactor

#1475 Seamless suits expose same slots as the zipper versions
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#1441 Refactor: Collar cuffs to extended items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/CollarCuffs/CollarCuffs.js
Labels: asset, refactor

#1442 Refactor: Mouth pump gag to extended items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemMouth/PumpGag/PumpGag.js
Labels: asset, refactor

#1464 Bed Asset update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemAddon/BedChains.png
  BondageClub/Assets/Female3DCG/ItemAddon/BedChains_Lock.png
  BondageClub/Assets/Female3DCG/ItemAddon/BedRopes.png
  BondageClub/Assets/Female3DCG/ItemAddon/BedStraps.png
  BondageClub/Assets/Female3DCG/ItemAddon/BedStraps_Lock.png
  BondageClub/Assets/Female3DCG/ItemAddon/BedTape.png
  BondageClub/Assets/Female3DCG/ItemAddon/Covers_Inner.png
  BondageClub/Assets/Female3DCG/ItemAddon/Covers_Outer.png
  BondageClub/Assets/Female3DCG/ItemArms/UnderBedBondageCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/UnderBedBondageCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/UnderBedBondageCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/UnderBedBondageCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_BedFrame.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_BottomPillow.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_CoverInner.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_CoverOuter.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_Headboard.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_Mattress.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_Pillow.png
  BondageClub/Assets/Female3DCG/ItemDevices/Bed_TopPillow.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1452 Refactor: Inflatable ball hood
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemHood/InflatedBallHood/InflatedBallHood.js
Labels: asset, refactor

#1453 Refactor: Nose ring to use extended items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
Labels: asset, refactor

#1459 add option to preserve whitespaces in chat
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement

#1417 Refactor: Chains (ItemFeet)
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
Labels: asset, refactor

#1465 Feature: Extended item permissions
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: improvement, refactor

#1487 Fix for pose handling
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#1496 Gags with mouths
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix, improvement

#1469 Fix: missing assets
  BondageClub/Assets/Female3DCG/Bra/ClamShell_Large.png
  BondageClub/Assets/Female3DCG/Bra/ClamShell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/ClamShell_Small.png
  BondageClub/Assets/Female3DCG/Bra/ClamShell_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/ClamShell.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/ClamShell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/ClamShell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/ClamShell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/ClamShell_XLarge.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/Cowtail.png
  BondageClub/Assets/Female3DCG/ItemButt/Cowtail.png
  BondageClub/Assets/Female3DCG/ItemButt/Preview/Cowtail.png
Labels: asset, hotfix

#1470 Improvement: Active pose behavior
  BondageClub/Scripts/Character.js
Labels: improvement

#1479 Improvement: Adds AllowColorizeAll & HideColoring attributes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/Asset.js
Labels: improvement

#1486 Feature/Bugfix: Adds a chat preference for colouring activities
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: feature, fix

#1491 Activity translation
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Scripts/Activity.js
Labels: improvement, translation

#1490 Bugfix: Ensures the correct translation files are used by the TextCache
  BondageClub/Scripts/Text.js
Labels: fix, translation

#1488 Updated FR files
  BondageClub/Assets/Female3DCG/ColorGroups_FR.txt
  BondageClub/Assets/Female3DCG/Female3DCG_FR.txt
  BondageClub/Assets/Female3DCG/LayerNames_FR.txt
  BondageClub/Screens/Character/Appearance/Text_Appearance_FR.txt
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_FR.txt
  BondageClub/Screens/Character/ItemColor/ItemColor_FR.txt
  BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_FR.txt
  BondageClub/Screens/Character/Preference/ActivityDictionary_FR.txt
  BondageClub/Screens/Character/Preference/Text_Preference_FR.txt
  BondageClub/Screens/Character/Relog/Text_Relog_FR.txt
  BondageClub/Screens/Character/Title/Text_Title_FR.txt
  BondageClub/Screens/MiniGame/DojoStruggle/Text_DojoStruggle_FR.txt
  BondageClub/Screens/MiniGame/PuppyWalker/Text_PuppyWalker_FR.txt
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom_FR.txt
  BondageClub/Screens/Room/DailyJob/Dialog_NPC_DailyJob_DojoTeacher_FR.txt
  BondageClub/Screens/Room/DailyJob/Dialog_NPC_DailyJob_PuppyMistress_FR.txt
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub_FR.txt
  BondageClub/Screens/Room/LARP/Text_LARP_FR.txt
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid_FR.txt
  BondageClub/Screens/Room/MainHall/Text_MainHall_FR.txt
  BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Student_FR.txt
  BondageClub/Scripts/Translation.js
Labels: has-dependencies, translation

#1499 Fix multicolor picker crash
  BondageClub/Scripts/Character.js
Labels: hotfix

#1500 Kneeling with spreader bars
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#1463 Extended Item - Miscellaneous Improvements
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/RoundPiercing.js
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/NecklaceKey.js
  BondageClub/Scripts/ExtendedItem.js
Labels: improvement

#1379 Improvement: Unique Gag Prerequisites
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: improvement

#1342 Infatable leotard
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotard.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardBloated.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardBloated_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardInflated.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardInflated_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardMax.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotardMax_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/InflatableStraightLeotard_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/InflatableStraightLeotard.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/Bloated.png
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/InflatableStraightLeotard.js
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/Inflated.png
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/Light.png
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/Max.png
  BondageClub/index.html
Labels: asset

#1466 Server Limited Permission Validation
  BondageClub/Scripts/Server.js
Labels: fix

#1498 Fix refresh weirdness
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/ExtendedItem.js
Labels: fix

#1505 Bunny Ears Multicolouring
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairAccessory1/BunnyEars2.png
  BondageClub/Assets/Female3DCG/HairAccessory1/BunnyEars2_Inner.png
  BondageClub/Assets/Female3DCG/HairAccessory1/BunnyEars2_Outer.png
  BondageClub/Assets/Female3DCG/HairAccessory1/Suspension/BunnyEars2.png
  BondageClub/Assets/Female3DCG/HairAccessory1/Suspension/BunnyEars2_Inner.png
  BondageClub/Assets/Female3DCG/HairAccessory1/Suspension/BunnyEars2_Outer.png
  BondageClub/Assets/Female3DCG/HairAccessory2/BunnyEars2.png
  BondageClub/Assets/Female3DCG/HairAccessory2/BunnyEars2_Inner.png
  BondageClub/Assets/Female3DCG/HairAccessory2/BunnyEars2_Outer.png
  BondageClub/Assets/Female3DCG/HairAccessory2/Suspension/BunnyEars2.png
  BondageClub/Assets/Female3DCG/HairAccessory2/Suspension/BunnyEars2_Inner.png
  BondageClub/Assets/Female3DCG/HairAccessory2/Suspension/BunnyEars2_Outer.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, improvement

#1508 fix unchecked OnlineSharedSettings as null
  BondageClub/Scripts/Character.js
Labels: fix

#1504 Extended Item - Miscellaneous Improvements part 2
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/BondageBenchStraps.js
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemArms/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Scripts/ExtendedItem.js
Labels: fix, improvement

#1513 New backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/EgyptianExhibit.jpg
  BondageClub/Backgrounds/EgyptianExhibitDark.jpg
  BondageClub/Backgrounds/NightClub.jpg
  BondageClub/Backgrounds/NightClubDark.jpg
  BondageClub/Backgrounds/SciFiOutdoors.jpg
  BondageClub/Backgrounds/SciFiOutdoorsDark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#1493 Rope and Chains Refactor
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
Labels: asset, refactor

#1503 Preference screen crash
  BondageClub/Scripts/Server.js
Labels: fix

#1509 New item: Wooden Cuffs for hands and feet
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Preview/WoodenCuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/WoodenCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/WoodenCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/WoodenCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/WoodenCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/WoodenCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/WoodenCuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/WoodenCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/WoodenCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemFeet/WoodenCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/WoodenCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/WoodenCuffs_XLarge.png
  BondageClub/Audio/WoodenCuffs.mp3
  BondageClub/Scripts/Audio.js
Labels: asset
