Repository Ben987/Bondage-College, pull requests merged in 2020-11, with the labels that each got.

#1627 Immersion Settings
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change, improvement

#1449 Refactor: Bondage bench to extended items
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemAddon/Preview/BondageBenchStraps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchFull_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchFull_Straps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchHeavy_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchHeavy_Straps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchLight_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchLight_Straps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchNormal_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchNormal_Straps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBench_Bench.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBench_Straps.png
  BondageClub/Assets/Female3DCG/ItemDevices/BondageBenchstraps.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/BondageBenchStraps.js
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/Full.png
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/Heavy.png
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/Light.png
  BondageClub/Screens/Inventory/ItemAddon/BondageBenchStraps/Normal.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/Full.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/Heavy.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/Light.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/None.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/Normal.png
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/StrapUp.png
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: asset, refactor

#1633 Bugfix: Fix for vibrators removing locks from an item
  BondageClub/Scripts/VibratorMode.js
Labels: fix

#1634 Extended Items Lock fix
  BondageClub/Scripts/ExtendedItem.js
Labels: fix

#1637 Unlocked Gag Garble fix
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/Timer.js
Labels: fix

#1638 GP9 Gas Mask
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Edges.png
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Lens.png
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Mask.png
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Mouth.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/GP9GasMask.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1639 GP9 Gas Mask Lock
  BondageClub/Assets/Female3DCG/ItemHood/GP9GasMask_Lock.png
Labels: asset

#1640 Latex Room & Open Face Hood
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/OpenFaceHood.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/OpenFaceHood.png
  BondageClub/Assets/Female3DCG/Mask/OpenFaceHood.png
  BondageClub/Assets/Female3DCG/Mask/Preview/OpenFaceHood.png
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/LatexRoom.jpg
  BondageClub/Backgrounds/LatexRoomDark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#1642 Self-Bondage Difficulty for Extended Types
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
  BondageClub/Scripts/ExtendedItem.js
Labels: change, fix

#1647 Bugfix: Vibrator mode error
  BondageClub/Scripts/VibratorMode.js
Labels: beta-fix

#1648 Fix: Automatic OOC whisper history
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1649 Chat Search - Game Label fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix

#1653 Futuristic Armbinder Lock fix
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticArmbinderTight_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticArmbinder_Lock.png
Labels: beta-fix

#1654 Revert: OOC chat and whisper garbling
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
Labels: beta-fix

#1655 Hidden Item Hiding fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix, fix

#1656 Box Tie Armbinder Alpha Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1657 Bugfix: Locks blocking type switching
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: beta-fix

#1658 Clamshell Hogtied Images fix
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/ClamShell_XLarge.png
Labels: asset, fix

#1659 Large Asian Overhead fix
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Large_Asian.png
Labels: fix

#1661 Fix the futuristic panel gag from saying High sensitivity on Medium
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: beta-fix

#1664 Bugfix: Issue with non-lockable items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: beta-fix

#1665 Futuristic Armbinder Layer Names
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix

#1676 College Entrance Colour Check fix
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
Labels: hotfix

#1679 Rope/Gag/Lock Emoticons
  BondageClub/Assets/Female3DCG/Emoticon/LoveGag/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/LoveGag/Icon.png
  BondageClub/Assets/Female3DCG/Emoticon/LoveLock/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/LoveLock/Icon.png
  BondageClub/Assets/Female3DCG/Emoticon/LoveRope/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/LoveRope/Icon.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1674 Futuristic Collar now locks itself
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: asset, change

#1671 if OOC disabled, also block whispers while gagged
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1662 Futuristic Collar 'Copy Colors' Feature
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/FuturisticCollar_Mesh.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: asset, feature

#1703 New hood
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/GwenHood.png
  BondageClub/Assets/Female3DCG/ItemHood/GwenHood_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/GwenHood.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/GwenHood/GwenHood.js
  BondageClub/index.html
Labels: asset

#1677 Offline friends&submissives
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/FriendList/Text_FriendList.csv
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: feature, server
