Repository Ben987/Bondage-College, pull requests merged in 2021-05, with the labels that each got.

#2386 Fix: allows one to login with invalid skills/reps
  BondageClub/Scripts/Reputation.js
  BondageClub/Scripts/Skill.js
Labels: fix

#2351 Bugfix/Improvement: Menu button permission clarifications
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Validation.js
Labels: fix, improvement

#1476 JSDoc: Typedef + jsconfig.json
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/LZString.d.ts
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/jsconfig.json
Labels: improvement

#2385 Feature: BlindFlash
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Timer.js
Labels: feature

#2397 Sci Fi Pleasure Panties assets
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Large_Mesh1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Large_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Normal_Mesh1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Normal_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Small_Mesh1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Small_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_XLarge_Mesh1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_XLarge_Mesh2.png
Labels: asset, change

#2396 Chat Setting: Shrink non-dialogue
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2395 Refactor: VibratingDildoBar to extended vibrator script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemFeet/SpreaderVibratingDildoBar/SpreaderVibratingDildoBar.js
Labels: refactor

#2394 Tennis ball
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/Ball_Base.png
  BondageClub/Assets/Female3DCG/ItemMouth/Ball_Stripes.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/Ball.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2391 Refactor: Set bitch suit to new archetypes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/BitchSuit/BitchSuit.js
  BondageClub/index.html
Labels: refactor

#2390 Kinky Dungeon 1.31
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Electrify.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/ElectrifyHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeSnake.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/WitchShock.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/BlueKey.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/GreenKey.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/RedKey.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: feature

#2392 Cleanup: Scripts formatting (Part 11 - `Screens/Room/*`)
  BondageClub/Screens/Room/Arcade/Arcade.js
  BondageClub/Screens/Room/AsylumBedroom/AsylumBedroom.js
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
  BondageClub/Screens/Room/AsylumMeeting/AsylumMeeting.js
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Screens/Room/Cell/Cell.js
  BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
  BondageClub/Screens/Room/CollegeChess/CollegeChess.js
  BondageClub/Screens/Room/CollegeDetention/CollegeDetention.js
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
  BondageClub/Screens/Room/CollegeTeacher/CollegeTeacher.js
  BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
  BondageClub/Screens/Room/CollegeTheater/CollegeTheater.js
  BondageClub/Screens/Room/DailyJob/DailyJob.js
  BondageClub/Screens/Room/Empty/Empty.js
  BondageClub/Screens/Room/Gambling/Gambling.js
  BondageClub/Screens/Room/Infiltration/Infiltration.js
  BondageClub/Screens/Room/InfiltrationPerks/InfiltrationPerks.js
  BondageClub/Screens/Room/Introduction/Introduction.js
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Screens/Room/LARP/LARP.js
  BondageClub/Screens/Room/Magic/Magic.js
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Screens/Room/MovieStudio/MovieStudio.js
  BondageClub/Screens/Room/Nursery/Nursery.js
  BondageClub/Screens/Room/Pandora/Pandora.js
  BondageClub/Screens/Room/Photographic/Photographic.js
  BondageClub/Screens/Room/Prison/Prison.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Screens/Room/SlaveMarket/SlaveMarket.js
  BondageClub/Screens/Room/Stable/Stable.js
Labels: improvement

#2393 Cleanup: Scripts formatting (Part 12 - `Screens/*` - rest)
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/BackgroundSelection/BackgroundSelection.js
  BondageClub/Screens/Character/Cheat/Cheat.js
  BondageClub/Screens/Character/Creation/Creation.js
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
  BondageClub/Screens/Character/PasswordReset/PasswordReset.js
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Character/Title/Title.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/MiniGame/Chess/BondageChess.js
  BondageClub/Screens/MiniGame/GetUp/GetUp.js
  BondageClub/Screens/MiniGame/HorseWalk/HorseWalk.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/MiniGame/MaidCleaning/MaidCleaning.js
  BondageClub/Screens/MiniGame/MaidDrinks/MaidDrinks.js
  BondageClub/Screens/MiniGame/PlayerAuction/PlayerAuction.js
  BondageClub/Screens/MiniGame/PuppyWalker/PuppyWalker.js
  BondageClub/Screens/MiniGame/RhythmGame/RhythmGame.js
  BondageClub/Screens/MiniGame/SlaveAuction/SlaveAuction.js
  BondageClub/Screens/MiniGame/Tennis/Tennis.js
  BondageClub/Screens/MiniGame/Therapy/Therapy.js
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
Labels: improvement

#2403 "Hide others' Messages" applies to Hide Names sensory deprivation option
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change

#2402 Feature: Auto-generates `AllowEffect` and `AllowBlock` on typed items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/TypedItem.js
Labels: improvement

#2401 Refactor: Ceiling shackles to new archetypes
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/CeilingShackles/CeilingShackles.js
  BondageClub/index.html
Labels: refactor

#2273 ChatRoomSync-Split: Enable ChatRoomSyncCharacter
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2276 ChatRoomSync-Split: Enable ChatRoomSyncRoomProperties
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2339 More Multiplayer Backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/SchoolHallway.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#2398 Plastic wrap
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth2/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth2/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/PlasticWrap.png
Labels: asset

#2407 Bugfix: Fixes linting errors
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/Room/Pandora/Pandora.js
Labels: fix

#2408 Bugfix: Re-enables `DarkFactor` inside minigames
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Scripts/Drawing.js
Labels: fix

#2410 Fix: Ceiling Shackles
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2413 Feature: Modular item `Effect` support
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: improvement

#2411 Fix latex posture collar gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2416 Feature: Futuristic & Cage Muzzles in all mouth groups
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/CageMuzzle_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/CageMuzzle_Muzzle.png
  BondageClub/Assets/Female3DCG/ItemMouth/CageMuzzle_Strap.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticMuzzle.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticMuzzle_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/CageMuzzle.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/FuturisticMuzzle.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, change

#2417 Kinky Dungeon 1.35
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: feature

#2420 Preferences & Checkboxes tweaks
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Scripts/Drawing.js
Labels: change, refactor

#2422 Bugfix/Improvement: Better compatibility for `HideForPose`
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix, improvement

#2423 Improvement: `ItemBoots` is now shown in the `Spread` pose by default
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: has-dependencies, improvement

#2424 Bugfix: Type definition & JSDoc fixes
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#2425 Kinky Dungeon 1.37
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Blink.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BlinkHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/GreaterShield.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/GreaterShieldHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Leap.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/LeapHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Shield.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/ShieldHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Shroud.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/ShroudHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature, improvement

#2426 Prevent players that are leashed from leaving
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change

#2429 Bugfix: `HideForPose`/`HideAs` compatibility issue
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#2432 Pandora Button Hover
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Supervisor.csv
  BondageClub/Screens/Room/Pandora/Pandora.js
Labels: change

#2431 Locker Opacity
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Locker.png
  BondageClub/Assets/Female3DCG/ItemDevices/LockerOpaque.png
  BondageClub/Assets/Female3DCG/ItemDevices/LockerVentless_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/LockerVentless_VentCovers.png
  BondageClub/Assets/Female3DCG/ItemDevices/Locker_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Locker_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/Locker_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/Locker_Handle.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLocker.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLockerOpaque.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLockerOpaque_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLockerVentless_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLockerVentless_VentCovers.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLocker_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLocker_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLocker_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallLocker_Handle.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallVentlessLocker.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallVentlessLockerOpaque.png
  BondageClub/Assets/Female3DCG/ItemDevices/SmallVentlessOpaqueLocker_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/VentlessLocker.png
  BondageClub/Assets/Female3DCG/ItemDevices/VentlessLockerOpaque.png
  BondageClub/Assets/Female3DCG/ItemDevices/VentlessLockerOpaque_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/VentlessLocker_Lock.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Locker/Locker.js
  BondageClub/Screens/Inventory/ItemDevices/Locker/Seethrough.png
  BondageClub/Screens/Inventory/ItemDevices/Locker/Ventless.png
  BondageClub/Screens/Inventory/ItemDevices/Locker/Vents.png
  BondageClub/Screens/Inventory/ItemDevices/SmallLocker/Seethrough.png
  BondageClub/Screens/Inventory/ItemDevices/SmallLocker/SmallLocker.js
  BondageClub/Screens/Inventory/ItemDevices/SmallLocker/Ventless.png
  BondageClub/Screens/Inventory/ItemDevices/SmallLocker/Vents.png
  BondageClub/Screens/Inventory/ItemDevices/SmallVentlessLocker/Opaque.png
  BondageClub/Screens/Inventory/ItemDevices/SmallVentlessLocker/Seethrough.png
  BondageClub/Screens/Inventory/ItemDevices/SmallVentlessLocker/SmallVentlessLocker.js
  BondageClub/Screens/Inventory/ItemDevices/VentlessLocker/Opaque.png
  BondageClub/Screens/Inventory/ItemDevices/VentlessLocker/Seethrough.png
  BondageClub/Screens/Inventory/ItemDevices/VentlessLocker/VentlessLocker.js
  BondageClub/Scripts/Common.js
  BondageClub/index.html
Labels: asset, improvement

#2430 Bugfix: Better null safety on combination padlock extended menu
  BondageClub/Screens/Inventory/ItemMisc/CombinationPadlock/CombinationPadlock.js
Labels: fix

#2400 Changelog: R68 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2434 futuristic heels fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels2_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels2_Shine.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels2_Soles.png
Labels: beta-fix

#2436 Notification Popup fix
  BondageClub/Scripts/Notification.js
Labels: beta-fix

#2437 kinky dungeon fixes
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: beta-fix

#2438 ItemBoots Color Schema
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: change

#2439 Added sound to futuristic vibrator shock
  BondageClub/Scripts/Audio.js
Labels: beta-fix

#2440 Beta fix for clit ring
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2441 Bunny Mask Fix
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/Mask/BunnyMask1/BunnyMask1.js
  BondageClub/index.html
Labels: beta-fix, refactor

#2442 Character Down Button
  BondageClub/Icons/Down.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2443 Removed Floating Pixels on Swimsuits
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_Large.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_Small.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit2_Large.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit2_Small.png
Labels: asset

#2445 Fixes for futuristic collar
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: beta-fix, change

#2447 AllowRemoveExclusive now set correctly in Asset.js
  BondageClub/Scripts/Asset.js
Labels: fix

#2448 Fix kinky dungeon being unable to cast spells while in a box IRL
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix, refactor

#2449 If a leashing player disconnects, the leash is broken
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix, change

#2450 Bugfix: WebGL alpha blending
  BondageClub/Scripts/GLDraw.js
Labels: fix

#2446 Futuristic Recolor Refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Scripts/Asset.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: refactor

#2453 Fixed Dungeoneer reputation
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/Room/Arcade/Arcade.js
Labels: beta-fix

#2454 Bugfix: Locks breaking gag effects
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: beta-fix

#2455 Shading changes on futuristic items
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels2_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels2_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/FuturisticHeels2_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/FuturisticMittensGloves_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/FuturisticMittens_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/FuturisticMittensGloves_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/FuturisticMittens_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/FuturisticMittensGloves_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/FuturisticMittens_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/FuturisticMittensGloves_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/FuturisticMittens_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/FuturisticMittensGloves_Mesh.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/FuturisticMittens_Mesh.png
Labels: asset, change

#2456 MemberNumber = null for locks on player
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
Labels: beta-fix

#2457 Fixed Undefined in kinky dungeon Shroud spell description
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
Labels: beta-fix

#2459 [Beta Fix] [Asset] {Natsuki}: Plastic wrap fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/PlasticWrap_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/PlasticWrap_XLarge.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/PlasticWrap_XLarge.png
Labels: beta-fix

#2462 Fixes futuristic vibrator to work as it did before
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Speech.js
Labels: fix

#2463 Futuristic Collar Crash Prevention
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: beta-fix

#2464 Changelog: Updates changelog for R68 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2465 Fix for ribbon application
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2467 fix: metal leg spreader
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2468 Changelog: R68 Release
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2470 Bugfix: Ensures pose refresh on loading wardrobe outfit
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
Labels: fix

#2471 Revert to Default Bugfix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2473 Chess Calculation Fix
  BondageClub/Screens/MiniGame/Chess/chess.js
Labels: hotfix

#2476 Fixes issue where owner/lover lock on a leash makes it impossible to use
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: hotfix

#2478 Increases size of text field for safeword padlock
  BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
Labels: hotfix

#2479 Stimulation Messages Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2480 Kinky Dungeon Targeting Fix
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
Labels: fix, hotfix

#2481 Avoid removing keys when picking lock in kinky dungeon
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
Labels: hotfix

#2487 Bugfix/Refactor: Removes `AccessVulvaSuitZip` prerequisite & `Expose` on `SuitLower`
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Inventory.js
Labels: change, fix

#2485 Bugfix: Item update rollback mitigation
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2484 ExtendedItem Page Button
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/ExtendedItem.js
Labels: change

#2474 Bugfix: Ensures items get removed with timer locks
  BondageClub/Scripts/Timer.js
Labels: fix

#2472 Extended Self-Block Validation Fix
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/ExtendedItem.js
Labels: fix

#2458 Future vibe support for multiple commands at once
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: improvement

#2460 Feature: Serving Tray item
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/ServingTray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayFull.png
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Empty.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Full.png
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
Labels: asset, feature

#2495 [Asset] {Natsuki} Latching Pony Bit Gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/HarnessPonyBitsDetached_Metal.png
  BondageClub/Assets/Female3DCG/ItemMouth/HarnessPonyBits_Metal.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/HarnessPonyBits/Attached.png
  BondageClub/Screens/Inventory/ItemMouth/HarnessPonyBits/Detached.png
Labels: asset

#2494 Bugfix: `SetPose` property validation
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Validation.js
Labels: fix

#2493 New item: Steel Ankle Cuffs
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/SteelAnkleCuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_XLarge.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemFeet/SteelAnkleCuffs/Closed.png
  BondageClub/Screens/Inventory/ItemFeet/SteelAnkleCuffs/None.png
Labels: asset

#2492 New item: Steel Cuffs
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/SteelCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/SteelCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/SteelCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/SteelCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/SteelCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/SteelCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/SteelCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/SteelCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/SteelCuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/SteelCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/SteelCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/SteelCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/SteelCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/SteelCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/SteelCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/SteelCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/SteelCuffs_XLarge.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/SteelCuffs/None.png
  BondageClub/Screens/Inventory/ItemArms/SteelCuffs/Wrist.png
Labels: asset

#2491 New item: Shiny Steel Collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/ShinySteelCollar.png
  BondageClub/Assets/Female3DCG/ItemNeck/ShinySteelCollar_Collar.png
  BondageClub/Assets/Female3DCG/ItemNeck/ShinySteelCollar_Ring.png
  BondageClub/Assets/Female3DCG/ItemNeck/SlaveCollarShinySteelCollar.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
Labels: asset

#2461 pet tape binding
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargeBottom.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargeComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargeExposedComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargeFull.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargePetTape.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_LargeTop.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalBottom.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalExposedComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalFull.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalPetTape.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_NormalTop.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallBottom.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallExposedComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallFull.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallPetTape.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_SmallTop.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargeBottom.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargeComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargeExposedComplete.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargeFull.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargePetTape.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/DuctTape_XLargeTop.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemArms/DuctTape/PetTape.png
Labels: asset

#2477 Refactor/Bugfix: Password lock refactors & UI improvements
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Inventory.js
Labels: change, fix, refactor

#2483 Variable Suspension Height
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/HempRope_Suspension.png
  BondageClub/CSS/Styles.css
  BondageClub/Icons/Player.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRopeSuspensionHogtied.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/SuspensionHogtied.png
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/index.html
Labels: feature

#2498 JSDoc fixes
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Title/Title.js
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Room/InfiltrationPerks/InfiltrationPerks.js
  BondageClub/Screens/Room/MovieStudio/MovieStudio.js
  BondageClub/Screens/Room/Pandora/Pandora.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Animation.js
  BondageClub/Scripts/GameLog.js
  BondageClub/Scripts/MiniGame.js
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Translation.js
Labels: fix

#2497 ribbons for the torso and lips.
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/Ribbons.png
  BondageClub/Assets/Female3DCG/ItemMouth/Ribbons.png
  BondageClub/Assets/Female3DCG/ItemMouth/RibbonsBow.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_LargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_LargeHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_NormalHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_NormalHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_SmallHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_SmallHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_XLargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/AllFours/Ribbons_XLargeHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_LargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_LargeHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_NormalHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_NormalHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_SmallHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_SmallHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_XLargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/Ribbons_XLargeHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/Ribbons.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_LargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_LargeHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_NormalHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_NormalHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_SmallHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_SmallHarness2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_XLargeHarness1.png
  BondageClub/Assets/Female3DCG/ItemTorso/Ribbons_XLargeHarness2.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/Ribbons/Basic.png
  BondageClub/Screens/Inventory/ItemMouth/Ribbons/Bow.png
  BondageClub/Screens/Inventory/ItemTorso/Ribbons/Basic.png
  BondageClub/Screens/Inventory/ItemTorso/Ribbons/Harness1.png
  BondageClub/Screens/Inventory/ItemTorso/Ribbons/Harness2.png
  BondageClub/Screens/Inventory/ItemTorso/Ribbons/Ribbons.js
  BondageClub/index.html
Labels: asset

#2428 Kinky Dungeon 1.4
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/index.html
Labels: feature, on-hold

#2499 New asset: Dental gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGagClosed_Gag.png
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGagClosed_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGagClosed_Mouth.png
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGag_Gag.png
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/DentalGag_Mouth.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/DentalGag.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/DentalGag/Closed.png
  BondageClub/Screens/Inventory/ItemMouth/DentalGag/Open.png
Labels: asset

#2508 Asset: Ceiling & Floor shackles update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_LargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_NormalOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_SmallOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/FloorShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_XLarge_Cuffs.png
Labels: asset

#2507 Preview Fixes
  BondageClub/Assets/Female3DCG/ItemArms/Preview/FullBodyShackles.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/MermaidSuit.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/AnkleShackles.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/Snorkel.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/MermaidTail.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/SeamlessLegBinder.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/PantiesMask.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/ShoeGag.png
  BondageClub/Assets/Female3DCG/ItemVulva/Preview/BenWaBalls.png
  BondageClub/Assets/Female3DCG/ItemVulva/Preview/ShockDildo.png
  BondageClub/Assets/Female3DCG/ItemVulva/Preview/VibratingLatexPanties.png
Labels: fix

#2506 Futuristic Mittens Fuzz Fix
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/FuturisticMittens_Body.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/FuturisticMittens_Body.png
  BondageClub/Assets/Female3DCG/ItemHands/FuturisticMittens_Body.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/FuturisticMittens_Body.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/FuturisticMittens_Body.png
Labels: asset, fix

#2502 Fix: Comfy top missing asset
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/ComfyTop_XLarge.png
Labels: fix

#2504 Fix: Many small fixes & documentation
  BondageClub/.eslintrc.json
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Animation.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/DynamicDraw.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/MiniGame.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Text.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
  BondageClub/Scripts/VibratorMode.js
  BondageClub/Tools/Node/package.json
  BondageClub/jsconfig.json
Labels: fix

#2512 More stepping activities
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
Labels: feature

#2510 Feature: Archetyped item validation improvements
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature, improvement
