Repository Ben987/Bondage-College, pull requests merged in 2021-01, with the labels that each got.

#1841 Kicked in Chatroom Subscreen Fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Server.js
Labels: fix

#1795 Transport Box
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/TransportWoodenBox.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Box.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Wheelholders.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Wheels.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, has-dependencies

#1842 Bugfix: Vibrator mode fixes
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/VibratorMode.js
Labels: fix

#1843 Headphones/Leather Hood Multicolor
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemEars/Headphones_Dark.png
  BondageClub/Assets/Female3DCG/ItemEars/Headphones_Light.png
  BondageClub/Assets/Female3DCG/ItemEars/Preview/Headphones.png
  BondageClub/Assets/Female3DCG/ItemHood/LeatherHood_Collar.png
  BondageClub/Assets/Female3DCG/ItemHood/LeatherHood_Hood.png
  BondageClub/Assets/Female3DCG/ItemHood/LeatherHood_Snaps.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemEars/Headphones/Headphones.js
  BondageClub/Screens/Inventory/ItemEars/Headphones/Heavy.png
  BondageClub/Screens/Inventory/ItemEars/Headphones/Light.png
  BondageClub/Screens/Inventory/ItemEars/Headphones/Off.png
  BondageClub/index.html
Labels: asset

#1844 Height System Rework
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
Labels: feature, fix, refactor

#1845 Over-The-Head Pose fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix, has-dependencies

#1846 Upside-Down Perspective
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
Labels: feature, has-dependencies

#1847 Tails Visible when Hogtied
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: has-dependencies, improvement

#1850 Fixed Bug regarding the AllowActivityOn field
  BondageClub/Scripts/Dialog.js
Labels: fix

#1851 New Item: Ceiling Shackles
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/CeilingShackles.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/CeilingShackles/CeilingShackles.js
  BondageClub/Screens/Inventory/ItemArms/CeilingShackles/HeadLevel.png
  BondageClub/Screens/Inventory/ItemArms/CeilingShackles/Overhead.png
  BondageClub/index.html
Labels: asset

#1854 Bugfix: Fixes some font issues
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Scripts/Common.js
Labels: fix

#1855 Bugfix: Minor asset definition fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1853 Improvement: Expression coloring from the expression menu
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Icons/WinkBoth.png
  BondageClub/Icons/WinkL.png
  BondageClub/Icons/WinkNone.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: change, improvement

#1856 Fix softlock when disconnected during login
  BondageClub/Scripts/Server.js
Labels: fix

#1857 Flippers
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Small.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_XLarge.png
  BondageClub/Assets/Female3DCG/Shoes/Preview/Flippers.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Small.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_XLarge.png
Labels: asset

#1858 Photography NPC Pose fix
  BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
Labels: fix

#1860 New Item: Vac-Cube
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/VacCube.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_Highlights.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_Large_Latex.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_Normal_Latex.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_Small_Latex.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_XLarge_Latex.png
Labels: asset

#1861 Feature: Custom text on the canvas hood
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/CanvasHood_Hood.png
  BondageClub/Assets/Female3DCG/ItemHood/CanvasHood_Text.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CSS/Styles.css
  BondageClub/Fonts/Saira Stencil One/OFL.txt
  BondageClub/Fonts/Saira Stencil One/SairaStencilOne-Regular.ttf
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/CanvasHood/CanvasHood.js
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
  BondageClub/index.html
Labels: asset

#1862 Feature: Adds new alternative light & dark chatroom themes
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: feature

#1863 Buttplug Tail Colour Splits
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemButt/FoxTails.png
  BondageClub/Assets/Female3DCG/ItemButt/FoxTails_Bases.png
  BondageClub/Assets/Female3DCG/ItemButt/FoxTails_Tips.png
  BondageClub/Assets/Female3DCG/ItemButt/TailButtPlug.png
  BondageClub/Assets/Female3DCG/ItemButt/TailButtPlug_Bell.png
  BondageClub/Assets/Female3DCG/ItemButt/TailButtPlug_Ribbon.png
  BondageClub/Assets/Female3DCG/ItemButt/TailButtPlug_Tail.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, improvement

#1864 Stable Exam End Fix
  BondageClub/Screens/Room/Stable/Stable.js
Labels: fix

#1865 Height Rework Fixes
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
Labels: fix

#1866 Water Cell improvement
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Room/Magic/Magic.js
Labels: improvement

#1867 Missing devices toy text
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#1824 Updates the changelog for R64
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#1868 Suspension Hogtie Tails Visible
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: improvement

#1869 R64 Changelog updates
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#1870 Beta Fix: Vac-Cube fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/VacCube_Highlights.png
Labels: beta-fix

#1871 Beta Fix: Fix for extended gags not gagging
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemMouth/BallGag/BallGag.js
  BondageClub/Screens/Inventory/ItemMouth/WiffleGag/WiffleGag.js
Labels: beta-fix

#1872 Beta Fix: Fixes broken extended item menu for the clothing latex corset
  BondageClub/Screens/Inventory/Bra/LatexCorset1/LatexCorset1.js
  BondageClub/Screens/Inventory/Corset/LatexCorset1/Garter.png
  BondageClub/Screens/Inventory/Corset/LatexCorset1/LatexCorset1.js
  BondageClub/Screens/Inventory/Corset/LatexCorset1/NoGarter.png
  BondageClub/index.html
Labels: beta-fix

#1874 Fixes LastChatRoom being forced on hardcore players
  BondageClub/Screens/Character/Preference/Preference.js
Labels: beta-fix

#1875 Fix for only the last chat room appearing in the chat search on exit
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1876 Extended ball gag chat message fix
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#1877 Fixes player being trapped on relog if the room they rejoin is full
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix

#1878 All Fours Tails fixups
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2Base.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2_2in.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2_3in.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2_4in.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalBeads2_5in.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalHook.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalHookChain.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/AnalHookHair.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/FoxTail1_Base.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/FoxTail1_Tip.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/FoxTail2_Base.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/FoxTail2_Tip.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/FoxTails.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/PuppyTailPlug1.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/RaccoonButtPlug.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/RaccoonTailPlug.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/SuccubusHeartButtPlug_Heart.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/SuccubusHeartButtPlug_Tail.png
  BondageClub/Assets/Female3DCG/ItemButt/AllFours/WolfTail1.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailStrap1_Base.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailStrap1_Tip.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailStrap2_Base.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailStrap2_Tip.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailsStrap_Bases.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/FoxTailsStrap_Tips.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/KittenTailStrap1.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/MouseTailStrap1.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/MouseTailStrap2.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/RaccoonTailStrap.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/SuccubusHeartTailStrap_Heart.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/SuccubusHeartTailStrap_Tail.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/TailStrap.png
  BondageClub/Assets/Female3DCG/TailStraps/AllFours/WolfTailStrap1.png
Labels: beta-fix

#1879 Hands Missing Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/CommonDraw.js
Labels: beta-fix

#1880 Futuristic Full Harness
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackBoxTie/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackCuffs/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/BackElbowTouch/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/TapedHands/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Yoked/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1881 Ceiling Chains fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#1882 Bugfix: Expression reset button now resets expression colors as well (where applicable)
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#1883 DrawCharacter on iOS fix
  BondageClub/Scripts/Drawing.js
Labels: beta-fix

#1884 Background
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/OutsideCells.jpg
  BondageClub/Backgrounds/OutsideCellsDark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#1886 Beta Improvement: Adds AllowActivityOn to the Vac-Cube
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, beta-fix, improvement

#1887 Auto-Remake rooms now remakes private, adding player as admin
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix, improvement

#1889 Fix: Ceiling Shackles: Make the chain longer
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/CeilingShackles_XLarge_Chain.png
Labels: beta-fix

#1891 Improved Flippers Coloring
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Large_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Large_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Normal_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Small_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_Small_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_XLarge_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Flippers_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Large_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Large_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Normal_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Small_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_Small_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_XLarge_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Hogtied/Flippers_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Large_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Large_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Normal_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Small_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_Small_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_XLarge_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Kneel/Flippers_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Large_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Large_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Normal_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Small_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_Small_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_XLarge_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/Flippers_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Large_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Large_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Normal_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Small_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_Small_Shoes.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_XLarge_Fins.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/Flippers_XLarge_Shoes.png
Labels: asset, improvement

#1892 Spread Legs Boot fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1894 Kicked Room Rejoin fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix

#1897 Beta fix: Pose fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/LeatherAnkleCuffs/LeatherAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/OrnateAnkleCuffs/OrnateAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/LeatherLegCuffs/LeatherLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/OrnateLegCuffs/OrnateLegCuffs.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#1873 Changelog: R64 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#1898 Feature/Beta Fix: Adds a "reset to default" button to the color picker
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix, feature

#1900 Blocked OOC Gagged Workaround Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1901 Beta fix: Vanishing lover/owner locks
  BondageClub/Scripts/Server.js
Labels: beta-fix

#1902 Preview pic for full futuristic harness
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/FuturisticHarness2.png
Labels: beta-fix

#1905 Beta Fix: Slave Collar
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Labels: beta-fix

#1907 Bugfix: Allows timer locks to trigger chatroom messages in other chatroom subscreens
  BondageClub/Scripts/Timer.js
Labels: beta-fix

#1912 Suspension Pose fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1917 Confirmation dialog for calling maids to leave the room
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#1919 Bugfix: Ensures an item update when the full lockdown suit's wand gets added
  BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
Labels: beta-fix

#1920 Bugfix: Removes an unneeded console.log call
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: beta-fix

#1921 College Entrance Uniform Colour fix
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
Labels: beta-fix

#1924 Bugfix: Prevents the bed spread eagle hemp rope type from ignoring toe ties
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
Labels: beta-fix

#1927 Pilot suit fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#1930 Fixed return to chatroom allowing people to create non-asylum rooms
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix

#1929 Changelog Update: R64 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#1933 Hotfix: Correct a naming error on the ceiling cuffs layers
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, fix

#1934 Bugfix: Fix for chess square overflow in Firefox
  BondageClub/CSS/Chess.css
  BondageClub/index.html
Labels: fix

#1937 Bugfix: Removes the medical restraints from the random pool
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1938 Bugfix: Fixes the layer names for the Futuristic arm cuffs
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: fix

#1939 Bugfix: Fixes posture collar name orderings
  BondageClub/Assets/Female3DCG/Female3DCG.csv
Labels: fix

#1942 Bugfix: Fixes alpha mask issues with the open straitdress
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1944 Chains Feet LegsClosed fix
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
Labels: fix

#1941 Fix: Extended item removal while viewing
  BondageClub/Scripts/Character.js
Labels: fix

#1946 Bugfix: Adds the Corset group to the Hide array for several items
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1950 Bugfix: Adds a missing AllowBlock entry to the Pet Suit
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1948 Improvement: Adds retry logic to CommonGet
  BondageClub/Scripts/Common.js
Labels: improvement

#1947 Hollow butt plug
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemButt/Preview/HollowButtPlug.png
Labels: asset

#1945 Chatroom Cut-off Name
  BondageClub/Scripts/Drawing.js
Labels: improvement

#1943 Tweaked tail heights
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, improvement

#1940 Vacbed + Flippers edit
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_Large.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_LargeNohair.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_Normal.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_NormalNohair.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_Small.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_SmallNohair.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_XLarge.png
  BondageClub/Assets/Female3DCG/ItemDevices/Vacbed_XLargeNohair.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Vacbed/Nohair.png
  BondageClub/Screens/Inventory/ItemDevices/Vacbed/Normal.png
  BondageClub/Screens/Inventory/ItemDevices/Vacbed/Vacbed.js
  BondageClub/index.html
Labels: asset, change

#1932 Feature: New Backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/Desert.jpg
  BondageClub/Backgrounds/DesertDark.jpg
  BondageClub/Backgrounds/OutdoorPool2.jpg
  BondageClub/Backgrounds/OutdoorPool2Dark.jpg
  BondageClub/Backgrounds/Ranch.jpg
  BondageClub/Backgrounds/RanchDark.jpg
  BondageClub/Backgrounds/Wagons.jpg
  BondageClub/Backgrounds/WagonsDark.jpg
  BondageClub/Backgrounds/WesternStreet.jpg
  BondageClub/Backgrounds/WesternStreetDark.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#1928 Extended Item Self-Blocking Validation
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
  BondageClub/Scripts/ExtendedItem.js
Labels: fix, refactor

#1926 Fix: Raise wooden sign priority
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#1952 Bugfix: Fixes some medium collar chain asset artefacts & missing locks
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarChainMedium_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarChainMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarChainMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarChainMedium_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarChainMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarChainMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarChainMedium_Lock.png
Labels: asset, fix

#1955 Dev feature: Asset check script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Tools/Node/AssetCheck.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/Tools/Node/package-lock.json
  BondageClub/Tools/Node/package.json
Labels: feature

#1953 Improvement: Simple chatroom optimisations
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement, refactor

#1935 Fix: Aligns the Up-Button with the left hand side ones
  BondageClub/Scripts/Dialog.js
Labels: improvement

#1925 Timer Password Padlock
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/TimerPasswordPadlock.png
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Timer.js
  BondageClub/index.html
Labels: asset, feature

#1918 Refactor: Full latex lockdown suit wand
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/FullLatexSuitWand/FullLatexSuitWand.js
Labels: asset, improvement

#1916 Refactor: Vibrating butt plug to extended vibrator
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemButt/VibratingButtplug/VibratingButtplug.js
Labels: asset, improvement

#1915 Refactor: Egg Plug XXL to extended vibrator
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemButt/EggVibePlugXXL/EggVibePlugXXL.js
Labels: asset, improvement

#1913 Refactor: Vibrating panties to extended vibrator
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/VibratingLatexPanties/VibratingLatexPanties.js
Labels: asset, improvement

#1911 Refactor: Wired egg to extended vibrator script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/WiredEgg/WiredEgg.js
Labels: asset, improvement

#1910 Refactor: Vulva vibrating egg to extended vibe
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/VibratingEgg/VibratingEgg.js
Labels: asset, improvement

#1909 Refactor: Wand belt to extended vibrator script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/WandBelt/WandBelt.js
Labels: asset, improvement

#1908 Refactor: Wand Rope belt to extended vibe
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/HempRopeBelt/HempRopeBelt.js
Labels: asset, improvement

#1903 Refactor: Clitoral stimulator to extended vibe mode
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/ClitoralStimulator/ClitoralStimulator.js
Labels: asset, improvement

#1959 Bugfix: Prevents non-owners/lovers from adding owner/lover locks
  BondageClub/Scripts/Server.js
Labels: fix

#1957 Bugfix: Adjusts the yoked lock asset for the Futuristic Arm Cuffs
  BondageClub/Assets/Female3DCG/ItemArms/Yoked/FuturisticCuffs_Lock.png
Labels: asset, fix

#1899 Ceiling Ropes and Chains
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemAddon/CeilingChain.png
  BondageClub/Assets/Female3DCG/ItemAddon/CeilingRope.png
  BondageClub/Assets/Female3DCG/ItemAddon/Preview/CeilingChain.png
  BondageClub/Assets/Female3DCG/ItemAddon/Preview/CeilingRope.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/CeilingChain.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/Lowered.png
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/Suspended.png
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/CeilingRope.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/Lowered.png
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/Suspended.png
  BondageClub/Scripts/Inventory.js
  BondageClub/index.html
Labels: asset

#1893 Default Colors for collars
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, improvement

#1890 Futuristic Collar now allows player to block remotes on wearer
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Scripts/Dialog.js
Labels: asset, feature

#1931 Feature: Item Opacity/Wooden Box enhancements
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenBox.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenBox_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenBox_Panel.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/StuddedBlindfold.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: asset, feature

#1923 Default Colour Check
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
Labels: refactor

#1922 Strait Bunny Leotard
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Large_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Large_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Large_Upper.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Normal_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Normal_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Normal_Upper.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Small_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Small_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Small_Upper.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_XLarge_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_XLarge_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_XLarge_Upper.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, improvement

#1904 Notifications
  BondageClub/Icons/Immersion.png
  BondageClub/Icons/Notifications.png
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Server.js
Labels: feature

#1675 Feature: Ability to pick locks
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/HighSecurityPadlock.png
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/HighSecurityPadlockKey.png
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/Lockpicks.png
  BondageClub/Icons/LockCancel.png
  BondageClub/Icons/LockMenu.png
  BondageClub/Icons/PickLock.png
  BondageClub/Icons/PickLockJammed.png
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
  BondageClub/Screens/Inventory/ItemArms/LeatherCuffs/LeatherCuffs.js
  BondageClub/Screens/Inventory/ItemArms/OrnateCuffs/OrnateCuffs.js
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/MiniGame/Lockpick/Arrow.png
  BondageClub/Screens/MiniGame/Lockpick/Cylinder.png
  BondageClub/Screens/MiniGame/Lockpick/Pin.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: feature

#1966 Bugfix: Fixes for hidden chat message handling
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#1965 Fix crash when swapping items
  BondageClub/Scripts/Dialog.js
Labels: fix

#1962 Github action: Asset check
  .github/workflows/assetCheck.yml
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature

#1896 Extreme Difficulty - Locks accessible to Whitelist
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: improvement

#1969 Bugfix: Adds type definitions for the new asset properties
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: fix

#1968 New item: Floor Shackles
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/FloorShackles.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/FloorShackles_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#1972 InventoryGroupIsBlocked(C, null, true)
  BondageClub/Scripts/Dialog.js
Labels: fix

#1970 Appearance Dynamic Menu Buttons
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
Labels: refactor

#1967 Longer messages & bio (with bio compression)
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
  BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile.csv
  BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_DE.txt
  BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_FR.txt
  BondageClub/Screens/Character/OnlineProfile/Text_OnlineProfile_RU.txt
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
Labels: feature

#1964 Lock Picking RNG tweaks and UI changes
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: improvement

#1960 10 new handhelds
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/ShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBaguette.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBallgag.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLongSock.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPanties.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilLong.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilShort.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTapeRoll.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTowel.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysVibeRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToyBallgag.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysBaguette.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysBallgag.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysLongSock.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPanties.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysRopeCoilLong.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysRopeCoilShort.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysTapeRoll.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysTowel.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysVibeRemote.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Baguette.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Ballgag.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/LongSock.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Panties.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/RopeCoilLong.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/RopeCoilShort.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/ShockRemote.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/TapeRoll.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Towel.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/VibeRemote.png
  BondageClub/Screens/Room/Sarah/Sarah.js
Labels: asset

#1954 New Item: Halo
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairAccessory3/HaloBroken_Base.png
  BondageClub/Assets/Female3DCG/HairAccessory3/HaloBroken_Core.png
  BondageClub/Assets/Female3DCG/HairAccessory3/HaloBroken_Glow.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Halo_Base.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Halo_Core.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Halo_Glow.png
  BondageClub/Assets/Female3DCG/HairAccessory3/Preview/Halo.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CSS/Styles.css
  BondageClub/Icons/Lightbulb.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/HairAccessory1/Halo/Halo.js
  BondageClub/Screens/Inventory/HairAccessory3/Halo/Broken.png
  BondageClub/Screens/Inventory/HairAccessory3/Halo/Default.png
  BondageClub/Screens/Inventory/HairAccessory3/Halo/Halo.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/VibratorMode.js
  BondageClub/index.html
Labels: asset

#1958 Improve (re)login and ForceDisconnect handling
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Login/Text_Login.csv
  BondageClub/Screens/Character/PasswordReset/PasswordReset.js
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Character/Relog/Text_Relog.csv
  BondageClub/Scripts/Server.js
Labels: improvement

#1977 Bugfix: Infinite Replication of SpankingToys
  BondageClub/Scripts/Dialog.js
Labels: fix

#1976 New item pose: Ceiling shackles - allow suspension
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShacklesOverhead_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_LargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_LargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_NormalOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_NormalOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_SmallOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_SmallOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/CeilingShackles_XLargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShacklesOverhead_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_LargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_LargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_NormalOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_NormalOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_SmallOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_SmallOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_XLargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_XLargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/Suspension/CeilingShackles_XLarge_Cuffs.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/CeilingShackles/CeilingShackles.js
Labels: asset, improvement

#1975 Bugfix: Adds more items to the RemoveItemOnRemove entry for the bed
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#1974 Bed Rope access fix
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
Labels: fix

#1973 Clothes Group Colour Button
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
Labels: improvement

#1914 Refactor: Bunny tail vibe to extended vibrator
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemButt/BunnyTailVibePlug/BunnyTailVibePlug.js
Labels: asset, improvement

#1835 Controller Support
  BondageClub/Icons/Controller.png
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ControllerSupport.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Timer.js
  BondageClub/index.html
Labels: feature

#1978 New item: Pet bed
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/PetBed.png
Labels: asset

#1980 Persistent Lock Picking
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: change, feature

#1986 Intro text on intricate padlock
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset, improvement

#1983 Over panties crotch rope now doesn't visually sink into the panties
  BondageClub/Assets/Female3DCG/ItemPelvis/HempRope_LargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/HempRope_NormalOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/HempRope_SmallOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/HempRope_XLargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Horse/HempRope_LargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Horse/HempRope_NormalOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Horse/HempRope_SmallOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Horse/HempRope_XLargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Kneel/HempRope_LargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Kneel/HempRope_NormalOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Kneel/HempRope_SmallOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Kneel/HempRope_XLargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/KneelingSpread/HempRope_LargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/KneelingSpread/HempRope_NormalOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/KneelingSpread/HempRope_SmallOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/KneelingSpread/HempRope_XLargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/LegsClosed/HempRope_LargeOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/LegsClosed/HempRope_NormalOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/LegsClosed/HempRope_SmallOverPanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/LegsClosed/HempRope_XLargeOverPanties.png
Labels: asset, change

#1987 More responsive vibrator visual effects
  BondageClub/Scripts/Timer.js
Labels: improvement

#1989 Refactor: DrawAssetPreview
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/VibratorMode.js
Labels: improvement, refactor

#1985 Messages when plugged or vibrated
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemPelvis/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemTorso/HempRopeHarness/HempRopeHarness.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
Labels: feature

#1988 Lock picking fixes
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: fix

#1999 Bugfix: Fixes double clicks on the appearance screen
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#1998 Item Permissions on Blocked Zones
  BondageClub/Scripts/Dialog.js
Labels: improvement

#1996 Dress Reset Icons
  BondageClub/Icons/DressReset.png
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
  BondageClub/Screens/Room/Gambling/Gambling.js
  BondageClub/Screens/Room/Shibari/Shibari.js
Labels: improvement

#1992 Feature: Adds kneeling support to the wooden box
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/WoodenBox_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/WoodenBox_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/WoodenBox_Panel.png
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
Labels: asset, improvement

#1994 Blocked or Limited Checks refactor
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/OldGasMask.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
Labels: refactor

#1997 Screen flash on plug/vibe events
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2000 Fix error on startup due to arousal messages
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2005 Bugfix: Fixes a click handler ordering issue in the appearance menu
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#2006 small fix for controller
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Timer.js
Labels: fix

#2007 Height Function Fix
  BondageClub/Scripts/Dialog.js
Labels: fix

#2008 New item: Pet Bowl
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/PetBowl_Bowl.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/PetBowl.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/PetBowl/PetBowl.js
  BondageClub/index.html
Labels: asset

#2009 Assets: Adds copies of pantyhose and stockings to SuitLower
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Large_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Normal_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Small_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_XLarge_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/PilotSuit_Large_Layer4.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/PilotSuit_Normal_Layer4.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/PilotSuit_Small_Layer4.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/PilotSuit_XLarge_Layer4.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/ReverseBunnySuit_Large.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/ReverseBunnySuit_Normal.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/ReverseBunnySuit_Small.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/ReverseBunnySuit_XLarge.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeamlessCatsuit_Large.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeamlessCatsuit_Normal.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeamlessCatsuit_Small.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeamlessCatsuit_XLarge.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Large_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Normal_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Small_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_XLarge_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuit_Large.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuit_Normal.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuit_Small.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuit_XLarge.png
  BondageClub/Scripts/CommonDraw.js
Labels: asset, change

#2004 Refactor: Preview images part 2
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCG_FR.txt
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/HairAccessory3/Halo/Halo.js
  BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
  BondageClub/Screens/Inventory/ItemArms/HighSecurityStraitJacket/HighSecurityStraitJacket.js
  BondageClub/Screens/Inventory/ItemArms/PrisonLockdownSuit/PrisonLockdownSuit.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
  BondageClub/Screens/Inventory/ItemButt/AnalBeads2/AnalBeads2.js
  BondageClub/Screens/Inventory/ItemButt/ButtPlugLock/ButtPlugLock.js
  BondageClub/Screens/Inventory/ItemButt/InflVibeButtPlug/InflVibeButtPlug.js
  BondageClub/Screens/Inventory/ItemDevices/Sybian/Sybian.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Screens/Inventory/ItemFeet/SpreaderVibratingDildoBar/SpreaderVibratingDildoBar.js
  BondageClub/Screens/Inventory/ItemHands/PaddedMittens/PaddedMittens.js
  BondageClub/Screens/Inventory/ItemHands/PawMittens/PawMittens.js
  BondageClub/Screens/Inventory/ItemHood/CanvasHood/CanvasHood.js
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/OldGasMask.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/LeatherLegCuffs/LeatherLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/OrnateLegCuffs/OrnateLegCuffs.js
  BondageClub/Screens/Inventory/ItemMisc/CombinationPadlock/CombinationPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/ExclusivePadlock/ExclusivePadlock.js
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/IntricatePadlock/IntricatePadlock.js
  BondageClub/Screens/Inventory/ItemMisc/LoversPadlock/LoversPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/LoversTimerPadlock/LoversTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MetalPadlock/MetalPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MistressPadlock/MistressPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MistressTimerPadlock/MistressTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/OwnerPadlock/OwnerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPadlock/TimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTag/CollarNameTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLivestock/CollarNameTagLivestock.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLover/CollarNameTagLover.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagOval/CollarNameTagOval.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagPet/CollarNameTagPet.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/LoveChastityBelt/LoveChastityBelt.js
  BondageClub/Screens/Inventory/ItemVulva/ClitAndDildoVibratorbelt/ClitAndDildoVibratorbelt.js
  BondageClub/Screens/Inventory/ItemVulva/InflatableVibeDildo/InflatableVibeDildo.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Mouse.js
Labels: asset, improvement, refactor

#1979 Appearance Group button scrolling
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2010 Bugfix: Rebuilds appearance inventory when selecting an item
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix
