Repository Ben987/Bondage-College, pull requests merged in 2021-12, with the labels that each got.

#3110 Bugfix: `ActivityCheckPrerequisite` logic fixes
  BondageClub/Scripts/Activity.js
Labels: fix

#3111 Feature: `ZoneAccessible` prerequisite expansion
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Asset.js
Labels: change

#3028 Spelling Fixes and Standardizations
  Actor.js
  BondageClub/CHANGELOG.md
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Drawing3D.js
  BondageClub/Scripts/DynamicDraw.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/changelog.html
  C002_FirstClass/Amanda/Stage_EN.csv
  C002_FirstClass/Outro/Script.js
  C002_FirstClass/Sarah/Intro_EN.csv
  C002_FirstClass/Sidney/Stage_EN.csv
  C005_GymClass/Jennifer/Stage_EN.csv
  C006_Isolation/IsolationRoom/Script.js
  C007_LunchBreak/Amanda/Script.js
  C007_LunchBreak/Jennifer/Stage_EN.csv
  C007_LunchBreak/Jennifer/Text_EN.csv
  C007_LunchBreak/Sarah/Script.js
  C008_DramaClass/AmandaIntro/Intro_EN.csv
  C008_DramaClass/AmandaIntro/Text_EN.csv
  C008_DramaClass/Damsel/Stage_EN.csv
  C008_DramaClass/SarahIntro/Text_EN.csv
  C009_Library/Jennifer/Stage_EN.csv
  C009_Library/Jennifer/Text_EN.csv
  C009_Library/Yuki/Stage_EN.csv
  C011_LiteratureClass/Mildred/Text_EN.csv
  C011_LiteratureClass/SelectDesk/Stage_EN.csv
  C012_AfterClass/Amanda/Script.js
  C012_AfterClass/Amanda/Stage_EN.csv
  C012_AfterClass/Amanda/Text_EN.csv
  C012_AfterClass/Jennifer/Stage_EN.csv
  C012_AfterClass/Jennifer/Text_EN.csv
  C012_AfterClass/Roommates/Stage_EN.csv
  C012_AfterClass/Sarah/Intro_EN.csv
  C012_AfterClass/Sarah/Script.js
  C012_AfterClass/Sarah/Stage_EN.csv
  C012_AfterClass/Sarah/Text_EN.csv
  C012_AfterClass/Sidney/Script.js
  C012_AfterClass/Sidney/Stage_EN.csv
  C012_AfterClass/Sidney/Text_EN.csv
  C101_KinbakuClub/Erica/Intro_EN.csv
  C101_KinbakuClub/RopeGroup/Script.js
  C101_KinbakuClub/RopeGroup/Stage_DE.csv
  C101_KinbakuClub/RopeGroup/Stage_EN.csv
  C101_KinbakuClub/RopeGroup/Text_DE.csv
  C101_KinbakuClub/RopeGroup/Text_EN.csv
  C999_Common/Cuffs/Stage_EN.csv
  C999_Common/Player/Script.js
  C999_Common/Quiz/Questions/MonteCristoChapter2_EN.csv
Labels: fix, change

#3115 Bugfix: Button click logic for the Password Padlock
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
Labels: fix

#3114 fix - nursery dead end and diaper check
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
  BondageClub/Screens/Room/Nursery/Nursery.js
Labels: fix, change

#3113 Fix crashes when interacting with Love Chastity Belt
  BondageClub/Screens/Inventory/ItemPelvis/LoveChastityBelt/LoveChastityBelt.js
Labels: fix

#3112 Code cleanup
  BondageClub/.editorconfig
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Inventory/ItemMisc/LoversTimerPadlock/LoversTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MistressTimerPadlock/MistressTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Speech.js
Labels: refactor

#3117 Scarf
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/Scarf.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Scarf.png
  BondageClub/Assets/Female3DCG/ClothAccessory/ScarfBundled.png
  BondageClub/Assets/Female3DCG/ClothAccessory/ScarfHideMouth.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#3118 Fixed crash when spectating kinky dungeon
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
Labels: fix

#3121 [Asset] [Natsuki]: Plastic Wrap Roll
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPlasticWrap.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/PlasticWrap.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#3123 Chat Room Filter - Text limit increase
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Element.js
Labels: beta-fix

#3122 Changelog: R75 Beta 1 changelog corrections
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#3124 Beta Fix: Missing Futuristic Training Belt chat messages
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Scripts/Audio.js
Labels: beta-fix

#3125 Beta Fix: Snowman difficulty tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3128 Thin Leather Strap Difficulty Update
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: change

#3132 Latex Boxtie Armbinder, Armbinder Jacket, Bolero Straightjacket alpha fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#3134 Admiral Shirt Fix
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/AdmiralTop_Small_Shirt.png
Labels: fix

#3135 Changelog: R75 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#3137 Fix conflicting pose issue between the HempRope & FrogtieStrap
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3138 [Beta fix] [asset] [Natsuki] Plastic roll update
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPlasticWrap.png
Labels: beta-fix

#3140 Beta-fix: Allow `BlindHeavy` effect for `SmallLocker`
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3141 Allow KneelingSpread pose on the ItemNeckRestraints
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix, asset

#3146 Bugfix: "behind you back" typo
  BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Patient.csv
  BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Patient_DE.txt
  BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Patient_RU.txt
Labels: fix

#3145 Bugfix: Removes legs from the `KneelingSpread` pose for `Stockings1`
  BondageClub/Assets/Female3DCG/Socks/KneelingSpread/Stockings1_Large.png
Labels: fix, asset

#3144 Erase stray pixel from the scarf
  BondageClub/Assets/Female3DCG/ClothAccessory/Scarf.png
  BondageClub/Assets/Female3DCG/ClothAccessory/ScarfBundled.png
  BondageClub/Assets/Female3DCG/ClothAccessory/ScarfHideMouth.png
Labels: fix, asset

#3126 Medical Bed
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/MedicalBed_BedFrame.png
  BondageClub/Assets/Female3DCG/ItemDevices/MedicalBed_Mattress.png
  BondageClub/Assets/Female3DCG/ItemDevices/MedicalBed_Pillow.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/MedicalBed.png
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
Labels: asset

#3127 Heart-Link Choker Asset Update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/HeartLinkChoker_HeartLink.png
  BondageClub/Assets/Female3DCG/ItemNeck/HeartLinkChoker_LeatherStrap.png
  BondageClub/Assets/Female3DCG/ItemNeck/SlaveCollarHeartLinkChoker.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#3136 College Skirt Split
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Preview/CollegeOutfit1.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/CollegeOutfit1_Large_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/CollegeOutfit1_Normal_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/CollegeOutfit1_Small_Skirt.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/CollegeOutfit1_XLarge_Skirt.png
  BondageClub/Assets/Female3DCG/ClothLower/CollegeSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/CollegeSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/CollegeSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/CollegeSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/CollegeSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/CollegeSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/CollegeSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/CollegeSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/CollegeSkirt.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/CollegeCafeteria/CollegeCafeteria.js
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
  BondageClub/Screens/Room/Nursery/Nursery.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Scripts/Import.js
Labels: asset, change

#3129 Better identification of players in the Suitcase's Outgoing messages
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
  BondageClub/Scripts/Typedef.d.ts
Labels: change

#3159 Ziptie Message Fix
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#3161 Cleanup nullchecks
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/Game/OnlineGame.js
  BondageClub/Screens/Room/AsylumGGTS/AsylumGGTS.js
  BondageClub/Screens/Room/Infiltration/Infiltration.js
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Screens/Room/Pandora/Pandora.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Speech.js
Labels: refactor

#3162 Leg Spreader Prerequisite Fix
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Inventory.js
Labels: fix

#3164 Missing Effect Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Character.js
Labels: fix

#3166 Empty FilterTerms Fix
  BondageClub/Screens/Character/Creation/Creation.js
Labels: fix
