Repository Ben987/Bondage-College, pull requests merged in 2021-04, with the labels that each got.

#2270 New Back Hairstyles
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack47.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack48.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack49.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack47.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack48.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack49.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack47.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack48.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack49.png
  BondageClub/Assets/Female3DCG/HairBack/Orig/HairBack47.png
  BondageClub/Assets/Female3DCG/HairBack/Orig/HairBack48.png
  BondageClub/Assets/Female3DCG/HairBack/Orig/HairBack49.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack47.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack48.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack49.png
Labels: asset

#2269 Padded Blindfold
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/PaddedBlindfold_Base.png
  BondageClub/Assets/Female3DCG/ItemHead/PaddedBlindfold_Lock.png
  BondageClub/Assets/Female3DCG/ItemHead/PaddedBlindfold_Trim.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/PaddedBlindfold.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2265 Feature: facial expressions can be saved/loaded
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
Labels: feature

#2263 Feature/Refactor: Extended Archetypes - typed items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/ItemArms/LatexBoxtieLeotard/LatexBoxtieLeotard.js
  BondageClub/Screens/Inventory/ItemArms/LatexButterflyLeotard/LatexButterflyLeotard.js
  BondageClub/Screens/Inventory/ItemArms/LatexSleevelessLeotard/LatexSleevelessLeotard.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Tools/Node/AssetCheck.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: feature, refactor

#2259 Feature: Display login queue position
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Login/Text_Login.csv
  BondageClub/Screens/Character/Relog/Text_Relog.csv
  BondageClub/Scripts/Server.js
Labels: feature, server

#2280 Cushion
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackBoxTie/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackBoxTie/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackCuffs/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackCuffs/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackElbowTouch/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/BackElbowTouch/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Horse/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/Horse/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/OverTheHead/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/TapedHands/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/TapedHands/CushionKneel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/Cushion.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/CushionKneel.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Cushion.js
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Hold.png
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Kneel.png
  BondageClub/index.html
Labels: asset

#2288 Bugfix: Missing lock assets for HarnessPanties2
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemPelvis/HarnessPanties2_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Horse/HarnessPanties2_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Kneel/HarnessPanties2_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/KneelingSpread/HarnessPanties2_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/LegsClosed/HarnessPanties2_Lock.png
Labels: asset, fix

#2287 Fix: exposed tape missing dialog
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2289 Feature: Adds support for the Wiggle activity to ItemNose and ItemEars
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
Labels: feature

#2272 ChatRoomSync-Split: Replacement functions only
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: refactor, server

#2274 ChatRoomSync-Split: Enable ChatRoomSyncMemberJoin
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2275 ChatRoomSync-Split: Enable ChatRoomSyncMemberLeave
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2292 Removed multiples of ChatRoomSync-Split functions
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2293 Custom backgrounds updates
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2294 Devious Dungeon 1.1
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Fireball.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/FireballHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/FocusedFlash.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/FocusedFlashHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/GreaterFlash.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/GreaterFlashHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Icebolt.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/IceboltHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Slime.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/SlimeHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: feature

#2301 Bugfix: Fixes for the Bunny Girl Accessories extended item menu
  BondageClub/Assets/Female3DCG/ClothAccessory/BunnyCollarCuffs/Both.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BunnyCollarCuffs/BunnyCollarCuffs.js
  BondageClub/Assets/Female3DCG/ClothAccessory/BunnyCollarCuffs/Collar.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BunnyCollarCuffs/Cuffs.png
  BondageClub/Screens/Inventory/ClothAccessory/BunnyCollarCuffs/BunnyCollarCuffs.js
Labels: beta-fix

#2302 Bugfix: Fixes casing for asset paths in the Kinky Dungeon minigame
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
Labels: beta-fix

#2304 Bugfix: Fixes incorrect appearance update rollbacks
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#2305 Custom Tag Regex Fix
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
Labels: fix

#2306 Sci-Fi Pleasure Panties Fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/SciFiPleasurePanties.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
Labels: beta-fix

#2307 Lock Timer Validation Fix
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#2310 Kidnap Dress Up Fix
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
Labels: beta-fix

#2300 Updates the changelog for R67 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2303 Fix `WhiteList` loading, add `BlackList` loading
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
Labels: beta-fix

#2313 Feature: Changelog R67 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2315 Kicked during Kinky Dungeon fix
  BondageClub/Scripts/Server.js
Labels: beta-fix

#2316 Urgent Pleasure Panties js update
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
Labels: beta-fix

#2317 Bugfix: Properly enables partial appearance rollbacks
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Server.js
Labels: beta-fix

#2318 Bugfix: Improves character clumsiness calculation
  BondageClub/Scripts/Character.js
Labels: beta-fix

#2320 Bugfix: Chatroom messages for the pet bed
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/PetBed/PetBed.js
Labels: beta-fix

#2322 Bugfix: Validation refinements
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#2319 Feature: Updates the changelog for beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2321 Rename sensory deprivation settings
  BondageClub/Screens/Character/Preference/Text_Preference.csv
Labels: change

#2336 Pleasure Panties Password Fail fix
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
Labels: beta-fix

#2335 Beta-fix: Remove Friendlist sorting
  BondageClub/Screens/Character/FriendList/FriendList.js
Labels: beta-fix

#2332 Bugfix: Ensures expression remove timers get removed when the expression is
  BondageClub/Scripts/Character.js
Labels: fix

#2330 Bugfix: Allows the null type to have properties
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#2329 Fix: bad parenthesis at MsgEnterLeave test
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2326 Bugfix: Additional validation fixes
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#2334 Feature: Updates changelog for R67
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2341 Bugfix: Lock validation fixes
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Timer.js
  BondageClub/Scripts/Validation.js
Labels: hotfix

#2340 Movie Studio Corset fix
  BondageClub/Screens/Room/MovieStudio/MovieStudio.js
Labels: fix

#2338 Bugfix: Changelog correction
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: hotfix

#2346 Fix: Crash during beep log rendering
  BondageClub/Screens/Character/FriendList/FriendList.js
Labels: hotfix

#2345 Bugfix: Fix for tongue strap gag lock asset colour
  BondageClub/Assets/Female3DCG/ItemMouth/TongueStrapGag_Lock.png
Labels: asset, fix

#2344 Added stepping sexual activity
  BondageClub/Assets/Female3DCG/Activity/Step.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
Labels: feature

#2337 Feature: Typed item archetype enhancements & Latex Corset refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ClothAccessory/BunnyCollarCuffs/BunnyCollarCuffs.js
  BondageClub/Screens/Inventory/Corset/LatexCorset1/LatexCorset1.js
  BondageClub/Screens/Inventory/Glasses/EyePatch1/EyePatch1.js
  BondageClub/Screens/Inventory/HairAccessory3/Halo/Halo.js
  BondageClub/Screens/Inventory/ItemArms/CollarCuffs/CollarCuffs.js
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
  BondageClub/Screens/Inventory/ItemButt/ButtPump/ButtPump.js
  BondageClub/Screens/Inventory/ItemHood/GwenHood/GwenHood.js
  BondageClub/Screens/Inventory/ItemHood/InflatedBallHood/InflatedBallHood.js
  BondageClub/Screens/Inventory/ItemMouth/CupholderGag/CupholderGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/PumpGag/PumpGag.js
  BondageClub/Screens/Inventory/ItemNipples/LactationPump/LactationPump.js
  BondageClub/Screens/Inventory/ItemNipples/NippleSuctionCups/NippleSuctionCups.js
  BondageClub/Screens/Inventory/ItemNipples/PlateClamps/PlateClamps.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemTorso/LatexCorset1/Garter.png
  BondageClub/Screens/Inventory/ItemTorso/LatexCorset1/LatexCorset1.js
  BondageClub/Screens/Inventory/ItemTorso/LatexCorset1/NoGarter.png
  BondageClub/Screens/Inventory/ItemVulva/ClitSuctionCup/ClitSuctionCup.js
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/NecklaceKey.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: improvement, refactor

#2333 Improvement: Automatically generates AllowEffect & AllowBlock for modular items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ModularItem.js
Labels: improvement

#2331 Kinky Dungeon Persistence
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
Labels: improvement

#2327 Asset: blanket hood
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/BlanketHood.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/BlanketHood.png
Labels: asset

#2325 Extended Bunny Mask 1
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Mask/BunnyMask1.png
  BondageClub/Assets/Female3DCG/Mask/BunnyMask1_Base.png
  BondageClub/Assets/Female3DCG/Mask/BunnyMask1_Ears.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Mask/BunnyMask1/BunnyMask1.js
  BondageClub/Screens/Inventory/Mask/BunnyMask1/Earless.png
  BondageClub/Screens/Inventory/Mask/BunnyMask1/Ears.png
  BondageClub/index.html
Labels: asset

#2323 Feature: Adds a badge for the asset check to the readme
  README.md
Labels: feature

#2348 Lock Key-List change fix
  BondageClub/Scripts/Validation.js
Labels: fix

#2347 Bugfix: Prevents expressions from being saved to the wardrobe
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
Labels: fix

#2314 Nose access change for blindfolds
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: change

#2349 Elf Ear Position Options
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/HairAccessory1/ElfEars/Behind.png
  BondageClub/Screens/Inventory/HairAccessory1/ElfEars/InFront.png
Labels: asset, improvement

#2352 Bugfix: Fixes a minor graphical issue with the pearl necklace
  BondageClub/Assets/Female3DCG/Necklace/Necklace4.png
Labels: asset, fix

#2355 Bugfix: Fixes an owner/lover lock validation issue
  BondageClub/Scripts/Validation.js
Labels: fix

#2354 Shock command for the futuristic vibrator
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: asset, feature

#2350 Giggle activity
  BondageClub/Assets/Female3DCG/Activity/MoanGagGiggle.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBoots/BalletHeels_Large.png
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
Labels: feature

#2360 clit ring
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/ClitRing.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/ClitRingLeash.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Kneel/ClitRing.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Kneel/ClitRingLeash.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Preview/ClitRing.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/Base.png
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/ClitRing.js
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/Leash.png
  BondageClub/index.html
Labels: asset

#2342 Canvas Draw Hooks + Virtual Avatars for VR Headset
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/FreeVR.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/InteractiveVRHeadset.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
Labels: feature

#2364 Notifications Improvements
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Notification.js
Labels: improvement

#2362 Locking vibrating Butt plug
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemButt/Preview/LockingVibePlug.png
  BondageClub/Screens/Inventory/ItemButt/LockingVibePlug/LockingVibePlug.js
  BondageClub/index.html
Labels: asset

#2361 Fix: CharacterLoadCanvas Lint
  BondageClub/Scripts/Character.js
Labels: fix

#2279 ChatRoomSync-Split: Enable ChatRoomSyncReorderPlayers
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2278 ChatRoomSync-Split: Enable ChatRoomSyncMovePlayer
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2277 ChatRoomSync-Split: Enable ChatRoomSyncSwapPlayers
  BondageClub/Scripts/Server.js
Labels: refactor, server

#2363 Immersion: Chat room names and descriptions are garbled while blind
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Speech.js
Labels: feature

#2376 Bug fix: Adding missing tag
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2375 New item: Short pencil skirt
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/ShortPencilSkirt.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPencilSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPencilSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPencilSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPencilSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: asset

#2374 Cleanup: Scripts formatting (Part 9 - `Screens/Inventory/*` - rest)
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/OldGasMask.js
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/SafewordPadlock/SafewordPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTag/CollarNameTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLivestock/CollarNameTagLivestock.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagLover/CollarNameTagLover.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagOval/CollarNameTagOval.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarNameTagPet/CollarNameTagPet.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
Labels: improvement

#2373 Cleanup: Scripts formatting (Part 8 - `Screens/Inventory/*` - Futuristic items)
  BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
  BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
  BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt2/FuturisticChastityBelt2.js
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/FuturisticHarness.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: improvement

#2372 Cleanup: Scripts formatting (Part 7 - `Screens/Inventory/*` - little changes)
  BondageClub/Screens/Inventory/ClothAccessory/BunnyCollarCuffs/BunnyCollarCuffs.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/CeilingChain.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/CeilingRope.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticArmbinder/FuturisticArmbinder.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/FuturisticStraitjacket.js
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/InflatableStraightLeotard.js
  BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/LeatherArmbinder.js
  BondageClub/Screens/Inventory/ItemArms/LeatherCuffs/LeatherCuffs.js
  BondageClub/Screens/Inventory/ItemArms/LeatherStraitJacket/LeatherStraitJacket.js
  BondageClub/Screens/Inventory/ItemArms/MermaidSuit/MermaidSuit.js
  BondageClub/Screens/Inventory/ItemArms/OrnateCuffs/OrnateCuffs.js
  BondageClub/Screens/Inventory/ItemArms/StraitJacket/StraitJacket.js
  BondageClub/Screens/Inventory/ItemArms/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemBoots/ToeTape/ToeTape.js
  BondageClub/Screens/Inventory/ItemButt/AnalBeads2/AnalBeads2.js
  BondageClub/Screens/Inventory/ItemButt/AnalHook/AnalHook.js
  BondageClub/Screens/Inventory/ItemButt/InflVibeButtPlug/InflVibeButtPlug.js
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
  BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Cushion.js
  BondageClub/Screens/Inventory/ItemDevices/PetBed/PetBed.js
  BondageClub/Screens/Inventory/ItemDevices/Pole/Pole.js
  BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/BluetoothEarbuds.js
  BondageClub/Screens/Inventory/ItemEars/FuturisticEarphones/FuturisticEarphones.js
  BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
  BondageClub/Screens/Inventory/ItemEars/Headphones/Headphones.js
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/InteractiveVRHeadset.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/InteractiveVisor.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemMisc/ExclusivePadlock/ExclusivePadlock.js
  BondageClub/Screens/Inventory/ItemMisc/IntricatePadlock/IntricatePadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MetalPadlock/MetalPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/MistressPadlock/MistressPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/OwnerPadlock/OwnerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPadlock/TimerPadlock.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/MilkBottle/MilkBottle.js
  BondageClub/Screens/Inventory/ItemMouth2/ClothGag/ClothGag.js
  BondageClub/Screens/Inventory/ItemMouth3/ClothGag/ClothGag.js
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/ElectronicTag/ElectronicTag.js
  BondageClub/Screens/Inventory/ItemNipples/PlateClamps/PlateClamps.js
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/RoundPiercing.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Screens/Inventory/ItemVulva/ClitAndDildoVibratorbelt/ClitAndDildoVibratorbelt.js
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/ClitRing.js
Labels: improvement

#2371 Cleanup: Scripts formatting (Part 6 - `Assets/Female3DCG/Female3DCG.js`)
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: improvement

#2370 Cleanup: Scripts formatting (Part 5 - `Scripts/Struggle.js`)
  BondageClub/Scripts/Struggle.js
Labels: improvement

#2369 Cleanup: Scripts formatting (Part 4 - `Scripts/Dialog.js`)
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2368 Cleanup: Scripts formatting (Part 3 - `Scripts/Character.js`)
  BondageClub/Scripts/Character.js
Labels: improvement

#2367 Cleanup: Scripts formatting (Part 2 - `Scripts/Animation.js`)
  BondageClub/Scripts/Animation.js
Labels: improvement

#2366 Cleanup: Scripts formatting (Part 1 - little edits)
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/AfkTimer.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Drawing3D.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/GameLog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/MiniGame.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Notification.js
  BondageClub/Scripts/Reputation.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Skill.js
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/Timer.js
  BondageClub/Scripts/Translation.js
  BondageClub/Scripts/Validation.js
  BondageClub/Scripts/VibratorMode.js
Labels: improvement

#2383 Refactor: AllowPose changes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: refactor

#2380 Preference Subscreen Escaping
  BondageClub/Screens/Character/Preference/Preference.js
Labels: fix, improvement

#2379 Refactor: Extended Vibrator Script for the Sybian
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/Sybian/Sybian.js
Labels: refactor

#2384 Icon Notification Option
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Notification.js
  BondageClub/index.html
Labels: feature
