Repository Ben987/Bondage-College, pull requests merged in 2021-07, with the labels that each got.

#2649 Feature: Adds extended item support to `InventoryWearRandom` (and NPCs!)
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2650 Improvement: Force reset the canvas after a context loss if it is not restored after 10 seconds
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
Labels: fix, improvement

#2652 Extended item migration: ItemHead
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemHead/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemHead/WebBlindfold/WebBlindfold.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: refactor

#2653 Bugfix/Improvement: `GagUnique` prerequisite improvements
  BondageClub/Scripts/Inventory.js
Labels: fix, improvement

#2654 New eyes expression ^_^
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes1.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes10.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes11.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes12.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes13.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes2.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes3.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes4.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes5.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes6.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes7.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes8.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Eyes9.png
  BondageClub/Assets/Female3DCG/Eyes/ShylyHappy/Icon.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes1.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes10.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes11.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes12.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes13.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes2.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes3.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes4.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes5.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes6.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes7.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes8.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Eyes9.png
  BondageClub/Assets/Female3DCG/Eyes2/ShylyHappy/Icon.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2655 Update FoxyHarnessPanelGag to support all slots
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, change

#2656 ItemDevices extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Familiar/Familiar.js
  BondageClub/Screens/Inventory/ItemDevices/InflatableBodyBag/InflatableBodyBag.js
  BondageClub/Screens/Inventory/ItemDevices/LittleMonster/LittleMonster.js
  BondageClub/Screens/Inventory/ItemDevices/PetBed/PetBed.js
  BondageClub/Screens/Inventory/ItemDevices/Pole/Pole.js
  BondageClub/Screens/Inventory/ItemDevices/TeddyBear/TeddyBear.js
  BondageClub/Screens/Inventory/ItemDevices/Vacbed/Vacbed.js
  BondageClub/Scripts/Audio.js
  BondageClub/index.html
Labels: refactor

#2658 ItemLegs extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemLegs/LeatherLegCuffs/LeatherLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemLegs/Zipties/Zipties.js
  BondageClub/index.html
Labels: fix, refactor

#2659 ItemEars extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/BluetoothEarbuds.js
  BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
  BondageClub/Screens/Inventory/ItemEars/Headphones/Headphones.js
  BondageClub/index.html
Labels: refactor

#2651 WebGL render options
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/GLDraw.js
Labels: improvement

#2660 Merge fixes + ItemFeet extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemFeet/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemFeet/LeatherAnkleCuffs/LeatherAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/OrnateAnkleCuffs/OrnateAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemFeet/Zipties/Zipties.js
  BondageClub/index.html
Labels: fix, refactor

#2661 Gag Removal Fix
  BondageClub/Scripts/Inventory.js
Labels: fix

#2664 New Item: Short Plaid Skirt
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/ShortPlaidSkirt.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPlaidSkirt_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPlaidSkirt_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPlaidSkirt_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/ShortPlaidSkirt_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2663 Improvement: Add check for auto-generated `AllowType`, `AllowBlock` and `AllowEffect`
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Tools/Node/AssetCheck.js
Labels: improvement

#2662 misc type related fixes
  BondageClub/Screens/Character/Creation/Creation.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Cutscene/PlayerMistress/PlayerMistress.js
  BondageClub/Screens/MiniGame/Tennis/Tennis.js
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#2665 Feature: New screen functions and optimisations
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ControllerSupport.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: feature, improvement

#2666 Improvement: Optimise and cleanup chatroom code
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2667 New item: Hitching Post
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/Post_Base.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/Post_Chain.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/Post_Head.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/Post_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/Post_Post.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Post_Base.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Post_Chain.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Post_Head.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Post_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Post_Post.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Preview/Post.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2668 resize crash fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Element.js
Labels: fix, priority

#2669 various color picker fixes
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: fix

#2670 Boxes/Cages/... fixes + New item: Kennel
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/KennelClosedPadding_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelClosedPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelClosed_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelClosed_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelOpenPadding_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelOpenPadding_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kennel_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kennel_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kennel_Kennel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kennel_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kennel_Padding.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/Kennel.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Audio/CageClose.mp3
  BondageClub/Audio/CageEquip.mp3
  BondageClub/Audio/CageOpen.mp3
  BondageClub/Audio/CageStruggle.mp3
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/CeilingChain.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/CeilingRope.js
  BondageClub/Screens/Inventory/ItemDevices/Kennel/ClosedNoPadding.png
  BondageClub/Screens/Inventory/ItemDevices/Kennel/ClosedPadding.png
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel_Lock.png
  BondageClub/Screens/Inventory/ItemDevices/Kennel/OpenNoPadding.png
  BondageClub/Screens/Inventory/ItemDevices/Kennel/OpenPadding.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: asset, change, fix

#2671 Removed unused files
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Body.pdn
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Frame.pdn
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid_Closed.pdn
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Belt.pdn
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt_Large_Belt_3.pdn
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticTrainingBelt_Large_Belt.pdn
Labels: fix

#2672 New item: diapers4
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Panties/Diapers4_LargeButterfly_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_LargeFlower_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_LargeSpots_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_LargeStrawBerry_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Large_Diaper.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Large_Tape.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_NormalButterfly_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_NormalFlower_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_NormalSpots_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_NormalStrawBerry_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Normal_Diaper.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Normal_Tape.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_SmallButterfly_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_SmallFlower_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_SmallSpots_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_SmallStrawBerry_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Small_Diaper.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_Small_Tape.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLargeButterfly_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLargeFlower_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLargeSpots_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLargeStrawBerry_Pattern.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLarge_Diaper.png
  BondageClub/Assets/Female3DCG/Panties/Diapers4_XLarge_Tape.png
  BondageClub/Assets/Female3DCG/Panties/Preview/Diapers4.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Panties/Diapers4/Butterflies.png
  BondageClub/Screens/Inventory/Panties/Diapers4/Flower.png
  BondageClub/Screens/Inventory/Panties/Diapers4/None.png
  BondageClub/Screens/Inventory/Panties/Diapers4/Spots.png
  BondageClub/Screens/Inventory/Panties/Diapers4/StrawBerry.png
Labels: asset

#2673 missing catsuit zips
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Large_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Normal_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_Small_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/Catsuit_XLarge_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Large_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Normal_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_Small_Zip.png
  BondageClub/Assets/Female3DCG/SuitLower/Hogtied/SeethroughSuitZip_XLarge_Zip.png
Labels: fix

#2674 New fur items
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/FurHeadband.png
  BondageClub/Assets/Female3DCG/Hat/Preview/FurHeadband.png
  BondageClub/Assets/Female3DCG/Hat/Suspension/FurHeadband.png
  BondageClub/Assets/Female3DCG/Necklace/FurScarf.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/FurScarf.png
Labels: asset

#2675 Bra extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/Bra/CuteBikini1/CuteBikini1.js
  BondageClub/Screens/Inventory/Bra/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/Bra/SexyBikini1/SexyBikini1.js
  BondageClub/index.html
Labels: refactor

#2676 Clothes extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ClothAccessory/BunnyCollarCuffs/BunnyCollarCuffs.js
  BondageClub/Screens/Inventory/Glasses/EyePatch1/EyePatch1.js
  BondageClub/Screens/Inventory/Necklace/NecklaceKey/NecklaceKey.js
  BondageClub/Screens/Inventory/Necklace/NecklaceLock/NecklaceLock.js
  BondageClub/index.html
Labels: refactor

#2678 ItemPelvis extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OrnateChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/PolishedChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/StuddedChastityBelt.js
  BondageClub/index.html
Labels: refactor

#2679 new backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/Office1.jpg
  BondageClub/Backgrounds/Office2.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#2680 Preview Icons
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/ShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBaguette.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBallgag.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBelt.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysCandleWax.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysCane.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysCattleProd.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysCrop.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysElectricToothbrush.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysFeather.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysFeatherDuster.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysFlogger.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysGavel.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysHairbrush.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysHeartCrop.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysIceCube.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLargeDildo.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLongDuster.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLongSock.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysLotion.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPaddle.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPanties.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPetToy.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilLong.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilShort.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRuler.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysShockWand.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysSmallDildo.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysSmallVibratingWand.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysSpatula.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysSword.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTapeRoll.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTennisRacket.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysToothbrush.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTowel.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysVibeRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysVibratingWand.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysVibrator.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysWartenbergWheel.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysWhip.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysWhipPaddle.png
  BondageClub/Icons/Previews/Favorite.png
  BondageClub/Icons/Previews/Handheld.png
  BondageClub/Icons/Previews/Locked.png
  BondageClub/Icons/Previews/LoverOnly.png
  BondageClub/Icons/Previews/OwnerOnly.png
  BondageClub/Icons/Previews/Unlocked.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature, refactor

#2681 Extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemBoots/ToeTape/ToeTape.js
  BondageClub/Screens/Inventory/ItemHood/GwenHood/GwenHood.js
  BondageClub/Screens/Inventory/ItemNipples/PlateClamps/PlateClamps.js
  BondageClub/Screens/Inventory/ItemPelvis/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemPelvis/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemTorso/HempRopeHarness/HempRopeHarness.js
  BondageClub/index.html
Labels: refactor

#2682 Kennel improvements
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA10_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA2_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA3_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA4_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA5_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA6_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA7_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA8_Door.png
  BondageClub/Assets/Female3DCG/ItemDevices/KennelA9_Door.png
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js
  BondageClub/Scripts/Struggle.js
Labels: asset, change

#2684 Up button improvements
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
Labels: fix, improvement

#2683 Updates and fixes to the FuturisticVibrator (and minor change to FuturisticTrainingBelt)
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: change

#2685 validation lock check
  BondageClub/Scripts/Validation.js
Labels: fix

#2686 FlowerBra
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Large_Bra.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Large_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Normal_Bra.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Normal_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Small_Bra.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_Small_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_XLarge_Bra.png
  BondageClub/Assets/Female3DCG/Bra/FlowerBra_XLarge_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Large_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Large_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Normal_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Normal_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Small_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_Small_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_XLarge_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FlowerBra_XLarge_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Preview/FlowerBra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Large_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Large_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Normal_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Normal_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Small_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_Small_Flowers.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_XLarge_Bra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FlowerBra_XLarge_Flowers.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2687 Key accessory for collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/Key.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/Preview/Key.png
Labels: asset

#2689 minor fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#2691 Empty Warehouse & Leather Chamber backgrounds
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/EmptyWarehouse.jpg
  BondageClub/Backgrounds/LeatherChamber.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#2693 Recreate chat room fixes
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#2694 Update timing on auto shock collar and futuristic items
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: improvement

#2692 Changelog: R70 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/changelog.html
Labels: changelog

#2698 Maid rescue grammar fix
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor_DE.txt
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor_RU.txt
Labels: fix

#2697 key background fix
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/Preview/Key.png
Labels: asset, beta-fix

#2699 Favorites for Extreme Difficulty & Worn Items
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix, improvement

#2700 Modular Item Validation Fix
  BondageClub/Scripts/TypedItem.js
Labels: beta-fix

#2701 Unusable Favorites Fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix

#2702 harem typo
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix

#2703 Futuristic Crate Alpha Mask Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2704 minor fixes
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/FuturisticCrate.js
Labels: beta-fix

#2705 Bugfix: Font size setting adjustments
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2706 allfours fix for futuristic bra
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2708 Color Picker Fixes
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Dialog.js
Labels: fix

#2709 WiredEgg missing AllowEffect
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2710 kennel changes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js
Labels: change

#2711 garters shop
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
Labels: fix

#2712 Shock unit: red light
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Scripts/Dialog.js
Labels: asset, change, improvement

#2713 New Item: Gothic Collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Collar.png
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Flowers.png
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Jewels.png
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Metal.png
  BondageClub/Assets/Female3DCG/ItemNeck/GothicCollar_Ornaments.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/GothicCollar.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2714 Fixes issues with the training belt
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: beta-fix

#2715 Beta-fix: Removes forgotten OrnateLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/OrnateLegCuffs/OrnateLegCuffs.js
Labels: beta-fix

#2716 Beta-fix: Convert ItemTorso:NylonRopeHarness to typed item
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/ItemTorso/NylonRopeHarness/NylonRopeHarness.js
  BondageClub/index.html
Labels: refactor

#2717 Beta-fix: AssetCheck: respect CopyConfig
  BondageClub/Tools/Node/AssetCheck.js
Labels: beta-fix

#2718 barefootsandals missing assets
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandals1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/LegsClosed/BarefootSandals1_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals1_Large.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals1_Normal.png
  BondageClub/Assets/Female3DCG/Shoes/Spread/BarefootSandals1_Small.png
Labels: fix

#2719 Fix intensity = 0 in training belt
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: beta-fix

#2720 New item: Nipple Piercing Chain
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Large_Heart.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Large_Piercing.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Normal_Heart.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Piercing.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Small_Heart.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Small_Piercing.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_XLarge_Heart.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_XLarge_Piercing.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/Preview/NecklacePiercingChain.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2721 fix: finished collar rope split
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemLegs/Sybian.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeMedium_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeShort_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeShort_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeMedium_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeMedium_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeMedium_Rope.png
Labels: fix

#2723 Futuristic Bra Extra Type
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeShow2Heart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeShow2Heart_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeShow2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeShow2_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_LargeSolid2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Large_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalShow2Heart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalShow2Heart_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalShow2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalShow2_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_NormalSolid2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Normal_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallShow2Heart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallShow2Heart_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallShow2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallShow2_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_SmallSolid2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_Small_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeShow2Heart_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeShow2Heart_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeShow2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeShow2_Text.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLargeSolid2_Bra.png
  BondageClub/Assets/Female3DCG/ItemBreast/FuturisticBra_XLarge_Mesh2.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
Labels: asset

#2724 Remove unneeded GagHeavy from futuristic crate
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2725 Shop Sell Group Fix
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
Labels: beta-fix

#2727 Breast Binder Preview Fix
  BondageClub/Assets/Female3DCG/ItemBreast/Preview/LeatherBreastBinder.png
Labels: fix

#2729 [Betafix] [Natsuki] R70 RE-bracelet image fix
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/BowBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/BowBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/BowBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/KinkBracelet_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/KinkBracelet_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/KinkBracelet_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LesBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LesBand_Small.png
Labels: beta-fix

#2728 Changelog: R70 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2730 missing lock
  BondageClub/Assets/Female3DCG/ItemMouth/HarnessPonyBitsDetached_Lock.png
Labels: fix

#2731 removed unused files
  BondageClub/Assets/Female3DCG/ItemMouth2/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth2/Preview/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/PlasticWrap.png
  BondageClub/Assets/Female3DCG/ItemMouth3/Preview/PlasticWrap.png
Labels: fix

#2732 hover priority changes
  BondageClub/Scripts/Drawing.js
Labels: change, improvement

#2733 Colour Entry Fix
  BondageClub/Scripts/ColorPicker.js
Labels: beta-fix

#2734 Blind Examine setting change
  BondageClub/Screens/Character/Preference/Preference.js
Labels: change

#2735 Thrash Spelling
  BondageClub/Screens/Room/CollegeChess/Dialog_NPC_CollegeChess_Opponent.csv
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Dominatrix.csv
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Kidnapper.csv
  BondageClub/Screens/Room/MovieStudio/Dialog_NPC_MovieStudio_Interview_Journalist.csv
  BondageClub/Screens/Room/MovieStudio/Dialog_NPC_MovieStudio_Interview_Mistress.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_EntranceMaid.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_KidnapTarget.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomGuard.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMaid.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMistress.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RescueGuard.csv
  BondageClub/Screens/Room/PandoraPrison/Dialog_NPC_PandoraPrison_Guard.csv
Labels: beta-fix

#2736 Bugfix: Ensures characters refresh properly after calling `InventoryWearRandom`
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#2737 Permissions Mode Resetting
  BondageClub/Scripts/Dialog.js
Labels: change

#2738 Fix bug with training belt not updating if another player changes it
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: beta-fix

#2739 Beta-fix: Fixes stuck relog screen outside of chatroom
  BondageClub/Screens/Character/Login/Login.js
Labels: beta-fix

#2740 Fix for futuristic crate alpha mask
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2743 Fix futuristic collar chastity bra coloring
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2742 Random Item From Lists improvement
  BondageClub/Screens/Room/DailyJob/DailyJob.js
  BondageClub/Screens/Room/PandoraPrison/PandoraPrison.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix, improvement

#2744 Changelog: R70 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2745 [Asset] [Beta Fix] Blouse Preview Fix 2
  BondageClub/Assets/Female3DCG/Cloth/Preview/Blouse1.png
  BondageClub/Assets/Female3DCG/Suit/Preview/Blouse1.png
Labels: beta-fix

#2746 lock change belts
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: beta-fix

#2747 Spanking toys get type issue
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: fix

#2748 Positioning fix
  BondageClub/Assets/Female3DCG/Necklace/FurScarf.png
Labels: beta-fix

#2749 Fix crash when futuristic training belt triggers orgasm
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2750 Changelog: R70
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2751 [Fix] Blouse TapedHands Missing
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/Blouse1_Large.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/Blouse1_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/Blouse1_Small.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/Blouse1_XLarge.png
  BondageClub/Assets/Female3DCG/Suit/TapedHands/Blouse1_Large.png
  BondageClub/Assets/Female3DCG/Suit/TapedHands/Blouse1_Normal.png
  BondageClub/Assets/Female3DCG/Suit/TapedHands/Blouse1_Small.png
  BondageClub/Assets/Female3DCG/Suit/TapedHands/Blouse1_XLarge.png
Labels: asset, beta-fix

#2754 Fix ruined orgasms
  BondageClub/Scripts/Activity.js
Labels: hotfix

#2755 fix random typed items
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: hotfix

#2758 Futuristic Training Belt Punishment Fix
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: hotfix

#2761 fix missing dialog
  BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
Labels: hotfix

#2770 cafe crash fix
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv
Labels: hotfix

#2775 Priority fix: Fixes lint error
  BondageClub/Screens/Character/Login/Login.js
Labels: fix, priority

#2752 fix leotard behavior
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: change, fix

#2753 fix chat room name garble
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2756 multicolor witch hat
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/Suspension/WitchHat1_Band.png
  BondageClub/Assets/Female3DCG/Hat/Suspension/WitchHat1_Hat.png
  BondageClub/Assets/Female3DCG/Hat/WitchHat1.png
  BondageClub/Assets/Female3DCG/Hat/WitchHat1_Band.png
  BondageClub/Assets/Female3DCG/Hat/WitchHat1_Hat.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2759 fix incorrect room blocks persistance
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
Labels: fix

#2760 Misc. things
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Swimsuit1_LargeDull.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Swimsuit1_NormalDull.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Swimsuit1_SmallDull.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Swimsuit1_XLargeDull.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_LargeDull.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_NormalDull.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_SmallDull.png
  BondageClub/Assets/Female3DCG/Bra/Swimsuit1_XLargeDull.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Swimsuit1_LargeDull.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Swimsuit1_NormalDull.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Swimsuit1_SmallDull.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Swimsuit1_XLargeDull.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/KeyProp_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/KeyProp.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/KeyProp_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/KeyProp_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/KeyProp_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/KeyProp_XLarge.png
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/LingerieShop.jpg
  BondageClub/Backgrounds/SciFiRed.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Bra/Swimsuit1/Dull.png
  BondageClub/Screens/Inventory/Bra/Swimsuit1/Shiny.png
Labels: asset

#2765 Fix: Private ActivityTarget being replaced only once
  BondageClub/Screens/Room/Private/Private.js
Labels: fix

#2766 Sensory Deprivation Changes
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change

#2767 Arousal Glow Options
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Private/Private.js
Labels: feature

#2771 Moves the $ sign to the beginning of the price rather than the end
  BondageClub/Screens/Room/Shop/Shop.js
Labels: change

#2781 New item: Nipple Stretchers
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNipples/Preview/StretchClovers.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Large_Clamps.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Large_Frame.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Normal_Clamps.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Normal_Frame.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Small_Clamps.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_Small_Frame.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_XLarge_Clamps.png
  BondageClub/Assets/Female3DCG/ItemNipples/StretchClovers_XLarge_Frame.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2780 Use string.replace rather than string.replaceAll in futuristic vibe
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: fix

#2777 move the $ in all .csv files
  BondageClub/Screens/Cutscene/NPCSlaveAuction/Text_NPCSlaveAuction.csv
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Room/Arcade/Dialog_NPC_Arcade_Employee.csv
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_EscapedPatient.csv
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_KidnapNurse.csv
  BondageClub/Screens/Room/AsylumMeeting/Dialog_NPC_AsylumMeeting_PatientLeft.csv
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv
  BondageClub/Screens/Room/CollegeCafeteria/Dialog_NPC_CollegeCafeteria_Sidney.csv
  BondageClub/Screens/Room/CollegeChess/Dialog_NPC_CollegeChess_Opponent.csv
  BondageClub/Screens/Room/CollegeDetention/Dialog_NPC_CollegeDetention_Yuki.csv
  BondageClub/Screens/Room/CollegeTennis/Dialog_NPC_CollegeTennis_Jennifer.csv
  BondageClub/Screens/Room/DailyJob/Dialog_NPC_DailyJob_DojoTeacher.csv
  BondageClub/Screens/Room/DailyJob/Dialog_NPC_DailyJob_PuppyMistress.csv
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_SecondSub.csv
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Supervisor.csv
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid.csv
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_RandomKidnapper.csv
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_Trainer.csv
  BondageClub/Screens/Room/Magic/Dialog_NPC_Magic_Assistant.csv
  BondageClub/Screens/Room/Magic/Dialog_NPC_Magic_Performer.csv
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid.csv
  BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress.csv
  BondageClub/Screens/Room/MovieStudio/Dialog_NPC_MovieStudio_Director.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMaid.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMemberNew.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMemberOld.csv
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMistress.csv
  BondageClub/Screens/Room/PandoraPrison/Dialog_NPC_PandoraPrison_Guard.csv
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Vendor.csv
  BondageClub/Screens/Room/PrivateRansom/Text_PrivateRansom.csv
  BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Teacher.csv
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/SlaveMarket/Dialog_NPC_SlaveMarket_Mistress.csv
  BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Trainer.csv
Labels: change

#2774 Buygroups cleanup
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2772 minor tweaks to items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/NecklacePiercingChain_Normal_Piercing.png
Labels: fix

#2769 [Asset] Floral Panties 2
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Large_Base.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Large_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Normal_Base.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Normal_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Small_Base.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_Small_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_XLarge_Base.png
  BondageClub/Assets/Female3DCG/Panties/FloralPanties2_XLarge_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/Preview/FloralPanties2.png
Labels: asset

#2768 bracelet fixes
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/BowBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/BowBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/BowBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/BowBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/KinkBracelet_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/KinkBracelet_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/KinkBracelet_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/KinkBracelet_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/AllFours/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/BowBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/BowBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/BowBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/BowBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/KinkBracelet_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/KinkBracelet_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/KinkBracelet_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/KinkBracelet_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/BowBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/BowBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/BowBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/BowBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/KinkBracelet_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/KinkBracelet_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/KinkBracelet_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/KinkBracelet_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/BowBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/BowBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/BowBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/BowBand_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/KinkBracelet_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/KinkBracelet_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/KinkBracelet_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/KinkBracelet_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/BackElbowTouch/LesBand_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2764 Random Groups fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: fix

#2763 type fixes
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Room/Arcade/Arcade.js
  BondageClub/Screens/Room/CollegeTennis/CollegeTennis.js
  BondageClub/Screens/Room/DailyJob/DailyJob.js
  BondageClub/Screens/Room/InfiltrationPerks/InfiltrationPerks.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#2773 hideitem tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2762 More extended item refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemAddon/CeilingChain/CeilingChain.js
  BondageClub/Screens/Inventory/ItemAddon/CeilingRope/CeilingRope.js
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/InflatableStraightLeotard/InflatableStraightLeotard.js
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/MetalCuffs.js
  BondageClub/Screens/Inventory/ItemBreast/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemButt/AnalHook/AnalHook.js
  BondageClub/Screens/Inventory/ItemButt/ButtPlugLock/ButtPlugLock.js
  BondageClub/Screens/Inventory/ItemButt/ButtPump/ButtPump.js
  BondageClub/Screens/Inventory/ItemDevices/BondageBench/BondageBench.js
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
  BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Cushion.js
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/SpreaderMetal/SpreaderMetal.js
  BondageClub/Screens/Inventory/ItemHood/InflatedBallHood/InflatedBallHood.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemNipples/LactationPump/LactationPump.js
  BondageClub/Screens/Inventory/ItemNipples/NippleSuctionCups/NippleSuctionCups.js
  BondageClub/Screens/Inventory/ItemNipplesPiercings/RoundPiercing/RoundPiercing.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Inventory/ItemTorso/HeavyLatexCorset/HeavyLatexCorset.js
  BondageClub/Screens/Inventory/ItemTorso/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemVulva/ClitSuctionCup/ClitSuctionCup.js
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/ClitRing.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/index.html
Labels: improvement, refactor

#2787 Modular Items and Custom Tag improvements
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag2.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag3.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag4.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag5.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTag_Tag6.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t0.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t1.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t2.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t3.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t4.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/t5.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/x0.png
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: improvement

#2789 Futuristic training belt now uses original chat message
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2786 Bracelet and some hiding
  BondageClub/Assets/Female3DCG/Bracelet/Band1_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_LargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_LargeRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_NormalBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_NormalRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_SmallBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_SmallRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_XLargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Band1_XLargeRight.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_LargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_LargeRight.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_NormalBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_NormalRight.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_SmallBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_SmallRight.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_XLargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/Band1_XLargeRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Preview/Band1.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_Large.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_LargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_LargeRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_Normal.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_NormalBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_NormalRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_Small.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_SmallBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_SmallRight.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_XLarge.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_XLargeBoth.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/Band1_XLargeRight.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#2788 Futuristicbelt fix
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: fix

#2790 Fix/Improvement: Hogtied pose support for ItemNeckRestraints
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/ChainLeash.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/ChainLeashTaken.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/ChainLeashTaken_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/ChainLeash_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainLong_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainMedium_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainShort.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarChainShort_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarLeash.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarLeashTaken.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarLeashTaken_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarLeash_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeMedium_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeShort.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeShort_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/CollarRopeShort_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/Post_Base.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/Post_Chain.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/Post_Head.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/Post_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Hogtied/Post_Post.png
Labels: asset, improvement

#2791 rejoin room fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#2793 Improve visibility for nipple piercings under bras
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: improvement

#2795 Wardrobe Numbers in Names
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: change

#2794 Favourite Icon Improvements
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Icons/Previews/FavoriteBoth.png
  BondageClub/Icons/Previews/FavoritePlayer.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2796 Futuristic items fixes & cleanup
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
  BondageClub/Screens/Inventory/ItemEars/FuturisticEarphones/FuturisticEarphones.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/controller.zip
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: fix, refactor

#2797 fix extended pony bit
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#2799 more bit gag fixes
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Element.js
Labels: fix

#2776 Improvement: Use TypeScript for assetcheck
  .gitattributes
  .github/workflows/assetCheck.yml
  .github/workflows/lint.yml
  BondageClub/.eslintrc.json
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Notification.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/Tools/Node/jsconfig.json
  BondageClub/Tools/Node/package-lock.json
  BondageClub/Tools/Node/package.json
  BondageClub/Tools/Node/tsconfig-assetcheck.json
Labels: improvement

#2800 New fur items
  BondageClub/Assets/Female3DCG/Cloth/AllFours/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/Horse/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/Kneel/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/KneelingSpread/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/LegsClosed/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/Preview/FurCoat.png
  BondageClub/Assets/Female3DCG/Cloth/Spread/FurCoat_Lower.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/FurCoat_Upper.png
  BondageClub/Assets/Female3DCG/ClothAccessory/AllFours/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackCuffs/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Hogtied/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/FurBolero.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/FurBolero.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Necklace/FurScarf.png
Labels: asset

#2785 New Item: fuck machine
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Caps.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Dildo.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Metal.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Plastic.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Pole.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuckMachine_Pussy.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/FuckMachine.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Inventory/ItemButt/AnalBeads2/AnalBeads2.js
  BondageClub/Screens/Inventory/ItemDevices/FuckMachine/FuckMachine.js
  BondageClub/Scripts/Inventory.js
  BondageClub/index.html
Labels: asset

#2784 HideItem cleanup & tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2779 Typed Item Custom Dictionary + Web refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: improvement, refactor

#2778 Old gas mask rework
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHood/OldGasMask_Lenses.png
  BondageClub/Assets/Female3DCG/ItemHood/OldGasMask_Rebreather.png
  BondageClub/Assets/Female3DCG/ItemHood/OldGasMask_TubeA.png
  BondageClub/Assets/Female3DCG/ItemHood/OldGasMask_TubeB.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesRebreather_Lenses.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesRebreather_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesTube1_Lenses.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesTube1_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesTube2_Lenses.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLensesTube2_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskLenses_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskRebreather.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskRebreather_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskTube1.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskTube1_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskTube2.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/OldGasMaskTube2_Lock.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/Preview/OldGasMaskRebreather.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/Preview/OldGasMaskTube1.png
  BondageClub/Assets/Female3DCG/ItemHoodAddon/Preview/OldGasMaskTube2.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/OldGasMask.js
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/a0.png
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/a1.png
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/a2.png
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/a3.png
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/l0.png
  BondageClub/Screens/Inventory/ItemHood/OldGasMask/l1.png
  BondageClub/Scripts/Speech.js
  BondageClub/index.html
Labels: change, refactor

#2801 fix missing preview
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/FurBolero.png
Labels: fix

#2802 Dragon Tail Strap
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/TailStraps/DragonTailStrap1_Primary.png
  BondageClub/Assets/Female3DCG/TailStraps/DragonTailStrap1_Secondary.png
  BondageClub/Assets/Female3DCG/TailStraps/Preview/DragonTailStrap1.png
Labels: asset

#2798 Enchanted help for commands
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Commands.js
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
  BondageClub/Screens/Online/ChatRoom/Text_Commands.csv
  BondageClub/Screens/Online/ChatRoom/Text_Commands_DE.txt
  BondageClub/Screens/Online/ChatRoom/Text_Commands_FR.txt
  BondageClub/Screens/Online/ChatRoom/Text_Commands_RU.txt
  BondageClub/Scripts/Text.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: improvement

#2803 Changed ColorGroup lookup tags and fixed misc ColorGroup names
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/ColorGroups_FR.txt
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: change, fix

#2804 fix timer lover lock
  BondageClub/Screens/Inventory/ItemMisc/LoversTimerPadlock/LoversTimerPadlock.js
Labels: fix

#2805 Fix // comand
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Commands.js
Labels: fix, improvement

#2806 high thigh boots
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBoots/HighThighBoots_Large.png
  BondageClub/Assets/Female3DCG/ItemBoots/HighThighBoots_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/HighThighBoots_Normal.png
  BondageClub/Assets/Female3DCG/ItemBoots/HighThighBoots_Small.png
  BondageClub/Assets/Female3DCG/ItemBoots/HighThighBoots_XLarge.png
  BondageClub/Assets/Female3DCG/ItemBoots/Hogtied/HighThighBoots_Large.png
  BondageClub/Assets/Female3DCG/ItemBoots/Hogtied/HighThighBoots_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/Hogtied/HighThighBoots_Normal.png
  BondageClub/Assets/Female3DCG/ItemBoots/Hogtied/HighThighBoots_Small.png
  BondageClub/Assets/Female3DCG/ItemBoots/Hogtied/HighThighBoots_XLarge.png
  BondageClub/Assets/Female3DCG/ItemBoots/Kneel/HighThighBoots_Large.png
  BondageClub/Assets/Female3DCG/ItemBoots/Kneel/HighThighBoots_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/Kneel/HighThighBoots_Normal.png
  BondageClub/Assets/Female3DCG/ItemBoots/Kneel/HighThighBoots_Small.png
  BondageClub/Assets/Female3DCG/ItemBoots/Kneel/HighThighBoots_XLarge.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/HighThighBoots_Large.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/HighThighBoots_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/HighThighBoots_Normal.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/HighThighBoots_Small.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/HighThighBoots_XLarge.png
  BondageClub/Assets/Female3DCG/ItemBoots/Preview/HighThighBoots.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/HighThighBoots_Large.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/HighThighBoots_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/HighThighBoots_Normal.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/HighThighBoots_Small.png
  BondageClub/Assets/Female3DCG/ItemBoots/Spread/HighThighBoots_XLarge.png
Labels: asset

#2809 Kinkydungeon1.5
  BondageClub/Assets/Female3DCG/Emoticon/Gaming/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/Gaming/Icon.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/SummonSkeleton.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/SummonSkeletons.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectrify.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectrifyHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/Potion.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionFrigid.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionHealth.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionHealthGreater.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionHealthUltimate.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionMana.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/PotionStamina.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/AnimatedArmor.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/GreaterSkeleton.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/LesserSkeleton.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Necromancer.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Skeleton.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Brickwork.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Chest.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/ChestOpen.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Doodad.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Door.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/DoorOpen.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Floor.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Rubble.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/RubbleLooted.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Shrine.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/ShrineBroken.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/StairsDown.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/StairsUp.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Wall.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/PotionHealth.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/index.html
Labels: change, feature

#2810 fix - make ceiling chain unchangeable when locked
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#2811 [Fix] [Natsuki] Kneel wrap addition
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemLegs/Kneel/PlasticWrap_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/Kneel/PlasticWrap_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/Kneel/PlasticWrap_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/Kneel/PlasticWrap_XLarge.png
Labels: asset
