Repository Ben987/Bondage-College, pull requests merged in 2021-03, with the labels that each got.

#2159 Camisole
  BondageClub/Assets/Female3DCG/Bra/Camisole_Large.png
  BondageClub/Assets/Female3DCG/Bra/Camisole_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Camisole_Small.png
  BondageClub/Assets/Female3DCG/Bra/Camisole_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Camisole_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Camisole_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Camisole_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Camisole_Xlarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/Camisole.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Camisole_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Camisole_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Camisole_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Camisole_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2160 Fix: Game version
  BondageClub/Scripts/Common.js
  BondageClub/index.html
Labels: fix

#2161 Asset description line break fix
  BondageClub/Scripts/Asset.js
Labels: fix

#2162 Fix: CRLF problems
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Translation.js
Labels: fix

#2164 Fix lockpicking impossible for locks placed in scripted rooms
  BondageClub/Scripts/Struggle.js
Labels: fix

#2165 Skips struggle minigame choice if the item will be easy to remove
  BondageClub/Scripts/Struggle.js
Labels: change

#2163 VR headset
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVRHeadset_Body.png
  BondageClub/Assets/Female3DCG/ItemHead/InteractiveVRHeadset_Display.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/InteractiveVRHeadset.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/SynthWave.jpg
  BondageClub/Icons/Arcade.png
  BondageClub/Icons/KinkyDungeon.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/AR.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/InteractiveVRHeadset.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/Off.png
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/Virtual.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: asset, feature

#2171 Migration to socketio.io v3
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/socket.io/socket.io.dev.js
  BondageClub/Scripts/socket.io/socket.io.dev.js.map
  BondageClub/Scripts/socket.io/socket.io.js
  BondageClub/Scripts/socket.io/socket.io.js.map
  BondageClub/Scripts/socket.io/socket.io.min.js
  BondageClub/Scripts/socket.io/socket.io.min.js.map
  BondageClub/Scripts/socket.io/socket.io.slim.dev.js
  BondageClub/Scripts/socket.io/socket.io.slim.dev.js.map
  BondageClub/Scripts/socket.io/socket.io.slim.js
  BondageClub/Scripts/socket.io/socket.io.slim.js.map
  BondageClub/index.html
Labels: improvement, server

#2155 Item fix: Rope collar
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/NeckRope.png
Labels: asset, change

#2169 Asset: Bandanna [Necklace]
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Necklace/Bandana.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/Bandana.png
Labels: asset

#2168 Audio Volume Fix
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Server.js
Labels: fix

#2178 Lock picking arousal fixes
  BondageClub/Scripts/Struggle.js
Labels: fix

#2172 Stop the player from being slowed by skirts
  BondageClub/Scripts/Character.js
Labels: change

#2175 Restriction setting to bypass NPC punishment
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2179 Bugfix: Fixes leather armbinder lock positioning issues
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderStrap_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinderWrapStrap_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinder_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinder_Strap.png
  BondageClub/Assets/Female3DCG/ItemArms/LeatherArmbinder_WrapStrap.png
Labels: fix

#2180 Migrate to socket.io v3 (Attempt 2)
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/socket.io/socket.io.dev.js
  BondageClub/Scripts/socket.io/socket.io.dev.js.map
  BondageClub/Scripts/socket.io/socket.io.js
  BondageClub/Scripts/socket.io/socket.io.js.map
  BondageClub/Scripts/socket.io/socket.io.min.js
  BondageClub/Scripts/socket.io/socket.io.min.js.map
  BondageClub/Scripts/socket.io/socket.io.slim.dev.js
  BondageClub/Scripts/socket.io/socket.io.slim.dev.js.map
  BondageClub/Scripts/socket.io/socket.io.slim.js
  BondageClub/Scripts/socket.io/socket.io.slim.js.map
  BondageClub/index.html
Labels: improvement

#2181 Kneel Button Merge Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2183 Fix having struggle options for things like the bed
  BondageClub/Scripts/Struggle.js
Labels: fix

#2182 Notification Popups and Rework
  BondageClub/Icons/Audio0.png
  BondageClub/Icons/Audio1.png
  BondageClub/Icons/Audio2.png
  BondageClub/Icons/Logo.png
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Notification.js
  BondageClub/Scripts/Notifications.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: feature

#2185 Character in Preview Images
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Notification.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature

#2187 Character in Previews - Performance Improvement
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2188 larp typo fix
  BondageClub/Screens/Online/Game/OnlineGameDictionary.csv
Labels: fix

#2190 Online Dialog overflow fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Labels: fix

#2191 Wardrobe Name Persistence
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: change

#2194 Metal Cuffs in front of the body
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_LargeBehindBack.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_NormalBehindBack.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_SmallBehindBack.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_XLargeBehindBack.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_XLarge.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/BehindBack.png
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/InFront.png
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/MetalCuffs.js
  BondageClub/index.html
Labels: asset, change

#2192 Changelog: R66 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2197 Sensory Deprivation Message Hiding fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2198 Enclosing Item Device Priority fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2200 Metal Cuffs Behind Back option difficulty fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/MetalCuffs.js
Labels: beta-fix, fix

#2201 Chatroom Subscreen Kicked Fix
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2203 Increase gag stimulation messages frequency
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix, change

#2204 Bugfix: Fixes incorrect synthwave background name casing
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2206 Increases the difficulty of the minigame to get up if you are kneeling
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix, change

#2207 Beta Fix: Camisole
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2208 Fixes futuristic collar not coloring the tag properly
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: beta-fix

#2209 Deluxe Mistress Boots alpha groups
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2211 Fix: Changelog on account creation
  BondageClub/Screens/Character/Creation/Creation.js
Labels: beta-fix

#2210 Added cyrilic for detect words to futuristic gag.
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: improvement

#2213 Bugfix: Incorrect variable reference in collar auto shock unit
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
Labels: beta-fix

#2214 Notification Fixes
  BondageClub/Screens/Character/Creation/Creation.js
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Scripts/Notification.js
Labels: beta-fix

#2215 Respirator gag fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2218 Fixes crash when applying prelocked extended item to unowned lover
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2220 Spread vs Hogtie fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2221 Changelog Update: R66 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2224 Chatroom Background Drawing Refactors
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
Labels: beta-fix, refactor

#2225 Suspension Kneel Fix
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/HempRope/HempRope.js
Labels: beta-fix

#2226 Chess Progress Change
  BondageClub/Screens/MiniGame/Chess/BondageChess.js
  BondageClub/Screens/MiniGame/Chess/chess.js
  BondageClub/Screens/Room/CollegeChess/CollegeChess.js
Labels: beta-fix, change

#2228 Fix: InventoryItemHasEffect
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Inventory.js
Labels: improvement

#2230 Chess Simultaneous Move Fix
  BondageClub/Screens/MiniGame/Chess/chess.js
Labels: beta-fix

#2229 Changelog: R66 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2232 Bugfix: Fixes feet items clipping with the long skirt
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/LongSkirt1_Back.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/LongSkirt1_Front.png
  BondageClub/Assets/Female3DCG/ClothLower/LongSkirt1_Back.png
  BondageClub/Assets/Female3DCG/ClothLower/LongSkirt1_Front.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, beta-fix

#2233 Fix/Improvement: Add friend list refresh button
  BondageClub/Icons/Small/Reset.png
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/FriendList/Text_FriendList.csv
Labels: beta-fix, improvement

#2234 Background Darkening Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2236 Bugfix: Collar cuffs now allow neck activities
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#2238 Changelog: Updates changelog for R66
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2241 Extended clothes on others fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#2242 Incorrect Clothes Pose fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2243 Bugfix: Corrects extended item arguments for the eyepatch
  BondageClub/Screens/Inventory/Glasses/EyePatch1/EyePatch1.js
Labels: fix

#2249 Appearance Esc Fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix

#2246 HairFront17/17b Position Adjustment
  BondageClub/Assets/Female3DCG/HairFront/HairFront17.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront17b.png
Labels: asset, fix

#2248 No Items Message
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2247 Metal Cuffs Default
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/BackCuffs/MetalCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_LargeInFront.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_NormalInFront.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_SmallInFront.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_XLargeInFront.png
  BondageClub/Screens/Inventory/ItemArms/MetalCuffs/MetalCuffs.js
Labels: asset, change

#2245 Sell Items in the Shop
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Screens/Room/Shop/Text_Shop.csv
Labels: feature

#2240 Sci-Fi Pleasure Panties
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/SciFiPleasurePanties.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Band.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Lock.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Mesh1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Mesh2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Plug1.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Plug2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/SciFiPleasurePanties_Screen.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Audio.js
  BondageClub/index.html
Labels: asset

#2235 Pig Nose Hook
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNose/PigNoseHook_Band.png
  BondageClub/Assets/Female3DCG/ItemNose/PigNoseHook_Hook.png
  BondageClub/Assets/Female3DCG/ItemNose/Preview/PigNoseHook.png
Labels: asset

#2231 Chess - Play as Black
  BondageClub/Screens/MiniGame/Chess/BondageChess.js
  BondageClub/Screens/MiniGame/Chess/chess.js
  BondageClub/Screens/Room/CollegeChess/CollegeChess.js
Labels: improvement

#2216 Refactor: Migrates the Butt Plug Lock to the extended item script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemButt/ButtPlugLock/ButtPlugLock.js
Labels: asset, improvement, refactor

#2212 Refactor: Migrates the leather/ornate/futuristic leg cuffs to the extended item script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/LeatherLegCuffs/LeatherLegCuffs.js
  BondageClub/Screens/Inventory/ItemLegs/OrnateLegCuffs/OrnateLegCuffs.js
Labels: asset, improvement, refactor

#2196 Asset: Blanket for Pet Bed
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Inner.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/PetBed/Blanket.png
  BondageClub/Screens/Inventory/ItemDevices/PetBed/NoBlanket.png
  BondageClub/Screens/Inventory/ItemDevices/PetBed/PetBed.js
  BondageClub/index.html
Labels: asset, improvement

#2244 Fix: Bundle fix for extended items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/Web/Web.js
  BondageClub/Screens/Inventory/ItemArms/Zipties/Zipties.js
  BondageClub/Screens/Inventory/ItemButt/AnalHook/AnalHook.js
  BondageClub/Screens/Inventory/ItemButt/ButtPump/ButtPump.js
  BondageClub/Screens/Inventory/ItemEars/Headphones/Headphones.js
  BondageClub/Screens/Inventory/ItemHead/WebBlindfold/WebBlindfold.js
  BondageClub/Screens/Inventory/ItemHood/InflatedBallHood/InflatedBallHood.js
  BondageClub/Screens/Inventory/ItemMouth/PumpGag/PumpGag.js
  BondageClub/Screens/Inventory/ItemNipples/LactationPump/LactationPump.js
  BondageClub/Screens/Inventory/ItemNipples/NippleSuctionCups/NippleSuctionCups.js
  BondageClub/Screens/Inventory/ItemVulva/ClitSuctionCup/ClitSuctionCup.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2239 Fix: Possible crashes when text items have bad properties
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
  BondageClub/Screens/Inventory/ItemDevices/PetBowl/PetBowl.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Screens/Inventory/ItemHood/CanvasHood/CanvasHood.js
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag.js/CustomCollarTag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/ElectronicTag/ElectronicTag.js
Labels: fix

#2227 Improvement/Fix: Moves chatroom rejoin functionality into ChatroomSync
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix, improvement, refactor

#2202 Block Arousal Activities in Room
  BondageClub/Screens/Online/ChatAdmin/Text_ChatAdmin.csv
  BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
  BondageClub/Screens/Online/ChatBlockItem/Text_ChatBlockItem.csv
  BondageClub/Screens/Online/ChatCreate/Text_ChatCreate.csv
  BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
  BondageClub/Scripts/Activity.js
Labels: feature

#2170 Add enhanced arrest flow
  BondageClub/Screens/Room/Gambling/Gambling.js
  BondageClub/Screens/Room/Prison/Dialog_NPC_Prison_Police.csv
  BondageClub/Screens/Room/Prison/Prison.js
  BondageClub/Screens/Room/Stable/Stable.js
Labels: improvement

#2195 Character in Previews - More Groups
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Icons/CharacterOff.png
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
Labels: improvement

#2186 Improvement/Refactor: Appearance update validation rework
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Validation.js
  BondageClub/index.html
Labels: improvement, refactor

#2251 Bugfix: Removes duplicate properties from Futuristic Harness layers
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2252 Refactor: Removes handling of the unused Restrain property
  BondageClub/Screens/Inventory/ItemHands/PaddedMittens/PaddedMittens.js
  BondageClub/Screens/Inventory/ItemHands/PawMittens/PawMittens.js
  BondageClub/Scripts/Validation.js
Labels: refactor

#2254 assets cleanup/improvement
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/InflatableBodyBag.png
  BondageClub/Assets/Female3DCG/ItemDevices/InflatableBodyBagBloated.png
  BondageClub/Assets/Female3DCG/ItemDevices/InflatableBodyBagInflated.png
  BondageClub/Assets/Female3DCG/ItemDevices/InflatableBodyBagMax.png
  BondageClub/Assets/Female3DCG/ItemLegs/LegBinder_Large_Latex.png
  BondageClub/Assets/Female3DCG/ItemLegs/LegBinder_Normal_Latex.png
  BondageClub/Assets/Female3DCG/ItemLegs/LegBinder_Small_Latex.png
  BondageClub/Assets/Female3DCG/ItemLegs/LegBinder_XLarge_Latex.png
  BondageClub/Assets/Female3DCG/ItemLegs/SeamlessLegBinder_Large.png
  BondageClub/Assets/Female3DCG/ItemLegs/SeamlessLegBinder_Normal.png
  BondageClub/Assets/Female3DCG/ItemLegs/SeamlessLegBinder_Small.png
  BondageClub/Assets/Female3DCG/ItemLegs/SeamlessLegBinder_XLarge.png
Labels: asset, improvement

#2255 Bugfix: Fixes issues with new validation script when run on private room NPCs
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Validation.js
Labels: fix

#2256 added wrapped blanket (all credits go to Ayesha)
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_LargeFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_LargeFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_LargeShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_NormalFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_NormalFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_NormalShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_SmallFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_SmallFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_SmallShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_XLargeFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_XLargeFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/WrappedBlanket_XLargeShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/WrappedBlanket.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_LargeFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_LargeFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_LargeShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_NormalFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_NormalFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_NormalShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_SmallFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_SmallFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_SmallShouldersWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_XLarge.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_XLargeFeetWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_XLargeFullWrapped.png
  BondageClub/Assets/Female3DCG/ItemArms/WrappedBlanket_XLargeShouldersWrapped.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/FeetWrapped.png
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/FullWrapped.png
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/NormalWrapped.png
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/ShouldersWrapped.png
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/WrappedBlanket.js
  BondageClub/index.html
Labels: asset

#2257 Feature: Lock interactions - Combination Padlock
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMisc/CombinationPadlock/CombinationPadlock.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
Labels: feature

#2260 NPC Missing Arousal Settings fix
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/NPC.js
Labels: fix

#2264 Bugfix: Validation typo fixes
  BondageClub/Scripts/Validation.js
Labels: fix

#2266 Bugfix: Cafe hover text rendering underneath Arcade icon
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: fix

#2267 Bugfix: Removes duplicated DefaultColor property
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: fix

#2268 New item: Mouth dildo
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/LargeDildo_Dildo.png
  BondageClub/Assets/Female3DCG/ItemMouth/LargeDildo_Lips.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/LargeDildo.png
Labels: asset
