Repository Ben987/Bondage-College, pull requests merged in 2021-08, with the labels that each got.

#2816 Kinky Dungeon 1.51
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/EnchKnife.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Hammer.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Knife.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Lore.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Pick.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLore.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/MiniGame/KinkyDungeon/Weapons/Axe.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Weapons/Hammer.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Weapons/Sword.png
  BondageClub/index.html
Labels: feature

#2814 [Fix] [Natsuki] the REAL #2811 Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2813 Misc fixes
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Room/Poker/PokerHandValue.js
  BondageClub/Screens/Room/PrivateRansom/Text_PrivateRansom.csv
Labels: fix

#2807 text remove duplicate code, prefetch screens
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Text.js
Labels: improvement

#2818 Cat-Eye Glasses, Antennae, HairBack52
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Glasses/CatGlasses.png
  BondageClub/Assets/Female3DCG/Glasses/CatGlassesBack.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/CatGlasses.png
  BondageClub/Assets/Female3DCG/HairAccessory1/Antennae.png
  BondageClub/Assets/Female3DCG/HairAccessory1/Preview/Antennae.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack52.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack52.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack52.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack52.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#2819 fix empty text missing key warning
  BondageClub/Scripts/Text.js
Labels: fix

#2821 Development improvement: Automatic changelog pregeneration
  BondageClub/Tools/Node/GenerateChangelog.js
  BondageClub/Tools/Node/package-lock.json
  BondageClub/Tools/Node/package.json
Labels: feature

#2822 KinkyDungeon 1.51 fixes
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLore.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/MiniGame/KinkyDungeon/Weapons/Knife.png
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2823 fix remove space in textget keys
  BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
Labels: fix

#2824 Kinky Dungeon 1.52
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLore.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: change

#2825 fix to pass lint check
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
Labels: fix

#2826 Cleanup: Move libraries to common folder
  BondageClub/.eslintrc.json
  BondageClub/Scripts/lib/LZString.d.ts
  BondageClub/Scripts/lib/LZString.js
  BondageClub/Scripts/lib/chess/chess.min.js
  BondageClub/Scripts/lib/chess/chessboard-0.3.0.js
  BondageClub/Scripts/lib/jquery-3.2.1.min.js
  BondageClub/Scripts/lib/socket.io/socket.io.min.js
  BondageClub/Scripts/lib/socket.io/socket.io.min.js.map
  BondageClub/Scripts/lib/three/FBXLoader.js
  BondageClub/Scripts/lib/three/GLTFLoader.js
  BondageClub/Scripts/lib/three/inflate.min.js
  BondageClub/Scripts/lib/three/three.min.js
  BondageClub/Scripts/lib/webgl/resources/m4.js
  BondageClub/Tools/Node/tsconfig-assetcheck.json
  BondageClub/index.html
  BondageClub/jsconfig.json
Labels: refactor

#2827 Misc type fixes
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Stable/Stable.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing3D.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Notification.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/VibratorMode.js
  BondageClub/Scripts/lib/webgl/resources/m4.d.ts
Labels: fix

#2829 Kinky dungeon bugfix + linting
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLore.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
Labels: fix

#2830 Added DrawLocks: false to VacBedDeluxe to fix 404 missing lock asset
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2832 [Fix] [Natsuki] Lint Check Fix
  BondageClub/Screens/Room/Poker/Poker.js
Labels: fix, priority

#2831 [Asset] [Natsuki] Latex collars
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/LatexCollar1.png
  BondageClub/Assets/Female3DCG/ItemNeck/LatexCollar2.png
  BondageClub/Assets/Female3DCG/ItemNeck/LatexCollar2_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/LatexCollar1.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/LatexCollar2.png
Labels: asset

#2833 Lace Armbands & HairFront19 Revamp
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Large_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Large_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Normal_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Normal_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Small_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_Small_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_XLarge_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackBoxTie/LaceBands_XLarge_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Large_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Large_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Normal_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Normal_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Small_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_Small_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_XLarge_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/BackCuffs/LaceBands_XLarge_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Large_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Large_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Normal_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Normal_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Small_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_Small_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_XLarge_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/LaceBands_XLarge_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Large_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Large_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Normal_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Normal_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Small_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_Small_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_XLarge_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/OverTheHead/LaceBands_XLarge_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/Preview/LaceBands.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Large_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Large_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Normal_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Normal_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Small_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_Small_Lace.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_XLarge_Bands.png
  BondageClub/Assets/Female3DCG/Bracelet/Yoked/LaceBands_XLarge_Lace.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairFront/HairFront19.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2834 Futuristic Training Belt Update
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: change, feature, refactor

#2836 Another nipple piercing fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2820 Changelog: R71 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2837 fix non-dismountable fuckmachine
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2838 fix mu emotes
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2839 updated DuctTape ItemArms pet pose action to reflect the item split
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2845 [Asset] Pout Mouth Expression
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Mouth/Pout/Discreet.png
  BondageClub/Assets/Female3DCG/Mouth/Pout/Icon.png
  BondageClub/Assets/Female3DCG/Mouth/Pout/Regular_Inner.png
  BondageClub/Assets/Female3DCG/Mouth/Pout/Regular_Lips.png
Labels: asset

#2841 fixed vulva filling items prerequisites + fixed allowactivepose
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#2843 fixed undefined text for VFXFilter setting
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/Typedef.d.ts
Labels: beta-fix

#2847 Fix kinky dungeon restarting game
  BondageClub/Screens/Room/Arcade/Arcade.js
Labels: beta-fix

#2849 Changelog: R71 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2851 fix old gas mask missing color group
  BondageClub/Assets/Female3DCG/ColorGroups.csv
Labels: beta-fix

#2850 Fix wrong tileset when spectating kinky dungeon
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
Labels: beta-fix

#2853 fix 404s for custom collar tag lock
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2855 Fixed Kinky Dungeon crash when viewing commerce shrine
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
Labels: hotfix

#2857 fix typo in private room dialog 2$50 to $250
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv
Labels: fix

#2858 Fix crash when spectating Kinky Dungeeon
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
Labels: beta-fix

#2859 CommandFriendList text fix
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
Labels: fix

#2846 Bib
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Base.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Cows.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Hearts.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Pacis.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_PawPrints.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Strawberries.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Text.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Trim.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/Bib.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CSS/Styles.css
  BondageClub/Fonts/Pacifico/Pacifico-Regular.ttf
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ClothAccessory/Bib/Bib.js
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p0.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p1.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p2.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p3.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p4.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/p5.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/x0.png
  BondageClub/Screens/Inventory/ClothAccessory/Bib/x1.png
  BondageClub/index.html
Labels: asset

#2852 New Item: Bra Style 4
  BondageClub/Assets/Female3DCG/Bra/Bra10_Large.png
  BondageClub/Assets/Female3DCG/Bra/Bra10_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Bra10_Small.png
  BondageClub/Assets/Female3DCG/Bra/Bra10_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Bra10_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Bra10_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Bra10_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Bra10_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/Bra10.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Bra10_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Bra10_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Bra10_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/Bra10_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2856 Flower Crowns
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/FlowerCrown_MainFlowers.png
  BondageClub/Assets/Female3DCG/Hat/FlowerCrown_Petals.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown_Center.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown_EndFlowers.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown_Leaves.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown_MainFlower.png
  BondageClub/Assets/Female3DCG/Hat/PoppyCrown_SideFlowers.png
  BondageClub/Assets/Female3DCG/Hat/Preview/FlowerCrown.png
  BondageClub/Assets/Female3DCG/Hat/Preview/PoppyCrown.png
  BondageClub/Assets/Female3DCG/Hat/Preview/RoseCrown.png
  BondageClub/Assets/Female3DCG/Hat/RoseCrown_Leaves.png
  BondageClub/Assets/Female3DCG/Hat/RoseCrown_Roses.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2860 Poker Text Fixes
  BondageClub/Screens/Room/Poker/PokerHandValue.js
  BondageClub/Screens/Room/Poker/Sophie/Text_Multiple.csv
  BondageClub/Screens/Room/Poker/Sophie/Text_Single.csv
  BondageClub/Screens/Room/Poker/Text_Poker.csv
Labels: fix

#2861 [Asset Addition] [Natsuki] Tape Mummy Hood Cut-out
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHead/DuctTapeOpen.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/DuctTape/Open.png
Labels: asset

#2844 New Item Face Paint
  BondageClub/Assets/Female3DCG/ClothAccessory/AllFours/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackBoxTie/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackCuffs/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Hogtied/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/TapedHands/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/FacePaint.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/FacePaint.png
  BondageClub/Assets/Female3DCG/Hat/Preview/FacePaint.png
  BondageClub/Assets/Female3DCG/Mask/FacePaint.png
  BondageClub/Assets/Female3DCG/Mask/Preview/FacePaint.png
Labels: asset

#2864 New Item: Pacifier gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/PaciGag_Base.png
  BondageClub/Assets/Female3DCG/ItemMouth/PaciGag_Metal.png
  BondageClub/Assets/Female3DCG/ItemMouth/PaciGag_Straps.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/PaciGag.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2865 Vibrating Clit Egg Update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Kneel/TapedClitEgg.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Kneel/TapedClitEgg_Egg.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/Kneel/TapedClitEgg_Tape.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/TapedClitEgg.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/TapedClitEgg_Egg.png
  BondageClub/Assets/Female3DCG/ItemVulvaPiercings/TapedClitEgg_Tape.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, change

#2866 [Asset improvement] [Natsuki] Lower Cutout for tape
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_LargeCompleteLegs.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_LargeCutOut.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_NormalCutOut.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_SmallCompleteLegs.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_SmallCutOut.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_XLargeCompleteLegs.png
  BondageClub/Assets/Female3DCG/ItemLegs/DuctTape_XLargeCutOut.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/CutOut.png
Labels: asset

#2869 Type Alpha Masks
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix, priority, change

#2870 Misc fixes
  BondageClub/Assets/Female3DCG/ClothAccessory/AllFours/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackBoxTie/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackCuffs/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Hogtied/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/TapedHands/FacePaint.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/FacePaint.png
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
Labels: fix
