Repository Ben987/Bondage-College, pull requests merged in 2021-10, with the labels that each got.

#2996 Small tweaks to #2991
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#1512 AssetGet optimizations
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Introduction/Introduction.js
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
Labels: refactor, optimisation

#3016 Describe the round piercings as not drawing locks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3022 Beta Fix: Revert #2962
  BondageClub/Scripts/GLDraw.js
Labels: beta-fix

#3023 Changelog: R73 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#3026 Changelog: R73 Release
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#3008 New Item: Scissors
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysScissors.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysScissors.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Scissors.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#3032 Fix future chastity belt crash
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Scripts/Inventory.js
Labels: fix
