Repository Ben987/Bondage-College, pull requests merged in 2021-09, with the labels that each got.

#2875 New item: Pig nose
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNose/PigNose_Nose.png
  BondageClub/Assets/Female3DCG/ItemNose/PigNose_Strap.png
  BondageClub/Assets/Female3DCG/ItemNose/Preview/PigNose.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2876 New item: Gag necklace
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Necklace/NecklaceBallGag_Ball.png
  BondageClub/Assets/Female3DCG/Necklace/NecklaceBallGag_Strap.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/NecklaceBallGag.png
Labels: asset

#2877 New items: 2 new panties
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Panties/LatexCrotchlessPanties_Large.png
  BondageClub/Assets/Female3DCG/Panties/LatexCrotchlessPanties_Normal.png
  BondageClub/Assets/Female3DCG/Panties/LatexCrotchlessPanties_Small.png
  BondageClub/Assets/Female3DCG/Panties/LatexCrotchlessPanties_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Preview/LatexCrotchlessPanties.png
  BondageClub/Assets/Female3DCG/Panties/Preview/RedBowPanties.png
  BondageClub/Assets/Female3DCG/Panties/RedBowPanties_Bow.png
  BondageClub/Assets/Female3DCG/Panties/RedBowPanties_Large_Bow.png
  BondageClub/Assets/Female3DCG/Panties/RedBowPanties_Large_Panties.png
  BondageClub/Assets/Female3DCG/Panties/RedBowPanties_Panties.png
Labels: asset

#2874 Center and smoothly zoom chatrooms
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2890 Notifications Fix - Owner entering room
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2891 Asterisks in Chat Message fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2894 Arousal Thermometer Glow position fix
  BondageClub/Scripts/Drawing.js
Labels: fix

#2900 [Adjustment] "Handheld Toys" renamed to "Handheld Items"
  BondageClub/Assets/Female3DCG/Female3DCG.csv
Labels: change

#2895 Fox mask multicolor split
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/FoxyMask.png
  BondageClub/Assets/Female3DCG/ItemHood/FoxyMask_Lower.png
  BondageClub/Assets/Female3DCG/ItemHood/FoxyMask_Upper.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2902 [Asset] Mobile Phone Held Item
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPhone1.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysPhone1.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Phone1.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#2901 Emergancy Fix for the face paint
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix, asset

#2906 Fix: Background color of input elements on Android Chrome
  BondageClub/CSS/Styles.css
Labels: fix

#2880 Removed old eslint disable comment
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2883 Fix: photo popup block crash and infinite loads
  BondageClub/Scripts/Common.js
Labels: fix

#2888 Bugfix: Fixes deaf level calculation when no `Effect` array is present on an asset
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
Labels: refactor, fix

#2889 Feature: Adds an all-in-one `checks` npm script
  BondageClub/Tools/Node/package.json
Labels: feature

#2898 Improvement: extended clothes shortcut for consistency
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: improvement

#2537 Feature: Release submissive from ownership
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Labels: server, feature, on-hold

#2905 Improvement: Accessible Limited Item Icon
  BondageClub/Icons/Previews/AllowedLimited.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
Labels: improvement

#2872 [Improvement] [Natsuki] Economy Ballance
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid.csv
  BondageClub/Screens/Room/Introduction/Introduction.js
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Screens/Room/SlaveMarket/Dialog_NPC_SlaveMarket_Mistress.csv
  BondageClub/Screens/Room/SlaveMarket/SlaveMarket.js
Labels: change

#2878 Online Suitcase Minigame
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/BountySuitcase.png
  BondageClub/Assets/Female3DCG/ItemMisc/BountySuitcaseEmpty.png
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/BountySuitcase.png
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/BountySuitcaseEmpty.png
  BondageClub/Icons/Small/Money.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_Trainer.csv
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: feature

#2881 Techno Collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/TechnoCollar.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_ChokerCollarBase.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_ChokerCollarShine.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_ChokerCollarSides.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_FullCollarBase.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_FullCollarShine.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_FullCollarSides.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_PostureCollarBase.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_PostureCollarShine.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_PostureCollarSides.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_SlenderCollarBase.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_SlenderCollarShine.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_SlenderCollarSides.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_StrictPostureCollarBase.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_StrictPostureCollarShine.png
  BondageClub/Assets/Female3DCG/ItemNeck/TechnoCollar_StrictPostureCollarSides.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/TechnoCollar.js
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/c0.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/c1.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/c2.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/c3.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/c4.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/s0.png
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/s1.png
  BondageClub/index.html
Labels: asset

#2885 Improvement: view blocked categories from chatroom
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
Labels: improvement

#2886 Improvement: Friendlist & beep friendly navigation
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/Commands.js
  BondageClub/Screens/Online/ChatRoom/Text_Commands.csv
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2887 New Item: Doll Box
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/DollBox_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/DollBox_Cover.png
  BondageClub/Assets/Female3DCG/ItemDevices/DollBox_DollText.png
  BondageClub/Assets/Female3DCG/ItemDevices/DollBox_Glass.png
  BondageClub/Assets/Female3DCG/ItemDevices/DollBox_Heart.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/DollBox.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/CSS/Styles.css
  BondageClub/Fonts/Satisfy/LICENSE.txt
  BondageClub/Fonts/Satisfy/Satisfy-Regular.ttf
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
  BondageClub/index.html
Labels: asset

#2893 Improvement: secret beeps
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/FriendList/Text_FriendList.csv
Labels: server, improvement

#2896 Techno helmet
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHood/Preview/TechnoHelmet1.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_ChinStrap.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_HeavilyTintedVisor.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_HelmetMain.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_HelmetSecondary.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_HypnoSpiral.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_LightlyTintedVisor.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_OpaqueVisor.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_Shine.png
  BondageClub/Assets/Female3DCG/ItemHood/TechnoHelmet1_TransparentVisor.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Backgrounds/Backgrounds.js
  BondageClub/Backgrounds/HypnoSpiral2.jpg
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/c0.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/c1.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/d0.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/d1.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/d2.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/d3.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v0.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v1.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v2.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v3.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v4.png
  BondageClub/Screens/Inventory/ItemHood/TechnoHelmet1/v5.png
Labels: asset

#2903 New item: Bandana
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Hat/BandanaCircles_BandPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaCircles_BowPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaFlowers_BandPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaFlowers_BowPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaPolkaDots_BandPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaPolkaDots_BowPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaTriangles_BandPattern.png
  BondageClub/Assets/Female3DCG/Hat/BandanaTriangles_BowPattern.png
  BondageClub/Assets/Female3DCG/Hat/Bandana_Band.png
  BondageClub/Assets/Female3DCG/Hat/Bandana_Bow.png
  BondageClub/Assets/Female3DCG/Hat/Preview/Bandana.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Hat/Bandana/Circles.png
  BondageClub/Screens/Inventory/Hat/Bandana/Dots.png
  BondageClub/Screens/Inventory/Hat/Bandana/Flowers.png
  BondageClub/Screens/Inventory/Hat/Bandana/Plain.png
  BondageClub/Screens/Inventory/Hat/Bandana/Triangles.png
Labels: asset

#2904 Improvement: saved expression previews
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement, change

#2908 New Hairstyles: 10 b variant Back and 2 front
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack10b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack15b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack18b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack19b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack1b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack20b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack2b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack4b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack5b.png
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack6b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack10b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack15b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack18b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack19b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack1b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack20b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack2b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack4b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack5b.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack6b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack10b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack15b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack18b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack19b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack1b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack20b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack2b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack4b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack5b.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack6b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack10b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack15b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack18b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack19b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack1b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack20b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack2b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack4b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack5b.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack6b.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront20.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront21.png
Labels: asset

#2909 fix: polluted modular object properties
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ModularItem.js
Labels: fix

#2910 fix: activities not hiding names in sensdep
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2911 fix: color picker crash & errors
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: fix

#2879 Misc item fixes & tweaks
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Large_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Large_Trim.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Normal_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Normal_Trim.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Small_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Small_Trim.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_XLarge_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_XLarge_Trim.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/Kennel/Kennel.js
Labels: fix, asset

#2882 New items: Hawaiian dress
  BondageClub/Assets/Female3DCG/Bra/CoconutBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/CoconutBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/CoconutBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/CoconutBra_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/CoconutBra.png
  BondageClub/Assets/Female3DCG/ClothLower/HulaSkirt_BackLeaves.png
  BondageClub/Assets/Female3DCG/ClothLower/HulaSkirt_Flowers.png
  BondageClub/Assets/Female3DCG/ClothLower/HulaSkirt_FrontLeaves.png
  BondageClub/Assets/Female3DCG/ClothLower/HulaSkirt_Pollen.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/HulaSkirt.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Necklace/FlowerGarland_Center.png
  BondageClub/Assets/Female3DCG/Necklace/FlowerGarland_Petals.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/FlowerGarland.png
Labels: asset

#2897 Improvement: private labels for rooms in friendlist
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Server.js
Labels: server, improvement

#2907 Minor Text Fix for the Latex Strait Leotard
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset, has-dependencies, change

#2913 Improvement: Modular Item ModuleType
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt0_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt1_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt2_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt3_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt4_Tag.png
  BondageClub/Assets/Female3DCG/ItemNeckAccessories/CustomCollarTagt5_Tag.png
  BondageClub/Screens/Inventory/ItemNeckAccessories/CustomCollarTag/CustomCollarTag.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2914 support banlist for RoomRecreate
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2915 Extended DoubleEndDildo
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemVulva/DoubleEndDildo.png
  BondageClub/Assets/Female3DCG/ItemVulva/DoubleEndDildoLarge.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset, change

#2884 New Item: Tutu
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/Tutu.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2916 Autoban refactor
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
Labels: refactor

#2917 Missing Layer Names and Action Messges changes
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2918 Shock visual effect
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/LoveChastityBelt/LoveChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Drawing.js
Labels: feature

#2919 Screen glow when vibrator is on
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2920 Feature: Improved console warnings
  BondageClub/Scripts/Server.js
Labels: server, improvement

#2921 Feature: Updates Pet Suit to utilise the new `ModuleType` property
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Largez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Largez1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Normalz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Normalz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Smallz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Smallz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_XLargez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_XLargez1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Largez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Largez1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Normalz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Normalz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Smallz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_Smallz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_XLargez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/BitchSuit_XLargez1_Latex.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: refactor, asset

#2923 Fix: I forgot that I made chastity versions
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2924 New Fur items + Alpha mask fix
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/FurStraitJacket.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/FurStraitJacket.png
  BondageClub/Assets/Female3DCG/ItemDevices/FurBlanketWrapBelts_Belts.png
  BondageClub/Assets/Female3DCG/ItemDevices/FurBlanketWrapBelts_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/FurBlanketWrapTight_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/FurBlanketWrap_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/FurBlanketWrapBelts_Belts.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/FurBlanketWrapBelts_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/FurBlanketWrapTight_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/FurBlanketWrap_Blanket.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/FurBlanketWrap.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix, asset

#2926 Fix glasses
  BondageClub/Assets/Female3DCG/Glasses/CatGlasses.png
  BondageClub/Assets/Female3DCG/Glasses/CatGlassesBack.png
  BondageClub/Assets/Female3DCG/Glasses/EyePatch1.png
  BondageClub/Assets/Female3DCG/Glasses/EyePatch1Right.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses1.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses2.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses3.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses4.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses5.png
  BondageClub/Assets/Female3DCG/Glasses/Glasses6.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/CatGlasses.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/EyePatch1.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses1.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses2.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses3.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses4.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses5.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/Glasses6.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/SunGlasses1.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/SunGlasses2.png
  BondageClub/Assets/Female3DCG/Glasses/Preview/SunGlassesClear.png
  BondageClub/Assets/Female3DCG/Glasses/SunGlasses1.png
  BondageClub/Assets/Female3DCG/Glasses/SunGlasses2.png
  BondageClub/Assets/Female3DCG/Glasses/SunGlassesClear.png
Labels: beta-fix

#2930 fix stuck in friendlist
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: beta-fix

#2928 Changelog: R72 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/Icons/Information.svg
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/Tools/Node/GenerateChangelog.js
  BondageClub/changelog.html
Labels: changelog

#2938 Filename casing fix for Grand Mage Dress
  BondageClub/Assets/Female3DCG/Cloth/GrandMage_Large_Trim.png
Labels: beta-fix

#2941 Pacifier gag shop fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2943 removed spiral backgrounds from room options
  BondageClub/Backgrounds/Backgrounds.js
Labels: beta-fix

#2945 Fix formatting error in Dialog_NPC_KidnapLeague_Trainer.csv
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_Trainer.csv
Labels: beta-fix

#2929 Phone handheld items Icon Fix + Phone Variant 2
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPhone2.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysPhone2.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Phone2.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: beta-fix, asset

#2952 [Fix] Handheld Item Name Fix
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: beta-fix

#2948 Dialog Message for Room Blocked Items
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2947 Suitcase minigame rebalance
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Scripts/Struggle.js
Labels: beta-fix

#2946 Fix $ icon over bounty-carrying player
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2954 Fix ChatRoomCarryingBounty
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2953 Add DrawLocks: false to Futuristic Muzzle
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2951 fix wardrobe sending a server sync on every update
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#2949 Pet Suit fixes & tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_Large_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_Normal_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_Small_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuitExposed_XLarge_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Largez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Largez1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Normalz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Normalz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Smallz0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Smallz1_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_Straps.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_XLargez0_Latex.png
  BondageClub/Assets/Female3DCG/ItemArms/AllFours/BitchSuit_XLargez1_Latex.png
Labels: beta-fix

#2944 fix grandmage hogtied pose with small body
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/GrandMage_Small_Base.png
Labels: beta-fix

#2942 missing double ended dildo large image
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemVulva/Kneel/DoubleEndDildo.png
Labels: beta-fix

#2939 fix `CharacterGetCurrent` while in wardrobe
  BondageClub/Scripts/Character.js
Labels: beta-fix

#2937 added missing futuristic muzzle dialog
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2935 fix color picker crash with no item in wardrobe
  BondageClub/Screens/Character/ItemColor/ItemColor.js
Labels: fix

#2933 Feature: Pose mapping
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackBoxTie/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackCuffs/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/BackElbowTouch/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Belt.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Yoked/Tutu_Shine.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Typedef.d.ts
Labels: beta-fix, feature

#2932 Misc Fixes
  BondageClub/Assets/Female3DCG/Cloth/AllFours/StudentOutfit1_Large_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/StudentOutfit1_Normal_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/StudentOutfit1_Small_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/StudentOutfit1_XLarge_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/HOG TEMPLATE.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/StudentOutfit1_Large_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/StudentOutfit1_Normal_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/StudentOutfit1_Small_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/StudentOutfit1_XLarge_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/StudentOutfit1_Large_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/StudentOutfit1_Normal_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/StudentOutfit1_Small_Buckle.png
  BondageClub/Assets/Female3DCG/Cloth/StudentOutfit1_XLarge_Buckle.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Large_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Large_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Normal_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Small_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_Small_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/AdmiralSkirt_XLarge_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Large_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Large_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Normal_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Small_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_Small_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/AdmiralSkirt_XLarge_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Large_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Large_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Normal_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Small_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_Small_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/AdmiralSkirt_XLarge_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Large_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Large_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Normal_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Small_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_Small_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/AdmiralSkirt_XLarge_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Large_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Large_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Normal_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Normal_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Small_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_Small_Stripe.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_XLarge_Cloth.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/AdmiralSkirt_XLarge_Stripe.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/FuckMachine/FuckMachine.js
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/TechnoCollar.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Text.js
  BondageClub/Tools/Node/tsconfig-assetcheck.json
Labels: fix

#2950 Changelog: R72 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2956 fix click on room name while in chatsearch in friends mode
  BondageClub/Screens/Character/FriendList/FriendList.js
Labels: beta-fix

#2959 Bib visual improvement
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Base.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Bib_Trim.png
Labels: asset

#2960 Misc small beta fixes
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2961 Fur blanket tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2966 Bugfix: Modifies Pet Suit to hide gloves
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2967 Fix missing ' crate' in futuristic crate dialogue
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2968 Increase cooldowns on futuristic training belt
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
Labels: change

#2971 Fix 15 minutes duration for suitcase game
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2973 Changelog: R72 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2982 Fix: tutu image updates
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Large_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Large_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Large_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Large_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Normal_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Normal_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Normal_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Normal_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Small_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Small_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Small_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_Small_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_XLarge_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_XLarge_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_XLarge_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/OverTheHead/Tutu_XLarge_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Large_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Large_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Large_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Large_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Normal_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Normal_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Normal_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Normal_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Small_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Small_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Small_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_Small_Layer4.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_XLarge_Layer1.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_XLarge_Layer2.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_XLarge_Layer3.png
  BondageClub/Assets/Female3DCG/ClothLower/Tutu_XLarge_Layer4.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2981 Reword the coiled rope's names for consistency
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: change

#2978 Help kneel maintains upper pose
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2976 Item Chat Message Fixes
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/FullLatexSuit/FullLatexSuit.js
  BondageClub/Screens/Inventory/ItemDevices/DollBox/DollBox.js
Labels: fix

#2974 Handheld Toy - Select Screen Rename
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2984 Fix a crash when using the techno collar shock module
  BondageClub/Screens/Inventory/ItemNeck/TechnoCollar/TechnoCollar.js
Labels: beta-fix

#2986 minor assets fix
  BondageClub/Assets/Female3DCG/ItemMisc/Preview/SafewordPadlock.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuitZip_Large_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuitZip_Normal_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuitZip_Small_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuitZip_XLarge_Base.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuit_Large.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuit_Normal.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuit_Small.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/SeethroughSuit_XLarge.png
Labels: fix

#2985 new item: V glasses
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Glasses/Preview/VGlasses.png
  BondageClub/Assets/Female3DCG/Glasses/VGlasses_Frame.png
  BondageClub/Assets/Female3DCG/Glasses/VGlasses_Glass.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2979 Adds authorization settings to the futuristic vibrator
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: asset, change

#2975 Character fetch for extended clothes refactor
  BondageClub/Screens/Inventory/HairAccessory1/Halo/Halo.js
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
  BondageClub/Scripts/ExtendedItem.js
Labels: refactor

#2927 Made lock picking only take one try when false set pins reset
  BondageClub/Scripts/Struggle.js
Labels: change

#2962 Improvement: tweaked the image retry strategy to not be instantaneous
  BondageClub/Scripts/GLDraw.js
Labels: improvement

#2936 Feature: Updates cyclic block validation to take prerequisites into account
  BondageClub/Scripts/Validation.js
Labels: improvement

#2931 Only include commits from upstream/master in `changelogPrepare` script
  BondageClub/Tools/Node/GenerateChangelog.js
Labels: improvement

#2990 Nursery dialog grammar and wording fixes
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_ABDL1.csv
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_ABDL2.csv
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
Labels: fix, change

#2989 Fix an error in the nursery dialog CSV file
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
Labels: fix

#2977 Apply remove item logic when swapping
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Inventory.js
Labels: fix

#2958 Feature: added lower quality animation settings
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/HairAccessory1/Halo/Halo.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRopeSuspensionHogtied.js
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
  BondageClub/Screens/Inventory/ItemDevices/FuckMachine/FuckMachine.js
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/FuturisticCrate.js
  BondageClub/Screens/Inventory/ItemDevices/Locker/Locker.js
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/VacBedDeluxe.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Scripts/Common.js
Labels: feature

#2934 New Item: Animated steampunk wings
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Wings/Preview/SteampunkWings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings0_Gears.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings0_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings0_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings1_Gears.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings1_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings1_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings2_Gears.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings2_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings2_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings3_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings3_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings4_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings4_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings5_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings5_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings6_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings6_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings7_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings7_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings8_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings8_Wings.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings_Base.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings_Gears.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings_WingFrames.png
  BondageClub/Assets/Female3DCG/Wings/SteampunkWings_Wings.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Wings/SteampunkWings/SteampunkWings.js
  BondageClub/index.html
Labels: asset

#2922 Chat room create rework
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatCreate/Text_ChatCreate.csv
  BondageClub/Screens/Online/ChatCreate/Text_ChatCreate_FR.txt
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement, change

#2993 New Item: Net
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/NetAllFours_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/NetAllFours_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/NetAllFours_WeightsBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/NetAllFours_WeightsFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/NetSuspended_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/NetSuspended_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/NetKneel_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/NetKneel_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/NetKneel_WeightsBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/NetKneel_WeightsFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/Net_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/Net_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/Net_WeightsBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/Net_WeightsFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/Net_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Net_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/Net.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/NetKneel_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/NetKneel_Front.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/NetKneel_WeightsBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/NetKneel_WeightsFront.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Net/AllFours.png
  BondageClub/Screens/Inventory/ItemDevices/Net/Kneel.png
  BondageClub/Screens/Inventory/ItemDevices/Net/Net.png
  BondageClub/Screens/Inventory/ItemDevices/Net/Net_BackWeights.png
  BondageClub/Screens/Inventory/ItemDevices/Net/Net_FrontWeights.png
  BondageClub/Screens/Inventory/ItemDevices/Net/Suspended.png
Labels: asset
