Repository Ben987/Bondage-College, pull requests merged in 2021-02, with the labels that each got.

#2011 Appearance Group buttons - mobile
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2012 Bugfix: Fixed limited permission check for individual spanking toys
  BondageClub/Scripts/Inventory.js
Labels: fix

#2013 Chatroom Toggle Icons
  BondageClub/Icons/Rectangle/Eye0.png
  BondageClub/Icons/Rectangle/Eye1.png
  BondageClub/Icons/Rectangle/Eye2.png
  BondageClub/Icons/Rectangle/Eye3.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
  BondageClub/Scripts/Drawing.js
Labels: feature

#1991 Refactor: Unify Preference Init
  BondageClub/Screens/Character/Creation/Creation.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
Labels: refactor

#2014 Chat Room Camera
  BondageClub/Icons/Rectangle/Camera.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
  BondageClub/Screens/Room/Photographic/Photographic.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Drawing.js
Labels: feature

#2024 Futuristic Collar Permission
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
Labels: asset, improvement

#2023 Futuristic Ball Gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagBall_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagBlink_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagLightBall_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagPlug_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGagPlug_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_Ball.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_BallHighlights.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_Light.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_Lock.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_Mask.png
  BondageClub/Assets/Female3DCG/ItemMouth/FuturisticHarnessBallGag_Straps.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/FuturisticHarnessBallGag.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/index.html
Labels: asset

#2022 Feature/Refactor: Refactors dynamic text drawing into common functions
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/PetBowl/PetBowl.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/NWSE.png
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/SWNE.png
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Screens/Inventory/ItemHood/CanvasHood/CanvasHood.js
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
  BondageClub/Scripts/DynamicDraw.js
  BondageClub/index.html
Labels: feature, refactor

#2021 Futuristic Vibrator
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemVulva/FuturisticVibrator_Band.png
  BondageClub/Assets/Female3DCG/ItemVulva/FuturisticVibrator_Display.png
  BondageClub/Assets/Female3DCG/ItemVulva/FuturisticVibrator_Lock.png
  BondageClub/Assets/Female3DCG/ItemVulva/Kneel/FuturisticVibrator_Band.png
  BondageClub/Assets/Female3DCG/ItemVulva/Kneel/FuturisticVibrator_Display.png
  BondageClub/Assets/Female3DCG/ItemVulva/Kneel/FuturisticVibrator_Lock.png
  BondageClub/Assets/Female3DCG/ItemVulva/LegsClosed/FuturisticVibrator_Band.png
  BondageClub/Assets/Female3DCG/ItemVulva/LegsClosed/FuturisticVibrator_Display.png
  BondageClub/Assets/Female3DCG/ItemVulva/LegsClosed/FuturisticVibrator_Lock.png
  BondageClub/Assets/Female3DCG/ItemVulva/Preview/FuturisticVibrator.png
  BondageClub/Assets/Female3DCG/ItemVulva/VibratingDildo_Dildo.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/VibratorMode.js
  BondageClub/index.html
Labels: asset

#2020 Sensory deprivation messages
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature, fix

#2019 Adds Noise Cancellation to all earphones, and changes name garbling
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemEars/BluetoothEarbuds/NoiseCancelling.png
  BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/HeadphoneEarPlugs.js
  BondageClub/Screens/Inventory/ItemEars/HeadphoneEarPlugs/NoiseCancelling.png
  BondageClub/Screens/Inventory/ItemEars/Headphones/NoiseCancelling.png
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: asset, change, feature

#2033 Bugfix: Ensures that the DrawRun function always gets refreshed properly
  BondageClub/Scripts/Drawing.js
Labels: fix

#2035 Improvement: Chess
  BondageClub/Screens/MiniGame/Chess/OLD/chessAIOLD.js
  BondageClub/Screens/MiniGame/Chess/OLD/chessOLD.js
  BondageClub/Screens/MiniGame/Chess/chess.js
Labels: improvement

#2036 TightJacket Message Fix
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
Labels: fix

#2032 Improvement: Draw empty background
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2031 Improvement: Optional lock assets & custom lock layers
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacketc0a0s0_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacketc0a1s0_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacketc1a0s0_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/HighSecurityStraitJacketc1a1s0_Lock.png
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature, improvement

#2030 Improvement: Don't draw empty text
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2027 Crib Update
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Crib.png
  BondageClub/Assets/Female3DCG/ItemDevices/CribClosed.png
  BondageClub/Assets/Female3DCG/ItemDevices/CribStuffed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_GateClosed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_GateOpen.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_Mattress.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_Pillow.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_PillowTrim.png
  BondageClub/Assets/Female3DCG/ItemDevices/Crib_Plushies.png
  BondageClub/Assets/Female3DCG/ItemDevices/Cribg0p0_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Cribg0p1_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Cribg1p0_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Cribg1p1_Lock.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Crib/Crib.js
  BondageClub/Screens/Inventory/ItemDevices/Crib/Gate.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/Open.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/Plushies.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/Stuffed.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/g0.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/g1.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/p0.png
  BondageClub/Screens/Inventory/ItemDevices/Crib/p1.png
Labels: asset, improvement

#2026 Feature: Updates the Transport Box with opacity and custom text options
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBoxNWSE_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBox_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBox_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBox_Panel.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBox_Wheelholders.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/TransportWoodenBox_Wheels.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/WoodenBoxNWSE_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBoxNWSE_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Back.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Box.png
  BondageClub/Assets/Female3DCG/ItemDevices/TransportWoodenBox_Panel.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenBoxNWSE_Lock.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Inventory/ItemDevices/TransportWoodenBox/NWSE.png
  BondageClub/Screens/Inventory/ItemDevices/TransportWoodenBox/SWNE.png
  BondageClub/Screens/Inventory/ItemDevices/TransportWoodenBox/TransportWoodenBox.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/index.html
Labels: asset, change

#2015 Wardrobe Compresses & Decompresses Properties (FIX)
  BondageClub/Scripts/Character.js
Labels: change

#2025 Improvement: Adds eyes closed expression support to the blackout lenses
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/BlackoutLenses.png
  BondageClub/Assets/Female3DCG/ItemHead/BlackoutLenses_Left.png
  BondageClub/Assets/Female3DCG/ItemHead/BlackoutLenses_Right.png
  BondageClub/Assets/Female3DCG/ItemHead/Closed/BlackoutLenses.png
  BondageClub/Assets/Female3DCG/ItemHead/Closed/BlackoutLenses_Left.png
  BondageClub/Assets/Female3DCG/ItemHead/Closed/BlackoutLenses_Right.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: asset, improvement

#2028 Kigurumi Mask
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Blush1.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Blush2.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Blush3.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Blush4.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Brows1.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Brows2.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Brows3.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Brows4.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Eyes1.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Eyes2.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Eyes3.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Eyes4.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Mask.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Mouth1.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Mouth2.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Mouth3.png
  BondageClub/Assets/Female3DCG/ItemHood/KirugumiMask_Mouth4.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/KirugumiMask.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/KirugumiMask.js
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/b0.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/b1.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/b2.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/b3.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/br0.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/br1.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/br2.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/br3.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/e0.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/e1.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/e2.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/e3.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/m0.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/m1.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/m2.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/m3.png
  BondageClub/index.html
Labels: asset

#2037 Futuristic Straitjacket
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitJacketHandsBackChastity_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitJacketHandsBack_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitJacketHandsFrontChastity_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitJacket_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Display.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_GlovesBack.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_Mesh.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Large_Sides.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_GlovesBack.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_Mesh.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Normal_Sides.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_GlovesBack.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_Mesh.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Small_Sides.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_Gloves.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_GlovesBack.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_Lower.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_Mesh.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_XLarge_Sides.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/FuturisticStraitjacket.png
  BondageClub/Assets/Female3DCG/ItemArms/StraitLeotard_Lock_2.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Large_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Normal_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_Small_Belt.png
  BondageClub/Assets/Female3DCG/ItemPelvis/FuturisticChastityBelt2_XLarge_Belt.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/FuturisticStraitjacket.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/HandsBack.png
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/HandsBackChastity.png
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/HandsFront.png
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/HandsFrontChastity.png
  BondageClub/index.html
Labels: asset

#2038 Wooden Sign Upside-Down
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMisc/Suspension/WoodenSign_Rope.png
  BondageClub/Assets/Female3DCG/ItemMisc/Suspension/WoodenSign_Sign.png
  BondageClub/Assets/Female3DCG/ItemMisc/Suspension/WoodenSign_Text.png
  BondageClub/Screens/Inventory/ItemMisc/WoodenSign/WoodenSign.js
Labels: asset, improvement

#2040 Refactor: ChatRoomDrawCharacter
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: refactor

#2042 Increased sensory deprivation level
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2043 In Sensory deprivation, player names in emotes get replaced with Someone
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2044 Bugfix: Reinstates missing asset for the vibrating dildo
  BondageClub/Assets/Female3DCG/ItemVulva/VibratingDildo_Dildo.png
Labels: fix

#2045 Feature/Refactor: Modular item generalisation and extended item archetypes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/HighSecurityStraitJacket/HighSecurityStraitJacket.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: feature, refactor

#2048 small controller fix for appearance menu
  BondageClub/Scripts/Drawing.js
Labels: fix

#2049 Notifications Enhancements
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Notifications.js
  BondageClub/Scripts/Server.js
  BondageClub/index.html
Labels: feature, improvement

#2050 Photo Blink Fix
  BondageClub/Scripts/Drawing.js
Labels: fix

#2051 Improvement: Removes unneeded uniforms from GLDraw shaders
  BondageClub/Scripts/GLDraw.js
Labels: improvement

#2053 Bugfix: Prevents expression reset from removing lip color
  BondageClub/Scripts/Dialog.js
Labels: fix

#2054 Kigurumi Mask Refactor
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/KirugumiMask.js
  BondageClub/index.html
Labels: asset, refactor

#2056 Bugfix: Several lock-related fixes
  BondageClub/Screens/Inventory/ItemMisc/HighSecurityPadlock/HighSecurityPadlock.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: fix

#2057 Bugfix: DialogHasKey error fix
  BondageClub/Scripts/Dialog.js
Labels: fix

#2041 Futuristic Quality of life changes
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticArmbinder_Lock.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_LargeHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_Large_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_NormalHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_SmallHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_Small_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_XLargeHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/FuturisticHeels_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_LargeHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_Large_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_NormalHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_Normal_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_SmallHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_Small_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_XLargeHeel_Shoes.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/FuturisticHeels_XLarge_Shoes.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness2_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Display2.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Large_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Lock2.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Normal_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_Small_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/FuturisticHarness_XLarge_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Display.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Display2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Large_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Large_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Lock2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Mesh.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Normal_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Normal_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Small_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_Small_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_XLarge_Band.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/FuturisticHarness_XLarge_Band2.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/FuturisticHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/FuturisticHarness2.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/Full.png
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/FuturisticHarness.js
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/Lower.png
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness/Upper.png
  BondageClub/Screens/Inventory/ItemTorso/FuturisticHarness2/FuturisticHarness2.js
  BondageClub/index.html
Labels: asset, improvement

#1951 Changelog: R65 beta 1
  BondageClub/CHANGELOG.md
  BondageClub/CSS/Changelog.css
  BondageClub/Icons/Warning.svg
  BondageClub/changelog.html
Labels: changelog

#2063 Clothes Back/Next Fix
  BondageClub/Scripts/Drawing.js
Labels: beta-fix

#2064 Spatula fixes
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Spatula.png
Labels: beta-fix

#2065 Bugfix: Ensures an extended item's exit function is called on extended item type selection
  BondageClub/Scripts/ExtendedItem.js
Labels: beta-fix

#2066 Bugfix: Fix for disappearing lover/owner locks on relog
  BondageClub/Screens/Character/Login/Login.js
Labels: beta-fix

#2067 Transport Box Exit fix
  BondageClub/Screens/Inventory/ItemDevices/TransportWoodenBox/TransportWoodenBox.js
Labels: beta-fix

#2068 Fix: Mobile landscape MouseX
  BondageClub/Scripts/Drawing.js
  BondageClub/index.html
Labels: beta-fix

#2069 Wardrobe Cancel Button
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix, change

#2070 Futuristic, stimulation, and lock fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/FuturisticStraitjacket.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2071 Bunny Tail Vibe Plug fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2073 Bugfix: Adds missing kneeling assets for the Transport Jacket
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Large_Shorts.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Large_StrapsLegs.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Normal_Shorts.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Normal_StrapsLegs.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Small_Shorts.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_Small_StrapsLegs.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_StripesLegs.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_XLarge_Shorts.png
  BondageClub/Assets/Female3DCG/ItemArms/Kneel/TransportJacket_XLarge_StrapsLegs.png
Labels: asset, beta-fix

#2074 Bugfix: Fixes the click handler for the clit & dildo vibrator belt
  BondageClub/Screens/Inventory/ItemVulva/ClitAndDildoVibratorbelt/ClitAndDildoVibratorbelt.js
Labels: beta-fix

#2072 Futuristic vibrator ignores OOC messages
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: beta-fix

#2076 Bugfix: Ensures lovers can unlock intricate/high security locks
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2077 Futuristic chastity belt dialog
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2078 Lock picking fixes
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2079 Beta Fix: Pet Bed clipping
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Lining.png
Labels: beta-fix

#2080 Hide nipple items on futuristic straitjacket
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2081 Fix: FloorShackes + Pet suit combo
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2082 Bugfix: More disappearing locks
  BondageClub/Scripts/Server.js
Labels: beta-fix

#2084 Fixed Position Assets
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature

#2086 Item Tweak: Pet Bed
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2085 Pet Bed Fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/AllFours/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Hogtied/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/Kneel/PetBed_Lining.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Bed.png
  BondageClub/Assets/Female3DCG/ItemDevices/PetBed_Lining.png
Labels: beta-fix

#2090 Fix: Canvas and element positioning
  BondageClub/CSS/Styles.css
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Element.js
Labels: beta-fix

#2087 Ceiling Rope/Chain changes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Inventory.js
Labels: beta-fix, change

#2075 Changelog Update: R65 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2094 Fix: Zoomed touch position on safari
  BondageClub/Scripts/ColorPicker.js
  BondageClub/index.html
Labels: beta-fix

#2091 Item Tweak: Pet Bed again
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2092 Fixed Assets Up Button fix
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2093 Bugfix: Modular item framework fixes
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/ModularItem.js
Labels: beta-fix

#2095 Item Permissions Colour fix
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix

#2096 Hands Colour Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/CommonDraw.js
Labels: beta-fix

#2099 Fix: Safari element position while zoomed
  BondageClub/Scripts/Element.js
Labels: beta-fix

#2097 Add High Security Lock to Strong Locks
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: beta-fix

#2098 Bugfix: Stops long password lock hints from overflowing
  BondageClub/Screens/Inventory/ItemMisc/PasswordPadlock/PasswordPadlock.js
Labels: beta-fix

#2100 Fix "Disable picking locks on self" forced in hardcore
  BondageClub/Screens/Character/Preference/Preference.js
Labels: beta-fix

#2102 Self Lockpick Fix
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2103 Updated lockpicking intro text
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2104 Main Hall Maid Release fix
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: beta-fix, fix

#2105 Bugfix: Adds a missing AllowType to the Halo in HairAccessory1
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2106 Bugfix: Re-enables removal of assets with the AllowRemoveExclusive property
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix, fix

#2107 Bugfix: Ensures Futuristic Vibrator works with the default triggers on first equip
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: beta-fix

#2108 Bugfix: Removes incorrect LockLayer properties
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2109 Bugfix: Fix for an infinite loop in the shop job
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/Shop/Shop.js
Labels: beta-fix

#2112 Fix: Lover items disappearing if player has no owner
  BondageClub/Scripts/Server.js
Labels: beta-fix

#2111 Changelog update R65 Beta 3
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2113 Bugfix: Fixes a crash in LARP item selection
  BondageClub/Screens/Online/GameLARP/GameLARP.js
Labels: beta-fix

#2114 Shackles Over Head Fix
  BondageClub/Assets/Female3DCG/ItemArms/OverTheHead/WristShackles_Chain.png
Labels: beta-fix

#2115 Changelog Update for R65 Release
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2116 AllFours ItemTorso fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2117 Kneel Button Fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#2118 Bugfix: Futuristic vibrator crash
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Scripts/Element.js
Labels: beta-fix

#2120 Stimulation and lock asset fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacketHandsBackChastity_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacketHandsBack_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacketHandsFrontChastity_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/FuturisticStraitjacket_Lock.png
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2121 Add Edged to AllowEffect of most vibrating toys
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#2122 Bugfix: Prevents the handheld remote from bypassing remote owner rules
  BondageClub/Screens/Room/Shop/Shop.js
  BondageClub/Scripts/Inventory.js
Labels: beta-fix

#2125 Missing SuitLower Names
  BondageClub/Assets/Female3DCG/Female3DCG.csv
Labels: beta-fix

#2127 Bugfix: Stops skill modifiers from overlapping skills in the information sheet
  BondageClub/Screens/Character/InformationSheet/InformationSheet.js
Labels: beta-fix

#2123 Changelog Update: R65 (hopefully) final
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#2130 SuitLower Order Fix
  BondageClub/Assets/Female3DCG/Female3DCG.csv
Labels: fix

#2131 Bugfix: Compatibility fixes for the floor shackles
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Inventory.js
Labels: fix

#2133 Bugfix: Adds some missing dialogue and audio entries
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/Scripts/Audio.js
Labels: fix

#2143 Fix for crash if character with invalid effect enters the chat room
  BondageClub/Scripts/Server.js
Labels: fix

#2140 Futuristic chastity bra no display lock icon
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#2137 Compatibility Patch: Item save format
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Inventory.js
Labels: refactor

#2142 Exit Club Confirm
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/MainHall/Text_MainHall.csv
Labels: change

#2141 Makes futuristic earphones hidden by most hoods
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2139 Rejoin Failed Message
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: improvement

#2136 Gag stimulation messages
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2135 Futuristic Vibrator dialog change
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
Labels: change

#2134 Giving keys is possible when wearing just collar/nonrestraint
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change

#2132 Lockpick Dealer
  BondageClub/Screens/Room/AsylumMeeting/AsylumMeeting.js
  BondageClub/Screens/Room/AsylumMeeting/Dialog_NPC_AsylumMeeting_PatientLeft.csv
Labels: feature

#2126 Pole
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Pole.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/Pole.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Pole/Pole.js
  BondageClub/Screens/Inventory/ItemDevices/Pole/Tied.png
  BondageClub/Screens/Inventory/ItemDevices/Pole/Untied.png
  BondageClub/index.html
Labels: asset

#2124 Front Hairstyle 17
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairFront/HairFront17.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront17b.png
Labels: asset

#2147 New Item: Long Skirt
  BondageClub/Assets/Female3DCG/ClothLower/Kneel/LongSkirt1.png
  BondageClub/Assets/Female3DCG/ClothLower/LongSkirt1.png
  BondageClub/Assets/Female3DCG/ClothLower/Preview/LongSkirt1.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2146 Change: Modifies the difficulties of the cryo capsule & coffin
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
  BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
Labels: asset, change

#2145 Collar no longer needed for futuristic items to be locked out
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: fix

#2119 Refactor: Refactors the crib to use the modular item script
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/Crib/Crib.js
  BondageClub/index.html
Labels: improvement, refactor

#2062 Improvement: AllowModularTypes enhancement
  BondageClub/Scripts/ModularItem.js
Labels: improvement

#2059 Collar Ropes
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/AllFours/CollarRopeShort.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeShort.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Horse/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Kneel/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/KneelingSpread/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Preview/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Preview/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/Preview/CollarRopeShort.png
Labels: asset

#2148 Changes the punishment for calling the maids for help to a timer padlock
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: change

#2061 Chatroom Photo Changes
  BondageClub/Icons/Rectangle/Admin.png
  BondageClub/Icons/Rectangle/Icons0.png
  BondageClub/Icons/Rectangle/Icons1.png
  BondageClub/Icons/Rectangle/Icons2.png
  BondageClub/Icons/Rectangle/Icons3.png
  BondageClub/Icons/Rectangle/Profile.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatBlockItem/ChatBlockItem.js
  BondageClub/Screens/Online/ChatBlockItem/Text_ChatBlockItem.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/ChatSearch/Text_ChatSearch.csv
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
Labels: improvement, refactor

#1990 Two new struggle minigames
  BondageClub/Icons/Struggle/Buckle.png
  BondageClub/Icons/Struggle/Dexterity.png
  BondageClub/Icons/Struggle/Flexibility.png
  BondageClub/Icons/Struggle/Player.png
  BondageClub/Icons/Struggle/Rope.png
  BondageClub/Icons/Struggle/Strength.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ControllerSupport.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Struggle.js
  BondageClub/index.html
Labels: feature

#2047 Improvement: Chatroom admin move
  BondageClub/Icons/Here.png
  BondageClub/Icons/Swap.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Scripts/Dialog.js
Labels: improvement

#2138 Improvement: Item save format
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
Labels: has-dependencies, improvement, refactor, server

#2129 Fix/Refactor: Asset description
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Common.js
  BondageClub/Tools/Node/AssetCheck.js
Labels: improvement, on-hold, refactor

#2052 Feature: Version number
  BondageClub/Icons/Small/Warning.png
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Common.js
  BondageClub/index.html
Labels: feature

#1673 Feature/Change: Stand Up/Kneel down Minigame
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/MiniGame/GetUp/GetUp.js
  BondageClub/Screens/MiniGame/GetUp/Text_GetUp.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Text_ChatRoom.csv
  BondageClub/index.html
Labels: feature

#2158 Feature: Send messages with beeps
  BondageClub/CSS/Styles.css
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: feature
