Repository Ben987/Bondage-College, pull requests merged in 2021-06, with the labels that each got.

#2503 Refactor: Move sturdy leather belts to extended items config
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Inventory/ItemArms/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemFeet/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/Screens/Inventory/ItemLegs/SturdyLeatherBelts/SturdyLeatherBelts.js
  BondageClub/index.html
Labels: refactor

#2517 Refactor: Leather armbinder and straps
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ClothAccessory/LeatherStraps/LeatherStraps.js
  BondageClub/Screens/Inventory/ItemArms/LeatherArmbinder/LeatherArmbinder.js
  BondageClub/index.html
Labels: refactor

#2523 Preserve scroll location in TextAreaChatLog on window resize
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Element.js
Labels: improvement

#2525 assets and tweets
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Large_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Large_Panties.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Normal_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Normal_Panties.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Small_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_Small_Panties.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_XLarge_Flowers.png
  BondageClub/Assets/Female3DCG/Panties/FlowerPanties_XLarge_Panties.png
  BondageClub/Assets/Female3DCG/Panties/Preview/FlowerPanties.png
  BondageClub/Screens/Inventory/ItemArms/Ribbons/Ribbons.js
Labels: asset

#2516 [Asset Improvement Fix] [Natsuki] SpankingToys CleanUp
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBallgag.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilLong.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysRopeCoilShort.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysShockRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysTowel.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysVibeRemote.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysWhipPaddle.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysRopeCoilLong.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysRopeCoilShort.png
Labels: asset, improvement

#2514 [Asset fix] [Natsuki]: Over The Head Visual Fix
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Large_Asian.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Large_Black.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Large_White.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Normal_Asian.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Normal_Black.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Normal_White.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Small_Asian.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Small_Black.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/Small_White.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/XLarge_Asian.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/XLarge_Black.png
  BondageClub/Assets/Female3DCG/BodyUpper/OverTheHead/XLarge_White.png
Labels: asset, fix

#2515 Silk strap bindings (item torso base)
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/SilkStraps.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_LargeDiamond.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_LargeHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_LargeStar.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_LargeWaist.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_NormalDiamond.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_NormalHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_NormalStar.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_NormalWaist.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_SmallDiamond.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_SmallHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_SmallStar.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_SmallWaist.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_XLargeDiamond.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_XLargeHarness.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_XLargeStar.png
  BondageClub/Assets/Female3DCG/ItemTorso/SilkStraps_XLargeWaist.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemTorso/SilkStraps/Crotch.png
  BondageClub/Screens/Inventory/ItemTorso/SilkStraps/Diamond.png
  BondageClub/Screens/Inventory/ItemTorso/SilkStraps/Harness.png
  BondageClub/Screens/Inventory/ItemTorso/SilkStraps/Star.png
  BondageClub/Screens/Inventory/ItemTorso/SilkStraps/Waist.png
Labels: asset

#2520 Refactor: Various arms items to extended configuration
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/CollarCuffs/CollarCuffs.js
  BondageClub/Screens/Inventory/ItemArms/LeatherCuffs/LeatherCuffs.js
  BondageClub/Screens/Inventory/ItemArms/LeatherStraitJacket/LeatherStraitJacket.js
  BondageClub/Screens/Inventory/ItemArms/OrnateCuffs/OrnateCuffs.js
  BondageClub/Screens/Inventory/ItemArms/StraitJacket/StraitJacket.js
  BondageClub/Screens/Inventory/ItemArms/WristShackles/WristShackles.js
  BondageClub/index.html
Labels: refactor

#2527 Change: small changes to alpha masks of two items
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: change

#2519 Extended items documentation & fixes
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/VibratorMode.js
Labels: fix

#2526 Improvement/Fix: Asset check update for extended items
  BondageClub/Scripts/Common.js
  BondageClub/Tools/Node/AssetCheck.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/Tools/Node/jsconfig.json
Labels: improvement

#2529 Improvement: Clientside GetAllowItem
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2528 Improvement: Drawing optimisations
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2530 Fix: Correct some wrongly hidden items on the short pencil skirt
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2524 Refactor: Duct tape on arms
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/DuctTape/DuctTape.js
  BondageClub/index.html
Labels: refactor

#2297 queue and await AccountUpdate, reduce emit calls
  BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Title/Title.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Room/InfiltrationPerks/InfiltrationPerks.js
  BondageClub/Screens/Room/LARP/LARP.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Server.js
Labels: improvement, on-hold, refactor

#2531 fix sync reset test
  BondageClub/Scripts/Server.js
Labels: fix

#2532 Animation Quality Preference
  BondageClub/Screens/Character/ItemColor/ItemColor.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/HairAccessory1/Halo/Halo.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRopeSuspensionHogtied.js
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
  BondageClub/Screens/Inventory/ItemDevices/Locker/Locker.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2533 fix credit over scroll
  BondageClub/Screens/Character/Login/Login.js
Labels: fix

#2539 fix and simplify LoginCreditsPosition check
  BondageClub/Screens/Character/Login/Login.js
Labels: fix

#2536 Refactor: Zipties to extended item config
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/Zipties/Zipties.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/index.html
Labels: refactor

#2538 Refactor: Collar ropes into layers
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeLong.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeLong_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeLong_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeMedium.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeMedium_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeMedium_Rope.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeShort.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeShort_Plate.png
  BondageClub/Assets/Female3DCG/ItemNeckRestraints/CollarRopeShort_Rope.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: refactor

#2542 Refactor: Various arm items
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/MermaidSuit/MermaidSuit.js
  BondageClub/Screens/Inventory/ItemArms/Ribbons/Ribbons.js
  BondageClub/Screens/Inventory/ItemArms/TightJacket/TightJacket.js
  BondageClub/Screens/Inventory/ItemArms/TightJacketCrotch/TightJacketCrotch.js
  BondageClub/Screens/Inventory/ItemArms/WrappedBlanket/WrappedBlanket.js
  BondageClub/index.html
Labels: refactor

#2543 Add files for Warning Sign "Wet Floor"
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/WetFloor.png
  BondageClub/Assets/Female3DCG/ItemDevices/WetFloor_Sign.png
  BondageClub/Assets/Female3DCG/ItemDevices/WetFloor_Text.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#2545 Reconfiguring blackout lenses to not hide mask or glasses
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, improvement

#2546 summer dress tweeting
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2549 Bugfix: Crash after calling the maids from a chatroom
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2552 [Asset] [Natsuki]: Clear Vacbed
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/VacbedClear.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacbedClear_Large.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacbedClear_Normal.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacbedClear_Small.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacbedClear_XLarge.png
Labels: asset

#2548 Feature: Hide item based on attribute
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Tools/Node/AssetCheck_Types.js
Labels: feature

#2551 Vacuum Bed Deluxe
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsDownLegsTogether_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsDownLegsTogether_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsDownLegsTogether_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsUpLegsTogether_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsUpLegsTogether_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxeArmsUpLegsTogether_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_LargeArmsDownLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_LargeArmsDownLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_LargeArmsUpLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_LargeArmsUpLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_NormalArmsDownLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_NormalArmsDownLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_NormalArmsUpLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_NormalArmsUpLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_SmallArmsDownLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_SmallArmsDownLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_SmallArmsUpLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_SmallArmsUpLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_XLargeArmsDownLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_XLargeArmsDownLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_XLargeArmsUpLegsTogether_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/LegsClosed/VacBedDeluxe_XLargeArmsUpLegsTogether_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Large_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Large_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Normal_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Normal_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Small_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_Small_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_XLarge_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/VacBedDeluxe_XLarge_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxeArmsUpLegsSpread_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxeArmsUpLegsSpread_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxeArmsUpLegsSpread_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_LargeArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_LargeArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_NormalArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_NormalArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_SmallArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_SmallArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_XLargeArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/Yoked/VacBedDeluxe_XLargeArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/ArmsDownLegsSpread.png
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/ArmsDownLegsTogether.png
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/ArmsUpLegsSpread.png
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/ArmsUpLegsTogether.png
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/VacBedDeluxe.js
  BondageClub/index.html
Labels: asset

#2550 Changelog: R69 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/changelog.html
Labels: changelog

#2555 Missing preview image for vacbed deluxe
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/VacBedDeluxe.png
Labels: fix

#2558 Kinky Dungeon Spectator Fix
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2556 Bugfix: Error thrown when inspecting the Bondage Bench
  BondageClub/Scripts/Dialog.js
Labels: fix

#2559 Bugfix: Reinstates accidentally removed extended script for web
  BondageClub/index.html
Labels: beta-fix

#2560 Bugfix: Prevents `HideItem` declarations from being short-circuited
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix

#2561 Multiple Vacuum Bed Deluxe Fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxeArmsUpLegsSpread_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxeArmsUpLegsSpread_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxeArmsUpLegsSpread_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_LargeArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_LargeArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Large_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Large_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_NormalArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_NormalArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Normal_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Normal_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_SheetBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_SheetFront.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_SmallArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_SmallArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Small_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_Small_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_XLargeArmsUpLegsSpread_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_XLargeArmsUpLegsSpread_Upper.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_XLarge_Lower.png
  BondageClub/Assets/Female3DCG/ItemDevices/BaseLower/VacBedDeluxe_XLarge_Upper.png
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/VacBedDeluxe.js
Labels: beta-fix

#2562 Bugfix: Reinstates accidentally deleted sturdy leather belt configuration
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: beta-fix

#2563 Adds a few keywords to the auto shock blacklist
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
Labels: improvement

#2564 Revert "Modified Hand Mask"
  BondageClub/Assets/Female3DCG/Hands/Default_Asian.png
  BondageClub/Assets/Female3DCG/Hands/Default_Black.png
  BondageClub/Assets/Female3DCG/Hands/Default_White.png
Labels: beta-fix

#2567 Bugfix: Prevents difficulty from increasing when sending single item updates
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Inventory.js
Labels: fix

#2570 Extended Item Type Permissions on Extreme Difficulty
  BondageClub/Scripts/ExtendedItem.js
Labels: fix

#2566 Fix kinky dungeon persistence
  BondageClub/Screens/Room/Arcade/Arcade.js
  BondageClub/Scripts/Dialog.js
Labels: beta-fix

#2565 Changelog: R69 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2568 Cleanup: Vacuum Bed Deluxe code
  BondageClub/Screens/Inventory/ItemDevices/VacBedDeluxe/VacBedDeluxe.js
Labels: beta-fix, refactor

#2577 tweaking fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#2580 Fix: Dental gag cannot be changed when locked
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: beta-fix

#2583 Bugfix: Typo fixes
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
  BondageClub/Screens/Character/Player/Dialog_Player_RU.txt
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/ChatRoom/Dialog_Online_DE.txt
  BondageClub/Screens/Online/ChatRoom/Dialog_Online_RU.txt
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse.csv
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse_DE.txt
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse_RU.txt
Labels: fix

#2584 Bugfix: Adjusts alpha masks & `Hide` entries on the seamless open crotch strait dress
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, fix

#2579 Changelog: R69 Beta 3/Release
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#2592 Hotfix: Fix crash in `AsylumEntrancePlayerJacket`
  BondageClub/Screens/Room/AsylumEntrance/AsylumEntrance.js
Labels: hotfix

#2586 Betafix: Ceiling Shackles: Suspension+Overhead combo
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShacklesOverhead_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_LargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_LargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Large_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_NormalOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_NormalOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Normal_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_SmallOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_SmallOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Small_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_XLargeOverhead_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_XLargeOverhead_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_XLarge_Chain.png
  BondageClub/Assets/Female3DCG/ItemArms/CeilingShackles_XLarge_Cuffs.png
Labels: hotfix

#2593 Bugfix: Adds a null check to extended item `ChangeWhenLocked` checks
  BondageClub/Scripts/ExtendedItem.js
Labels: hotfix

#2605 Bugfix: Fixes collar cuffs chatroom dialogue key
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2604 Club slave dialog leave fix
  BondageClub/Screens/Room/Management/Dialog_NPC_Management_RandomGirl.csv
Labels: fix

#2603 added drawlocks to clitring
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2601 Dizzy Eye Cutoff
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes1.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes10.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes11.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes12.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes13.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes2.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes3.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes4.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes5.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes6.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes7.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes8.png
  BondageClub/Assets/Female3DCG/Eyes/Dizzy/Eyes9.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes1.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes10.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes11.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes12.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes13.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes2.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes3.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes4.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes5.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes6.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes7.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes8.png
  BondageClub/Assets/Female3DCG/Eyes2/Dizzy/Eyes9.png
Labels: fix

#2598 Bugfix: Fixes incorrect gas mask rebreather layer name
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: fix

#2595 Bugfix: Prevents false lock modification warning messages in the console
  BondageClub/Scripts/Validation.js
Labels: fix

#2600 Allow CeilingChain to be lockable
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2599 Save input text when relogging in chat rooms.
  BondageClub/Screens/Character/Relog/Relog.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Server.js
Labels: improvement

#2588 [New Hair]- Style 46
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairBack/AllFours/HairBack51.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack51.png
  BondageClub/Assets/Female3DCG/HairBack/Hogtied/HairBack51.png
  BondageClub/Assets/Female3DCG/HairBack/Suspension/HairBack51.png
Labels: asset

#2582 re-doing the images of the prison gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/PrisonLockdownGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/PrisonLockdownGag_Belts.png
  BondageClub/Assets/Female3DCG/ItemMouth/PrisonLockdownGag_Mask.png
  BondageClub/Assets/Female3DCG/ItemMouth/PrisonLockdownGag_Straps.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, improvement

#2573 Bed Position
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2585 Strait Leotard Layer Priority Change
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset, change

#2587 Strait Leotard Extended
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/cl0.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/cl1.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/co0.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/co1.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/np0.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/np1.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/vp0.png
  BondageClub/Screens/Inventory/ItemArms/StraitLeotard/vp1.png
Labels: asset, change, has-dependencies

#2597 Feature: Extended modular item property support
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/ModularItem.js
Labels: feature

#2602 Kigurumi Mask New Functionality and Options
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/ms0.png
  BondageClub/Screens/Inventory/ItemHood/KirugumiMask/ms1.png
Labels: asset, change, has-dependencies

#2590 Advanced Denial Modes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/VibratorMode.js
Labels: change, feature

#2596 Item Expression Trigger Preference
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarShockUnit/CollarShockUnit.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/SciFiPleasurePanties/SciFiPleasurePanties.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature, fix

#2581 Quick add owner and/or lovers to chat room admins list
  BondageClub/Screens/Online/ChatAdmin/ChatAdmin.js
  BondageClub/Screens/Online/ChatAdmin/Text_ChatAdmin.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: feature

#2608 fix for 404 on PigNoseHook_Lock.jpg
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2612 Notifications Friend Join fix
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2616 New asset: Full latex bra
  BondageClub/Assets/Female3DCG/Bra/FullLatexBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/FullLatexBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/FullLatexBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/FullLatexBra_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FullLatexBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FullLatexBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FullLatexBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/Hogtied/FullLatexBra_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Preview/FullLatexBra.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FullLatexBra_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FullLatexBra_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FullLatexBra_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/FullLatexBra_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#2613 minor grammatical fixes to LoveChastityBelt EN texts
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: fix

#2617 hide anklets with wedding dresses
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#2607 [Asset][Natsuki] Nylon Collar
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemNeck/NylonCollar.png
  BondageClub/Assets/Female3DCG/ItemNeck/NylonCollar_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/NylonCollar.png
Labels: asset

#2609 Adds audio to training belt
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Audio/Vibrator_Advanced_End.mp3
  BondageClub/Audio/Vibrator_Advanced_HighEdge.mp3
  BondageClub/Audio/Vibrator_Advanced_LowEdge.mp3
  BondageClub/Audio/Vibrator_Advanced_LowTease.mp3
  BondageClub/Audio/Vibrator_Advanced_MediumEdge.mp3
  BondageClub/Audio/Vibrator_Advanced_MediumTease.mp3
  BondageClub/Audio/Vibrator_Advanced_Strong.mp3
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Scripts/Audio.js
Labels: feature

#2610 Advanced Vibrator Modes Disable
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Scripts/Validation.js
  BondageClub/Scripts/VibratorMode.js
Labels: feature

#2611 fix light/dark 2 mobile
  BondageClub/CSS/Styles.css
Labels: fix

#2614 suspension cuffs
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/SuspensionCuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/SuspensionCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/SuspensionCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemFeet/SuspensionCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/SuspensionCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/SuspensionCuffs_XLarge.png
Labels: asset

#2615 Fix floating cushion
  BondageClub/Screens/Inventory/ItemDevices/Cushion/Cushion.js
Labels: fix

#2618 Feature: Block cycle validation
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Graph.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
  BondageClub/index.html
Labels: feature, fix

#2620 Futuristic Crate
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrateSmallWindow_Glass.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrateWindow_Glass.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Body.pdn
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Body.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Display.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Frame.pdn
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Frame.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid_Closed.pdn
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid_Closed.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid_SmallWindow.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lid_Window.png
  BondageClub/Assets/Female3DCG/ItemDevices/FuturisticCrate_Lock.png
  BondageClub/Assets/Female3DCG/ItemDevices/Preview/FuturisticCrate.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/Closed.png
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/FuturisticCrate.js
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/Open.png
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/SmallWindow.png
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/Window.png
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Tools/Node/AssetCheck_Types.js
  BondageClub/index.html
Labels: asset

#2621 Fix/Cleanup: Many small asset fixes
  BondageClub/Assets/Female3DCG/Bra/Hogtied/Camisole_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CuteBikini1_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CuteBikini1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CuteBikini1_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/CuteBikini1_XLarge.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/SexyBikini1_Large.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/SexyBikini1_Normal.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/SexyBikini1_Small.png
  BondageClub/Assets/Female3DCG/Bra/Yoked/SexyBikini1_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CorsetShirt_Large .png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/AllFours/CorsetShirt_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CorsetShirt_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/CorsetShirt_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CorsetShirt_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/CorsetShirt_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CorsetShirt_Large.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/CorsetShirt_Xlarge.png
  BondageClub/Assets/Female3DCG/Cloth/CorsetShirt_Large.png
  BondageClub/Assets/Female3DCG/Cloth/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/CorsetShirt_XLarge.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CorsetShirt_Large.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CorsetShirt_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CorsetShirt_Small.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/CorsetShirt_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/TennisSkirt1_XLarge.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/Pajama1_Large.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/Pajama1_Normal.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/Pajama1_Small.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/Pajama1_XLarge.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Hat/PoliceWomanHat.png
  BondageClub/Assets/Female3DCG/Hat/Suspension/PoliceWomanHat.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemArms/MetalCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercingWeightedChain_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercingWeighted_Lock.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_LargeWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_LargeWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_NormalWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_NormalWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_SmallWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_SmallWeightedChain.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_XLargeWeighted.png
  BondageClub/Assets/Female3DCG/ItemNipplesPiercings/AllFours/RoundPiercing_XLargeWeightedChain.png
  BondageClub/Assets/Female3DCG/Suit/BackElbowTouch/PilotSuit_Large.png
  BondageClub/Assets/Female3DCG/Suit/BackElbowTouch/PilotSuit_Normal.png
  BondageClub/Assets/Female3DCG/Suit/BackElbowTouch/PilotSuit_Small.png
  BondageClub/Assets/Female3DCG/Suit/BackElbowTouch/PilotSuit_Xlarge.png
Labels: fix

#2622 Asset Check Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Audio.js
Labels: fix

#2591 Add support for MU* style poses
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2574 Fix pink orgasm filter + refactor chat room drawing
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix, refactor

#2572 Character In Previews Setting
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2571 Improvement: Admin icon asset
  BondageClub/Icons/Small/Admin.png
Labels: improvement

#2569 Allow permission setting for strong locks on Extreme difficulty
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
Labels: change

#2630 New Serving Tray options
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayCake_Details.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayCake_Objects.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayCake_Tray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayCookies_Objects.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayCookies_Tray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayDrinks_Details.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayDrinks_Objects.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayDrinks_Tray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayToys_Details.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayToys_Objects.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTrayToys_Tray.png
  BondageClub/Assets/Female3DCG/ItemMisc/ServingTray_Tray.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Cake.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Cookies.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Drinks.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Empty.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Full.png
  BondageClub/Screens/Inventory/ItemMisc/ServingTray/Toys.png
Labels: asset

#2638 Nurse Uniform OverTheHead pose fix
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/NurseUniform_Large.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/NurseUniform_Normal.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/NurseUniform_Small.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/NurseUniform_XLarge.png
Labels: asset

#2636 creation length validation
  BondageClub/Screens/Character/Creation/Creation.js
  BondageClub/Screens/Character/Creation/Text_Creation.csv
Labels: improvement

#2635 creation crash
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: fix, priority

#2632 Feature: Chat font size preference
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#2634 Added favorite colors to color picker
  BondageClub/Icons/Save.png
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Player/Dialog_Player_DE.txt
  BondageClub/Screens/Character/Player/Dialog_Player_FR.txt
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#2631 turning chat /afk into a toggle on or off
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement

#2633 Hide Icon State Persistence
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: improvement

#2627 Bugfix: Cafe item fixes
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Scripts/TypedItem.js
Labels: fix

#2629 Garters
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Garters/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/GarterBelt_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/Horse/GarterBelt_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/Kneel/GarterBelt_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/KneelingSpread/GarterBelt_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/LegsClosed/GarterBelt_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Preview/GarterBelt.png
  BondageClub/Assets/Female3DCG/Garters/Preview/GarterBelt2.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt2_Large.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt2_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt2_Small.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt2_XLarge.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt_Large.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt_Normal.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt_Small.png
  BondageClub/Assets/Female3DCG/Garters/Spread/GarterBelt_XLarge.png
Labels: asset

#2628 cane/crop gags
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/CaneGag_Cane.png
  BondageClub/Assets/Female3DCG/ItemMouth/CaneGag_Mouth.png
  BondageClub/Assets/Female3DCG/ItemMouth/CropGag_Crop.png
  BondageClub/Assets/Female3DCG/ItemMouth/CropGag_Mouth.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/CaneGag.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/CropGag.png
Labels: asset

#2624 broom item
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysBroom.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysBroom.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/Broom.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#2625 wardrobe info
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Appearance/Text_Appearance.csv
Labels: improvement

#2623 Bugfix: Crash during ChatRoomCharacterItemUpdate
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#2575 Disable Examine While Blind only works outside of the virtual realm
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: change, has-dependencies

#2576 Immersion refactor + only show adjacent players while partly blind
  BondageClub/Icons/CheckLocked.png
  BondageClub/Icons/CheckUnlocked.png
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Drawing.js
Labels: feature, has-dependencies, refactor

#2626 Feature: Allows `DefaultColor` to be set in an item's `Property`
  BondageClub/Scripts/CommonDraw.js
Labels: feature

#2640 DrawTextFit Optimisation
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
  BondageClub/Scripts/Drawing.js
Labels: improvement

#2639 Miscellaneous color picking fixes
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#2619 Inventory favorites
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Screens/MiniGame/Kidnap/Kidnap.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature, fix, server

#2637 Feature: Typed item API improvements
  BondageClub/Screens/Inventory/ItemArms/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticArmbinder/FuturisticArmbinder.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
  BondageClub/Screens/Inventory/ItemArms/FuturisticStraitjacket/FuturisticStraitjacket.js
  BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels/FuturisticHeels.js
  BondageClub/Screens/Inventory/ItemBoots/FuturisticHeels2/FuturisticHeels2.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra2/FuturisticBra2.js
  BondageClub/Screens/Inventory/ItemDevices/Coffin/Coffin.js
  BondageClub/Screens/Inventory/ItemDevices/CryoCapsule/CryoCapsule.js
  BondageClub/Screens/Inventory/ItemDevices/FuturisticCrate/FuturisticCrate.js
  BondageClub/Screens/Inventory/ItemFeet/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemFeet/FuturisticAnkleCuffs/FuturisticAnkleCuffs.js
  BondageClub/Screens/Inventory/ItemHands/FuturisticMittens/FuturisticMittens.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVRHeadset/InteractiveVRHeadset.js
  BondageClub/Screens/Inventory/ItemHead/InteractiveVisor/InteractiveVisor.js
  BondageClub/Screens/Inventory/ItemLegs/Chains/Chains.js
  BondageClub/Screens/Inventory/ItemLegs/DuctTape/DuctTape.js
  BondageClub/Screens/Inventory/ItemLegs/FuturisticLegCuffs/FuturisticLegCuffs.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessPanelGag/FuturisticHarnessPanelGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/FuturisticCollar/FuturisticCollar.js
  BondageClub/Screens/Inventory/ItemNose/NoseRing/NoseRing.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticChastityBelt/FuturisticChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/MetalChastityBelt/MetalChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/OrnateChastityBelt/OrnateChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/PolishedChastityBelt/PolishedChastityBelt.js
  BondageClub/Screens/Inventory/ItemPelvis/StuddedChastityBelt/StuddedChastityBelt.js
  BondageClub/Screens/Inventory/ItemVulvaPiercings/ClitRing/ClitRing.js
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement, refactor

#2644 auto shock unit fixes
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeckAccessories/CollarAutoShockUnit/CollarAutoShockUnit.js
Labels: fix

#2646 missing dialogs
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/FuturisticCuffs/FuturisticCuffs.js
Labels: fix

#2648 Fix/Improvement: Many small fixes, documentation and formatting
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Audio.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/ColorPicker.js
  BondageClub/Scripts/Common.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/DynamicDraw.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/GameLog.js
  BondageClub/Scripts/Graph.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Reputation.js
  BondageClub/Scripts/Skill.js
  BondageClub/Scripts/Speech.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
  BondageClub/Scripts/VibratorMode.js
  BondageClub/index.html
Labels: fix, improvement
