Repository Ben987/Bondage-College, pull requests merged in 2022-02, with the labels that each got.

#3208 [Fix] Emote Edge Artifacting Fix
  BondageClub/Assets/Female3DCG/Emoticon/Confusion/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/Confusion/Icon.png
  BondageClub/Assets/Female3DCG/Emoticon/Hearing/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/Hearing/Icon.png
  BondageClub/Assets/Female3DCG/Emoticon/Read/Emoticon.png
  BondageClub/Assets/Female3DCG/Emoticon/Read/Icon.png
Labels: fix

#3199 Simplify online game status
  BondageClub/Screens/MiniGame/MagicBattle/MagicBattle.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/Game/OnlineGame.js
  BondageClub/Screens/Online/GameLARP/GameLARP.js
  BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
  BondageClub/Screens/Room/AsylumGGTS/AsylumGGTS.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#3215 [Change/Asset] Kitty Blindfold Remaster
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHead/KittyBlindfold.png
  BondageClub/Assets/Female3DCG/ItemHead/KittyBlindfold_Base.png
  BondageClub/Assets/Female3DCG/ItemHead/KittyBlindfold_Ears.png
  BondageClub/Assets/Female3DCG/ItemHead/KittyBlindfold_Eyes.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/KittyBlindfold.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset, change

#3196 More online menu changes
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
  BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
  BondageClub/Screens/Room/AsylumGGTS/AsylumGGTS.js
  BondageClub/Screens/Room/AsylumTherapy/AsylumTherapy.js
  BondageClub/Screens/Room/CollegeEntrance/CollegeEntrance.js
  BondageClub/Screens/Room/KidnapLeague/KidnapLeague.js
  BondageClub/Screens/Room/LARP/LARP.js
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Screens/Room/Nursery/Nursery.js
  BondageClub/Screens/Room/Photographic/Photographic.js
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Typedef.d.ts
Labels: refactor, change

#3227 Kinky Dungeon Update
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/DarkShroud.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/DarkShroudHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonBuffs.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSpawns.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTraps.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: beta-fix

#3233 Changelog: R77 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#3237 Empty Chatroom Data bug
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: beta-fix

#3236 Add two missing layer names for the futuristic cuffs
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix

#3235 Fix the witch skirt
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/MageSkirt_Skirt.png
  BondageClub/Assets/Female3DCG/ClothLower/KneelingSpread/MageSkirt_Waist.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix

#3234 Really fix the Reverse Bunny Suit
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/SuitLower/Spread/ReverseBunnySuit_Large.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/ReverseBunnySuit_Normal.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/ReverseBunnySuit_Small.png
  BondageClub/Assets/Female3DCG/SuitLower/Spread/ReverseBunnySuit_XLarge.png
Labels: beta-fix

#3245 Changelog: R77
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#3232 New Rope Necklaces and Tattoo Chokers
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Necklace/ChokerTattoo.png
  BondageClub/Assets/Female3DCG/Necklace/ChokerTattooFlowers.png
  BondageClub/Assets/Female3DCG/Necklace/NecklaceRope.png
  BondageClub/Assets/Female3DCG/Necklace/NecklaceRopeLong.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/ChokerTattoo.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/NecklaceRope.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Necklace/ChokerTattoo/Flowers.png
  BondageClub/Screens/Inventory/Necklace/ChokerTattoo/Loops.png
  BondageClub/Screens/Inventory/Necklace/NecklaceRope/Long.png
  BondageClub/Screens/Inventory/Necklace/NecklaceRope/Short.png
Labels: asset

#3238 Update ceiling rope
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemAddon/CeilingRope_Ring.png
  BondageClub/Assets/Female3DCG/ItemAddon/CeilingRope_Ropes.png
Labels: asset, change

#3247 Bugfix: Fixes max length variable reference in the Transport Jacket script
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
Labels: fix
