Repository Ben987/Bondage-College, pull requests merged in 2022-03, with the labels that each got.

#3241 Fix a couple of bugs in Stables
  BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Pony.csv
  BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Trainer.csv
  BondageClub/Screens/Room/Stable/Stable.js
Labels: fix

#3261 Maid room fix (serving drinks)
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid_DE.txt
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
  BondageClub/Screens/Room/MainHall/MainHall.js
Labels: fix

#3262 Clothes NoFeetSpreader Prerequisite Fix
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Inventory.js
Labels: fix

#3267 Drone mask fixes
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHead/DroneMask/s0.png
  BondageClub/Screens/Inventory/ItemHead/DroneMask/s1.png
Labels: beta-fix

#3268 Slim Latex Leotard Missing Asset Fix
  BondageClub/Assets/Female3DCG/Suit/SleevelessSlimLatexLeotard_Large_BreastShade.png
  BondageClub/Assets/Female3DCG/Suit/SleevelessSlimLatexLeotard_Large_Latex.png
  BondageClub/Assets/Female3DCG/Suit/SleevelessSlimLatexLeotard_Large_Shine.png
Labels: beta-fix

#3269 Half shaved hairstyle Asset Fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairFront/HairFront22.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22_Base.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22_Fluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22_FrontFluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_Base.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_Fluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_FrontFluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23_Base.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23_Fluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23_FrontFluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b_Base.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b_Fluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b_FrontFluff.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix

#3270 Fix cafe maid removing the player's multi-layered gags
  BondageClub/Screens/Room/Cafe/Cafe.js
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv
Labels: fix

#3271 Fix positioning of the steel ankle cuffs
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/LegsClosed/SteelAnkleCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Large.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Normal.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Small.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_XLarge.png
  BondageClub/Assets/Female3DCG/ItemFeet/Spread/SteelAnkleCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Chain.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemFeet/SteelAnkleCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemLegs/SteelLegCuffs_Chain.png
Labels: fix

#3275 Allow Activity on extended types
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature
