Repository Ben987/Bondage-College, pull requests merged in 2022-01, with the labels that each got.

#3167 Room Recreate Loop Fix
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: fix

#3168 Leashing Mechanic for Kinky Dungeon
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: feature

#3169 Kinky dungeon 2.2
  BondageClub/Screens/MiniGame/KinkyDungeon/Bind.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Bomb.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BombHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Crackle.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/CrackleHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/CrackleTrail.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/CrackleTrailHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Dagger.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/DaggerHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Fireball_2.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Incinerate.pdn
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Incinerate.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/IncinerateHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Freeze.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Stun.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: change

#3171 Activity Null Check Fix
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: fix

#3170 Kinky Dungeon Pre-Beta fixes/changes
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BanditBola.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BanditBolaHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BanditBoltaHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Fireball.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Bind.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Freeze.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Slow.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Sneak.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Stun.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Bandit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/BanditHunter.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Bramble.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Slime.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/SmallSlime.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/VinePlant.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Brickwork.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Chest.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/ChestOpen.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Doodad.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Door.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/DoorOpen.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Floor.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Ghost.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Grate.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Orb.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/OrbEmpty.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Rubble.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/RubbleLooted.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Shrine.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/ShrineBroken.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/StairsDown.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/StairsUp.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Trap.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Wall.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonBuffs.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEvents.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTraps.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/index.html
Labels: beta-fix

#3173 Kinky Dungeon Saving
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: feature

#3174 Kinky dungeon 2.31
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
Labels: fix

#3175 Changelog: R76 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#3176 Revert accidental changes to VibratorMode.js
  BondageClub/Scripts/VibratorMode.js
Labels: beta-fix

#3178 Kinkiest dungeon 2.32
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/Guard.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor0/Bars.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor0/Bed.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Bars.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor1/Bed.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor11/Bars.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor11/Bed.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Bars.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Floor2/Bed.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: beta-fix

#3179 Kinkiest dungeon 2.33
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/RopeEngulf.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/RopeEngulfHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/LearnedRope.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/MonsterRope.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeKraken.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeMinion.aseprite
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeMinion.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeSnake.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Knives.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonPathfinding.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVision.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: beta-fix

#3188 Pet Bowl Fixed Position
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Inventory/ItemDevices/PetBowl/PetBowl.js
Labels: asset, change

#3180 Cleaning and Serving self and dust sprites
  BondageClub/Screens/MiniGame/MaidCleaning/Spot1.png
  BondageClub/Screens/MiniGame/MaidCleaning/Spot2.png
  BondageClub/Screens/MiniGame/MaidCleaning/Spot3.png
  BondageClub/Screens/MiniGame/MaidCleaning/Spot4.png
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid.csv
  BondageClub/Screens/Room/MaidQuarters/MaidQuarters.js
Labels: improvement

#3103 Typescript fixes
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/MiniGame/PlayerAuction/PlayerAuction.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Room/Poker/Poker.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Notification.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#3205 [Asset] Harness OTN Plug Gag
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/OTNPlugGagPlug_Plug.png
  BondageClub/Assets/Female3DCG/ItemMouth/OTNPlugGag_Base.png
  BondageClub/Assets/Female3DCG/ItemMouth/OTNPlugGag_Metal.png
  BondageClub/Assets/Female3DCG/ItemMouth/OTNPlugGag_Straps.png
  BondageClub/Assets/Female3DCG/ItemMouth/OTNPlugGag_Tongue.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/OTNPlugGag.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/OTNPlugGag/Open.png
  BondageClub/Screens/Inventory/ItemMouth/OTNPlugGag/Plug.png
Labels: asset

#3204 Effect Retrieval Rework
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Speech.js
Labels: refactor, fix

#3203 Fix missing Bondage Harness for the LegsClosed pose
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties1_Large.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties1_Normal.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties1_Small.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties1_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/HarnessPanties2_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Horse/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/Horse/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/Horse/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/Horse/HarnessPanties2_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties1_Large.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties1_Normal.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties1_Small.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties1_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/Kneel/HarnessPanties2_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties1_Large.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties1_Normal.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties1_Small.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties1_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/KneelingSpread/HarnessPanties2_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/LegsClosed/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/LegsClosed/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/LegsClosed/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/LegsClosed/HarnessPanties2_XLarge.png
  BondageClub/Assets/Female3DCG/Panties/Preview/HarnessPanties1.png
  BondageClub/Assets/Female3DCG/Panties/Preview/HarnessPanties2.png
  BondageClub/Assets/Female3DCG/Panties/Spread/HarnessPanties2_Large.png
  BondageClub/Assets/Female3DCG/Panties/Spread/HarnessPanties2_Normal.png
  BondageClub/Assets/Female3DCG/Panties/Spread/HarnessPanties2_Small.png
  BondageClub/Assets/Female3DCG/Panties/Spread/HarnessPanties2_XLarge.png
Labels: fix

#3202 Blouse Alpha Masks
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#3201 bugfix: remember private room becoming public on recreate
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#3200 Bed & Crib Legs Open fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#3198 College Chess Strip Fix
  BondageClub/Screens/Room/CollegeChess/CollegeChess.js
Labels: fix

#3197 feature: chat notification option for mentions of your character name
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement
