Repository Ben987/Bondage-College, pull requests merged in 2022-05, with the labels that each got.

#3391 Fix: Small fix for translation updater.
  BondageClub/Tools/Translation/Tools/GenerateTranslationTemplate.html
Labels: fix

#3392 Combo harness
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarnessShiny_Ball.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarnessShiny_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarnessTight_Ball.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarnessTight_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Ball.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Buckles.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Harness.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Lock.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Ring.png
  BondageClub/Assets/Female3DCG/ItemNeck/ComboHarness_Studs.png
  BondageClub/Assets/Female3DCG/ItemNeck/Preview/ComboHarness.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemNeck/ComboHarness/Normal.png
  BondageClub/Screens/Inventory/ItemNeck/ComboHarness/Shiny.png
  BondageClub/Screens/Inventory/ItemNeck/ComboHarness/Tight.png
  BondageClub/Scripts/Inventory.js
Labels: asset

#3393 Bugfix: `CanCloseLegs` prerequisite
  BondageClub/Scripts/Inventory.js
Labels: fix

#3394 Gambling hall fixes
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_FirstSub.csv
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_FirstSub_DE.txt
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_FirstSub_RU.txt
  BondageClub/Screens/Room/Gambling/Gambling.js
Labels: fix, change

#3395 Silky scarves
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHead/Preview/ScarfBlindfold.png
  BondageClub/Assets/Female3DCG/ItemHead/ScarfBlindfold.png
  BondageClub/Assets/Female3DCG/ItemMouth/ScarfGagOTN.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemMouth/ScarfGag/Loose.png
  BondageClub/Screens/Inventory/ItemMouth/ScarfGag/OTN.png
Labels: asset

#3397 Pony harness gag
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix, asset

#3398 Stop item sounds from playing when another screen is shown
  BondageClub/Scripts/Audio.js
Labels: fix

#3399 Feature: Blur & tint effects
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
Labels: feature, asset, change

#3402 Woodbox hood
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethroughOpaque_Glass.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethroughOpaque_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethrough_Frame.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethrough_Glass.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethrough_GlassInside.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethrough_LEDs.png
  BondageClub/Assets/Female3DCG/ItemHood/HeadboxSeethrough_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/HeadboxSeethrough.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: asset

#3404 Feat: More online dialog cn translations.
  BondageClub/Screens/Online/ChatRoom/Dialog_Online_CN.txt
Labels: translation

#3406 Latex bunny suit
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Large_Bottom.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Large_BottomShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Large_Breasts.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Large_BreastsShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Navel.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Normal_Bottom.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Normal_BottomShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Normal_Breasts.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Normal_BreastsShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Small_Bottom.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Small_BottomShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Small_Breasts.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_Small_BreastsShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_XLarge_Bottom.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_XLarge_BottomShine.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_XLarge_Breasts.png
  BondageClub/Assets/Female3DCG/Bra/LatexBunnySuit_XLarge_BreastsShine.png
  BondageClub/Assets/Female3DCG/Bra/Preview/LatexBunnySuit.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: asset

#3407 Appearance Screen Merge Concurrent Changes
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Scripts/Character.js
Labels: fix

#3408 Asset: Poncho
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Large_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Large_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Normal_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Normal_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Small_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_Small_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_XLarge_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/BackElbowTouch/Poncho_XLarge_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Large_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Large_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Normal_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Normal_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Small_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_Small_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_XLarge_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/OverTheHead/Poncho_XLarge_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Large_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Large_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Normal_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Normal_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Small_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_Small_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_XLarge_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Poncho_XLarge_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/Poncho.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Large_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Large_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Normal_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Normal_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Small_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_Small_Front.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_XLarge_Back.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Yoked/Poncho_XLarge_Front.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: asset

#3405 Asset: Slime restraints
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/Slime_BaseOneHogtied.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/Slime_BaseTwoHogtied.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/Slime_GirlFeaturesHogtied.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/Slime_GirlFrontHogtied.png
  BondageClub/Assets/Female3DCG/ItemArms/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemArms/Slime_BaseOne.png
  BondageClub/Assets/Female3DCG/ItemArms/Slime_BaseTwo.png
  BondageClub/Assets/Female3DCG/ItemArms/Slime_GirlBack.png
  BondageClub/Assets/Female3DCG/ItemArms/Slime_GirlFeatures.png
  BondageClub/Assets/Female3DCG/ItemArms/Slime_GirlFront.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/Slime_One.png
  BondageClub/Assets/Female3DCG/ItemBoots/LegsClosed/Slime_Two.png
  BondageClub/Assets/Female3DCG/ItemBoots/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemFeet/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemFeet/Slime_One.png
  BondageClub/Assets/Female3DCG/ItemFeet/Slime_Two.png
  BondageClub/Assets/Female3DCG/ItemHead/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemHead/Slime.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemHood/Slime_One.png
  BondageClub/Assets/Female3DCG/ItemHood/Slime_Two.png
  BondageClub/Assets/Female3DCG/ItemLegs/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemLegs/Slime_One.png
  BondageClub/Assets/Female3DCG/ItemLegs/Slime_Two.png
  BondageClub/Assets/Female3DCG/ItemMouth/Preview/Slime.png
  BondageClub/Assets/Female3DCG/ItemMouth/Slime.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Appearance/Appearance.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/Slime/p0.png
  BondageClub/Screens/Inventory/ItemArms/Slime/p1.png
  BondageClub/Screens/Inventory/ItemArms/Slime/t0.png
  BondageClub/Screens/Inventory/ItemArms/Slime/t1.png
Labels: asset

#3409 Fix: Add missing links to some translation files
  BondageClub/Screens/Online/ChatRoom/Text_Commands_DE.txt
  BondageClub/Screens/Online/ChatRoom/Text_Commands_FR.txt
  BondageClub/Screens/Online/ChatRoom/Text_Commands_RU.txt
  BondageClub/Screens/Room/CollegeEntrance/Dialog_NPC_CollegeTennis_Jennifer_RU.txt
  BondageClub/Scripts/Translation.js
Labels: refactor, fix

#3411 Feat: Chinese translation for activity.
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
Labels: translation

#3415 Bugfix: Caps Bondage Brawl level at 10
  BondageClub/Screens/Room/Platform/Platform.js
Labels: fix

#3416 Bugfix: Moves the `AllowBlur` preference into graphics settings
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Character/Preference/Text_Preference.csv
  BondageClub/Screens/Room/MainHall/MainHall.js
  BondageClub/Screens/Room/MainHall/Text_MainHall.csv
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Typedef.d.ts
Labels: beta-fix

#3438 Bugfix: `ExtendedItemLoad` fixes
  BondageClub/Scripts/ExtendedItem.js
Labels: fix

#3435 GP-9 Gas Mask tint tweak
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3434 Fix account creation crashes on R80b
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/Preference/Preference.js
Labels: beta-fix

#3433 Feat: Chinese translation and fix.
  BondageClub/Assets/Female3DCG/Female3DCG_CN.txt
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
  BondageClub/Screens/Online/ChatAdmin/Text_ChatAdmin_CN.txt
  BondageClub/Screens/Room/AsylumGGTS/Dialog_NPC_AsylumGGTS_Computer_CN.txt
Labels: translation

#3431 Gags Missing Open-Mouth Fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#3428 Reinstates removed `AllowPose` for original Harem Pants
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Large_Buttons.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Large_Fabric.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Large_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Large_PantyLine.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Large_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Normal_Buttons.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Normal_Fabric.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Normal_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Normal_PantyLine.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Normal_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Small_Buttons.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Small_Fabric.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Small_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Small_PantyLine.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_Small_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_XLarge_Buttons.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_XLarge_Fabric.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_XLarge_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_XLarge_PantyLine.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants2_XLarge_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Large_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Large_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Large_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Normal_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Normal_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Normal_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Small_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Small_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_Small_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_XLarge_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_XLarge_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Horse/HaremPants_XLarge_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Large_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Large_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Large_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Normal_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Normal_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Normal_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Small_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Small_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_Small_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_XLarge_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_XLarge_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/LegsClosed/HaremPants_XLarge_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Large_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Large_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Large_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Normal_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Normal_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Normal_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Small_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Small_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_Small_Veil.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_XLarge_Panty.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_XLarge_Pantyline.png
  BondageClub/Assets/Female3DCG/ClothLower/Spread/HaremPants_XLarge_Veil.png
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3447 Remove duplicate line from the rules menu
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Labels: beta-fix

#3443 Fix: Chinese translation in GGTS.
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
Labels: translation

#3442 Kinky Dungeon 3.31
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/RopeEngulf.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Conditions/Shop.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Consumables/Ectoplasm.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/DoorLock.aseprite
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/DoorLock.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/NawashiZombie.png
  BondageClub/Screens/MiniGame/KinkyDungeon/FloorGeneric/Angel.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Ectoplasm.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KDTypeDefs.ts
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumablesList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogue.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogueList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogueTriggers.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemiesList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEvents.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFactions.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFactionsList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInput.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonJail.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLootList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLore.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagicList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonObject.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonPathfinding.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonReputation.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraintsList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSetpiece.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSpawns.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTiles.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTraps.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVibe.js
  BondageClub/Screens/MiniGame/KinkyDungeon/MagicBook.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/index.html
Labels: feature

#3441 Fix autoscroll
  BondageClub/Screens/Character/FriendList/FriendList.js
  BondageClub/Scripts/Server.js
Labels: fix

#3440 Medieval rack: Various fixes
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#3422 Bugfix: 404s corset items in the `Cloth` group
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix, asset

#3421 Pony harness gag fix
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix, asset

#3439 Changelog: R80 Beta 2
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#3449 Fix: issue with Chinese OOC not blocked in Extreme difficulty.
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#3456 Kinky Dungeon 3.32
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/ElementalLeather.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/ElementalRope.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Enemies/RopeElemental.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KDTypeDefs.ts
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumablesList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogue.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogueList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDialogueTriggers.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemiesList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEvents.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFactions.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFactionsList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInput.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonJail.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagicList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonReputation.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraintsList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSpawns.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTraps.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonVibe.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
Labels: beta-fix

#3458 Fix InflationAmountSetLight dialog
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Tools/Node/AssetCheck.js
Labels: fix

#3463 Asset Check ArchetypeConfig fix
  BondageClub/Tools/Node/AssetCheck.js
Labels: beta-fix

#3462 Changelog: R80 Release
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/Tools/Node/GenerateChangelog.js
  BondageClub/changelog.html
  BondageClub/index.html
Labels: changelog

#3466 Bugfix: Stops locks from being deleted by the variable height load function
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/VariableHeight.js
Labels: hotfix

#3419 Additional handheld items
  BondageClub/Assets/Female3DCG/Activity/Inject.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHands/AllFours/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/BackBoxTie/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/BackCuffs/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/BackElbowTouch/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/MedicalInjector_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/MedicalInjector_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/MedicalInjector_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/MedicalInjector_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/OverTheHead/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/MedicalInjector.png
  BondageClub/Assets/Female3DCG/ItemHands/Preview/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/SpankingToysPotionBottle.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/MedicalInjector_Large.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/MedicalInjector_Normal.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/MedicalInjector_Small.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/MedicalInjector_XLarge.png
  BondageClub/Assets/Female3DCG/ItemHands/Yoked/SpankingToysPotionBottle.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/PotionBottle.png
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
Labels: asset

#3420 Fluffy twin tails hairstyle
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairBack/HairBack53_Base.png
  BondageClub/Assets/Female3DCG/HairBack/HairBack53_Tip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront27_Bangs.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront27_BangsTip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront27_Base.png
  BondageClub/Assets/Female3DCG/HairFront/Suspension/HairFront27_Bangs.png
  BondageClub/Assets/Female3DCG/HairFront/Suspension/HairFront27_BangsTip.png
  BondageClub/Assets/Female3DCG/HairFront/Suspension/HairFront27_Base.png
Labels: asset

#3423 Catsuit Collar
  BondageClub/Assets/Female3DCG/ClothAccessory/CatsuitCollar.png
  BondageClub/Assets/Female3DCG/ClothAccessory/Preview/CatsuitCollar.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Necklace/CatsuitCollar.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/CatsuitCollar.png
Labels: asset

#3436 Add kitty hood & latex dog hood
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Base.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Blindfold.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_BlindfoldNeutral.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_BlindfoldOwO.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_BlindfoldUwU.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Display.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Gag.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_GagNeutral.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_GagOwO.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_GagUwU.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Linings.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Openings.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Panel.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexDogHood.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexDogHood_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/KittyHood.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/LatexDogHood.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/KittyHood/b0.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/b1.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/e0.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/e1.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/e2.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/g0.png
  BondageClub/Screens/Inventory/ItemHood/KittyHood/g1.png
Labels: asset

#3451 Small CN translation fix
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
  BondageClub/Screens/Online/ChatSearch/Text_ChatSearch_CN.txt
Labels: translation

#3472 Translation fixes
  BondageClub/Screens/MiniGame/Kidnap/Text_Kidnap_CN.txt
  BondageClub/Screens/MiniGame/Tennis/Text_Tennis_CN.txt
Labels: fix, translation

#3459 Chinese Translation
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_EscapedPatient_CN.txt
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_KidnapNurse_CN.txt
Labels: translation

#3467 Feature: Adds lock icons to extended item menu preview images
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/VariableHeight.js
  BondageClub/Scripts/VibratorMode.js
Labels: feature

#3470 Allow multiple title pages, show current title
  BondageClub/Screens/Character/Title/Text_Title.csv
  BondageClub/Screens/Character/Title/Title.js
Labels: improvement

#3418 Typing improvements for `CommonDraw.js`
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Scripts/Animation.js
  BondageClub/Scripts/CommonDraw.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#3474 Kitty Hood Tweaks
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Base.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Display.png
  BondageClub/Assets/Female3DCG/ItemHood/KittyHood_Lock.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: change

#3450 Improvement: Standardizes `AllowLock` behaviour
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
Labels: refactor, improvement

#3461 Asset: Body Chain Necklace by Titania
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Assets/Female3DCG/Necklace/BackCuffs/BodyChainNecklace_Large_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackCuffs/BodyChainNecklace_Normal_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackCuffs/BodyChainNecklace_Small_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackCuffs/BodyChainNecklace_XLarge_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackElbowTouch/BodyChainNecklace_Large_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackElbowTouch/BodyChainNecklace_Normal_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackElbowTouch/BodyChainNecklace_Small_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BackElbowTouch/BodyChainNecklace_XLarge_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BodyChainNecklace_Choker.png
  BondageClub/Assets/Female3DCG/Necklace/BodyChainNecklace_Large_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BodyChainNecklace_Normal_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BodyChainNecklace_Small_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/BodyChainNecklace_XLarge_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/OverTheHead/BodyChainNecklace_Large_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/OverTheHead/BodyChainNecklace_Normal_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/OverTheHead/BodyChainNecklace_Small_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/OverTheHead/BodyChainNecklace_XLarge_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/Preview/BodyChainNecklace.png
  BondageClub/Assets/Female3DCG/Necklace/Yoked/BodyChainNecklace_Large_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/Yoked/BodyChainNecklace_Normal_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/Yoked/BodyChainNecklace_Small_Chains.png
  BondageClub/Assets/Female3DCG/Necklace/Yoked/BodyChainNecklace_XLarge_Chains.png
Labels: asset

#3473 Fix: Fixes `AllowActivityOn` type
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Typedef.d.ts
Labels: improvement

#3454 Feature: Adds `AllowLock` support to modular items
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
Labels: feature

#3457 Medieval rack: locks
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: asset, has-dependencies

#3446 Remove the Leather Whip, Crop, and Vibrating Wand items
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemBreast/Preview/LeatherCrop.png
  BondageClub/Assets/Female3DCG/ItemBreast/Preview/LeatherWhip.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/LeatherCrop.png
  BondageClub/Assets/Female3DCG/ItemPelvis/Preview/LeatherWhip.png
  BondageClub/Assets/Female3DCG/ItemVulva/Preview/VibratingWand.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Room/AsylumMeeting/AsylumMeeting.js
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid.csv
  BondageClub/Screens/Room/DailyJob/Dialog_NPC_DailyJob_Opponent.csv
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_FirstSub.csv
  BondageClub/Screens/Room/Gambling/Dialog_NPC_Gambling_SecondSub.csv
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid.csv
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub.csv
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_RandomKidnapper.csv
  BondageClub/Screens/Room/KidnapLeague/Dialog_NPC_KidnapLeague_Trainer.csv
  BondageClub/Screens/Room/Magic/Dialog_NPC_Magic_Assistant.csv
  BondageClub/Screens/Room/Magic/Dialog_NPC_Magic_Performer.csv
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid.csv
  BondageClub/Screens/Room/MainHall/Dialog_NPC_MainHall_Maid.csv
  BondageClub/Screens/Room/Management/Dialog_NPC_Management_RandomGirl.csv
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_ABDL1.csv
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_ABDL2.csv
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
  BondageClub/Screens/Room/Photographic/Dialog_NPC_Photographic_Sub.csv
  BondageClub/Screens/Room/Prison/Dialog_NPC_Prison_Maid.csv
  BondageClub/Screens/Room/Prison/Dialog_NPC_Prison_Sub.csv
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Custom.csv
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Vendor.csv
  BondageClub/Screens/Room/Private/Private.js
  BondageClub/Screens/Room/Sarah/Dialog_NPC_Amanda.csv
  BondageClub/Screens/Room/Sarah/Dialog_NPC_Sarah.csv
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Student.csv
  BondageClub/Screens/Room/Shibari/Dialog_NPC_Shibari_Teacher.csv
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor.csv
  BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Pony.csv
  BondageClub/Screens/Room/Stable/Dialog_NPC_Stable_Trainer.csv
  BondageClub/Screens/Room/Stable/Stable.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Import.js
Labels: change

#3476 Create Text_Poker_CN.txt
  BondageClub/Screens/Room/Poker/Text_Poker_CN.txt
Labels: translation

#3464 Minor Changes to Speech.js
  BondageClub/Scripts/Speech.js
Labels: refactor, fix

#3452 Another batch of TS fixes
  BondageClub/Screens/Online/ChatRoom/Commands.js
  BondageClub/Screens/Room/AsylumGGTS/AsylumGGTS.js
  BondageClub/Screens/Room/Infiltration/Infiltration.js
  BondageClub/Screens/Room/Pandora/Pandora.js
  BondageClub/Screens/Room/Sarah/Sarah.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Element.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#3481 Fix issue with extended items not accounting for character nicks
  BondageClub/Scripts/ExtendedItem.js
Labels: fix
