Repository Ben987/Bondage-College, pull requests merged in 2022-04, with the labels that each got.

#3292 CowHood by Evals
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemHood/CowHood_Base.png
  BondageClub/Assets/Female3DCG/ItemHood/CowHood_Spots.png
  BondageClub/Assets/Female3DCG/ItemHood/Preview/CowHood.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: asset

#3293 Fix an invalid property access on messages that do not have a sender
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
Labels: fix

#3297 More sound work
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Audio/VibratorShort.mp3
  BondageClub/Audio/WandBig.mp3
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Scripts/Audio.js
Labels: improvement

#3296 Make the PonyGag effects work correctly
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
Labels: fix

#3295 Make the ItemProperties interface explicit to catch issues
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/TransportJacket/TransportJacket.js
  BondageClub/Screens/Inventory/ItemBreast/FuturisticBra/FuturisticBra.js
  BondageClub/Screens/Inventory/ItemDevices/WoodenBox/WoodenBox.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticHarnessBallGag/FuturisticHarnessBallGag.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemNeck/SlaveCollar/SlaveCollar.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#3294 Cleanup the way activities are defined
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Screens/Inventory/ItemHands/SpankingToys/SpankingToy.js
  BondageClub/Scripts/Activity.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Typedef.d.ts
Labels: refactor

#3307 Chinese Translation update
  BondageClub/Screens/Cutscene/PlayerMistress/Text_PlayerMistress_CN.txt
  BondageClub/Screens/Room/AsylumBedroom/Text_AsylumBedroom_CN.txt
  BondageClub/Screens/Room/AsylumEntrance/Dialog_NPC_AsylumEntrance_Nurse_CN.txt
  BondageClub/Screens/Room/AsylumEntrance/Text_AsylumEntrance_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3310 fix #3309: nursery dialog error causing accountupdate flood
  BondageClub/Screens/Room/Nursery/Dialog_NPC_Nursery_Nurse.csv
Labels: fix

#3308 Misc: Code restructure.
  BondageClub/Scripts/Speech.js
Labels: refactor

#3317 Cancel Private Room Security Service fix
  BondageClub/Screens/Room/Private/Dialog_NPC_Private_Vendor.csv
Labels: fix

#3319 Fix item application playing sounds
  BondageClub/Scripts/Audio.js
Labels: beta-fix

#3320 Missing message on the Pony gag
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#3321 Mismatched asset name for the Pony Gag's Pentacle Panel
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_PanelPentacle.png
Labels: beta-fix

#3323 Restore the Vacbed Hairback hiding
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3324 Pony harness gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_BaseStraps.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_ExtraStraps.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_Horn.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_HornShine.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_PanelBase.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_PostReins.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_PostReinsDetail.png
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_Reins.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: beta-fix, asset

#3325 Fix: Chinese language text not wrapping properly.
  BondageClub/Scripts/Drawing.js
Labels: fix

#3326 Transparency in Preview Images
  BondageClub/Assets/Female3DCG/HairAccessory1/Preview/UnicornHorn.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/b0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/b1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/e0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/e1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/e2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/g0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/g1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/g2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/g3.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/g4.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/h0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/h1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/h2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p3.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p4.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p5.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p6.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p7.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p8.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/p9.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/r0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/r1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/r2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/r3.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/t0.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/t1.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/t2.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/t3.png
  BondageClub/Screens/Inventory/ItemMouth/PonyGag/t4.png
Labels: beta-fix

#3334 Update Dialog_Player_CN.txt
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
Labels: translation

#3335 Fix UseRemote effect
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Typedef.d.ts
Labels: fix

#3337 Feat: Chinese translation for some common items.
  BondageClub/Assets/Female3DCG/Female3DCG_CN.txt
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
Labels: translation

#3338 Kinky Dungeon Changes and fixes
  BondageClub/Screens/MiniGame/KinkyDungeon/Audio/Alarm.ogg
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Boulder.aseprite
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/Boulder.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BoulderHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BoulderLaunch.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/BoulderLaunchHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectricBurst.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectricBurstHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectricOrb.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Bullets/WitchElectricOrbHit.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Changelog.txt
  BondageClub/Screens/MiniGame/KinkyDungeon/Down.png
  BondageClub/Screens/MiniGame/KinkyDungeon/Items/Keyring.png
  BondageClub/Screens/MiniGame/KinkyDungeon/KDTypeDefs.ts
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeon.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonConsumables.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonCurse.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDraw.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDress.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonDressList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemies.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEnemiesList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonEvents.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonFight.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonGame.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonHUD.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonInventory.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonItem.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonJail.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLoot.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonLootList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagic.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMagicList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonMultiplayer.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonParams.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonPathfinding.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonReputation.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraints.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonRestraintsList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSetpiece.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonShrine.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonSpawns.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonStats.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTests.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTiles.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonTraps.js
  BondageClub/Screens/MiniGame/KinkyDungeon/KinkyDungeonWeaponList.js
  BondageClub/Screens/MiniGame/KinkyDungeon/Text_KinkyDungeon.csv
  BondageClub/Screens/MiniGame/KinkyDungeon/Up.png
  BondageClub/Screens/Online/ChatRoom/Dialog_Online.csv
Labels: change

#3340 Typescript tweaks
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Screens/Inventory/ItemMisc/MistressTimerPadlock/MistressTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/OwnerTimerPadlock/OwnerTimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPadlock/TimerPadlock.js
  BondageClub/Screens/Inventory/ItemMisc/TimerPasswordPadlock/TimerPasswordPadlock.js
  BondageClub/Screens/Inventory/ItemMouth/FuturisticPanelGag/FuturisticPanelGag.js
  BondageClub/Screens/Inventory/ItemPelvis/FuturisticTrainingBelt/FuturisticTrainingBelt.js
  BondageClub/Screens/Inventory/ItemVulva/FuturisticVibrator/FuturisticVibrator.js
  BondageClub/Scripts/ModularItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/Validation.js
  BondageClub/Scripts/VibratorMode.js
Labels: improvement

#3341 Pony harness gag
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_Post.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: beta-fix

#3342 CN Translation for Maid Quarters
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_InitiationMaids_CN.txt
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3346 Pony harness gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Screens/Character/Player/Dialog_Player.csv
Labels: beta-fix

#3347 Type definition fixes for `HideAs` changes
  BondageClub/Assets/Female3DCG/Female3DCG_Types.d.ts
  BondageClub/Scripts/Typedef.d.ts
Labels: beta-fix

#3348 Habit fix
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemHood/AccentHood.png
  BondageClub/Assets/Female3DCG/ItemHood/AccentHood_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/CollarHood.png
  BondageClub/Assets/Female3DCG/ItemHood/CollarHood_Collar.png
  BondageClub/Assets/Female3DCG/ItemHood/CollarHood_Hood.png
  BondageClub/Assets/Female3DCG/ItemHood/CollarHood_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Back.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Base.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Cape.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Collar.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Cowl.png
  BondageClub/Assets/Female3DCG/ItemHood/LatexHabit_Lock.png
  BondageClub/Assets/Female3DCG/ItemHood/ZipperHoodZippersClosedEyes.png
  BondageClub/Assets/Female3DCG/ItemHood/ZipperHoodZippersClosedMouth.png
  BondageClub/Assets/Female3DCG/ItemHood/ZipperHood_Lock.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemHood/ZipperHood/ZippersClosedEyes.png
  BondageClub/Screens/Inventory/ItemHood/ZipperHood/ZippersClosedMouth.png
Labels: beta-fix

#3350 Feat: GGTS related Chinese translation.
  BondageClub/Assets/Female3DCG/Female3DCG_CN.txt
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
  BondageClub/Screens/Room/AsylumGGTS/Dialog_NPC_AsylumGGTS_Computer_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3351 Pony harness gag
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/ItemMouth/PonyGag_Blinders.png
Labels: beta-fix

#3355 Changelog: R79
  BondageClub/CHANGELOG.md
  BondageClub/changelog.html
Labels: changelog

#3369 Additional garbling fixes
  BondageClub/Scripts/Speech.js
Labels: hotfix

#3357 Variable Height Archetype
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/Chains_Suspension.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRope.js
  BondageClub/Screens/Inventory/ItemArms/HempRope/HempRopeSuspensionHogtied.js
  BondageClub/Screens/Room/MagicSchoolLaboratory/MagicSchoolLaboratory.js
  BondageClub/Screens/Room/Shibari/Shibari.js
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/ExtendedItem.js
  BondageClub/Scripts/TypedItem.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/VariableHeight.js
  BondageClub/index.html
Labels: refactor, improvement

#3358 Fix dereferencing null DOM elements
  BondageClub/Scripts/Element.js
Labels: fix

#3365 Ownership Break Fixes
  BondageClub/Screens/Room/Management/Dialog_NPC_Management_Mistress.csv
  BondageClub/Screens/Room/Management/Management.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/GameLog.js
  BondageClub/Scripts/Server.js
Labels: fix

#3367 Update Common.js
  Common.js
Labels: translation

#3368 PonyGag added to slots 2 and 3
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: feature, asset

#3371 fixed a translation mistake
  BondageClub/Screens/Room/AsylumGGTS/Dialog_NPC_AsylumGGTS_Computer_CN.txt
Labels: translation

#3372 Feat: more CN translations.
  BondageClub/Assets/Female3DCG/Female3DCG_CN.txt
Labels: translation

#3373 Update Dialog_NPC_MaidQuarters_Maid_CN.txt
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_CN.txt
Labels: translation

#3374 Add Chinese translations for some minigames
  BondageClub/Screens/MiniGame/Chess/Text_Chess_CN.txt
  BondageClub/Screens/MiniGame/ChestLockpick/Text_ChestLockpick_CN.txt
  BondageClub/Screens/MiniGame/DojoStruggle/Text_DojoStruggle_CN.txt
  BondageClub/Screens/MiniGame/GetUp/Text_GetUp_CN.txt
  BondageClub/Screens/MiniGame/HorseWalk/Text_HorseWalk_CN.txt
  BondageClub/Screens/MiniGame/Kidnap/Text_Kidnap_CN.txt
  BondageClub/Screens/MiniGame/MaidCleaning/Text_MaidCleaning_CN.txt
  BondageClub/Screens/MiniGame/MaidDrinks/Text_MaidDrinks_CN.txt
  BondageClub/Screens/MiniGame/PuppyWalker/Text_PuppyWalker_CN.txt
  BondageClub/Screens/MiniGame/RhythmGame/Text_RhythmGame_CN.txt
  BondageClub/Screens/MiniGame/Tennis/Text_Tennis_CN.txt
  BondageClub/Screens/MiniGame/Therapy/Text_Therapy_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3376 Fix dereferencing null DOM elements, take 2
  BondageClub/Scripts/Element.js
Labels: fix

#3377 Add Chinese translation for store
  BondageClub/Screens/Room/MaidQuarters/Dialog_NPC_MaidQuarters_Maid_CN.txt
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Customer_CN.txt
  BondageClub/Screens/Room/Shop/Dialog_NPC_Shop_Vendor_CN.txt
  BondageClub/Screens/Room/Shop/Text_Shop_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3378 Validation Fix
  BondageClub/Scripts/Validation.js
Labels: fix

#3381 fix some translation
  C010_Revenge/SidneyJennifer/Stage_CN.csv
Labels: fix

#3384 bug repair
  C010_Revenge/AmandaSarah/Stage_CN.csv
  C010_Revenge/SidneyJennifer/Stage_CN.csv
Labels: fix

#3386 Medieval rack
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_HalfBack.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/WoodenRack/f1.png
  BondageClub/Screens/Inventory/ItemDevices/WoodenRack/f2.png
  BondageClub/Screens/Inventory/ItemDevices/WoodenRack/f3.png
Labels: asset

#3387 VariableHeight TS fixes
  BondageClub/Scripts/Asset.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/Scripts/VariableHeight.js
Labels: fix
