Repository Ben987/Bondage-College, pull requests merged in 2022-06, with the labels that each got.

#3460 Refactor: Random code cleanup and simplification
  BondageClub/Screens/Character/BackgroundSelection/BackgroundSelection.js
  BondageClub/Screens/Character/Login/Login.js
  BondageClub/Screens/Character/OnlineProfile/OnlineProfile.js
  BondageClub/Screens/Character/Title/Title.js
  BondageClub/Screens/Character/Wardrobe/Wardrobe.js
  BondageClub/Screens/Online/ChatCreate/ChatCreate.js
  BondageClub/Screens/Online/ChatRoom/ChatRoom.js
  BondageClub/Screens/Online/GameMagicBattle/GameMagicBattle.js
  BondageClub/Scripts/Character.js
  BondageClub/Scripts/Dialog.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/Inventory.js
  BondageClub/Scripts/NPC.js
  BondageClub/Scripts/Server.js
  BondageClub/Scripts/Struggle.js
  BondageClub/Scripts/Timer.js
  BondageClub/index.html
Labels: refactor, improvement

#3486 Leather cuff hogtie
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Large_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Large_Rings.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Lock.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Normal_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Normal_Rings.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Small_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_Small_Rings.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_XLarge_Cuffs.png
  BondageClub/Assets/Female3DCG/ItemArms/Hogtied/LeatherCuffs_XLarge_Rings.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemArms/LeatherCuffs/Hogtie.png
Labels: asset

#3485 cn translation
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Maid_CN.txt
  BondageClub/Screens/Room/Introduction/Dialog_NPC_Introduction_Sub_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3484 Chinese Translation
  BondageClub/Screens/Room/AsylumMeeting/Dialog_NPC_AsylumMeeting_PatientLeft_CN.txt
  BondageClub/Screens/Room/AsylumMeeting/Dialog_NPC_AsylumMeeting_PatientRight_CN.txt
  BondageClub/Screens/Room/AsylumTherapy/Dialog_NPC_AsylumTherapy_Nurse_CN.txt
  BondageClub/Screens/Room/Cafe/Dialog_NPC_Cafe_Maid_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#2987 Overhaul image caching
  BondageClub/Screens/Character/Preference/Preference.js
  BondageClub/Scripts/Animation.js
  BondageClub/Scripts/Drawing.js
  BondageClub/Scripts/GLDraw.js
  BondageClub/Scripts/ImageCache.js
  BondageClub/index.html
Labels: refactor, change

#3487 Fix some issues with the asset loading
  BondageClub/Scripts/ImageCache.js
  BondageClub/Scripts/Timer.js
Labels: fix

#3489 Fix missing handheld activities on the vulva piercing slot
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: fix

#3491 Changelog: R81 Beta 1
  BondageClub/CHANGELOG.md
  BondageClub/Screens/Character/Login/GameCredits.csv
  BondageClub/Tools/Node/GenerateChangelog.js
  BondageClub/changelog.html
Labels: changelog

#3493 Cn translation
  BondageClub/Assets/Female3DCG/ColorGroups_CN.txt
  BondageClub/Assets/Female3DCG/Female3DCG_CN.txt
  BondageClub/Assets/Female3DCG/LayerNames_CN.txt
  BondageClub/Screens/Character/InformationSheet/Text_InformationSheet_CN.txt
  BondageClub/Screens/Character/Player/Dialog_Player_CN.txt
  BondageClub/Screens/Character/Preference/ActivityDictionary_CN.txt
  BondageClub/Screens/Room/Crafting/Text_Crafting_CN.txt
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Dominatrix_CN.txt
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Kidnapper_CN.txt
  BondageClub/Screens/Room/Infiltration/Dialog_NPC_Infiltration_Supervisor_CN.txt
  BondageClub/Screens/Room/Infiltration/Text_Infiltration_CN.txt
  BondageClub/Screens/Room/InfiltrationPerks/Text_InfiltrationPerks_CN.txt
  BondageClub/Screens/Room/MainHall/Text_MainHall_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_EntranceMaid_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_KidnapTarget_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_NightGuard_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_PunishmentMistress_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomCosplay_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomGuard_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMaid_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMemberNew_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMemberOld_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomMistress_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RandomSlave_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RescueGuard_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_RescueVictim_CN.txt
  BondageClub/Screens/Room/Pandora/Dialog_NPC_Pandora_TreasureChest_CN.txt
  BondageClub/Screens/Room/Pandora/Text_Pandora_CN.txt
  BondageClub/Screens/Room/PandoraPrison/Dialog_NPC_PandoraPrison_Guard_CN.txt
  BondageClub/Screens/Room/PandoraPrison/Dialog_NPC_PandoraPrison_Maid_CN.txt
  BondageClub/Screens/Room/PandoraPrison/Text_PandoraPrison_CN.txt
  BondageClub/Scripts/Translation.js
Labels: translation

#3492 Always return exactly matching room-names
  BondageClub/Screens/Online/ChatSearch/ChatSearch.js
Labels: change

#3494 Fix: Head harness Heavy Type
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/Mask/HeadHarness_Heavy.png
  BondageClub/Assets/Female3DCG/Mask/HeadHarness_HeavyMetal.png
Labels: beta-fix

#3495 Beta fix: Increases priority of back layer for the Asymmetric Skirt
  BondageClub/Assets/Female3DCG/Female3DCG.js
Labels: beta-fix

#3497 Fix Poker & Platform image caching
  BondageClub/Screens/Room/Platform/Platform.js
  BondageClub/Screens/Room/PlatformIntro/PlatformIntro.js
  BondageClub/Screens/Room/Poker/Poker.js
  BondageClub/Scripts/ImageCache.js
Labels: beta-fix

#3498 Hide the Hair accessory groups on the Kitty and Latex Dog Hood
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Scripts/Typedef.d.ts
Labels: beta-fix

#3501 Fix: Medieval rack fixes
  BondageClub/Assets/Female3DCG/ColorGroups.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_BotStocks.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_BotStocksBack.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_FrameMetal.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_TopStocks.png
  BondageClub/Assets/Female3DCG/ItemDevices/WoodenRack_TopStocksBack.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemDevices/WoodenRack/t5.png
Labels: beta-fix

#3502 Safeguard against VariableHeightChange getting called with no item selected
  BondageClub/Scripts/VariableHeight.js
Labels: fix

#3496 Add a Jacket to the Cloth group
  BondageClub/Assets/Female3DCG/Cloth/AllFours/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/BackBoxTie/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/BackCuffs/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/BackElbowTouch/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Hogtied/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Jacket_Hood.png
  BondageClub/Assets/Female3DCG/Cloth/OverTheHead/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Preview/Jacket.png
  BondageClub/Assets/Female3DCG/Cloth/TapedHands/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Cloth/Yoked/Jacket_Base.png
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/LayerNames.csv
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/Cloth/Jacket/Hooded.png
  BondageClub/Screens/Inventory/Cloth/Jacket/HoodedEarsOut.png
  BondageClub/Screens/Inventory/Cloth/Jacket/Normal.png
Labels: asset

#3505 Improvement/fix: Lock number validation improvements
  BondageClub/Scripts/Validation.js
Labels: improvement, fix

#3506 Medical Injector Beta Fixes
  BondageClub/Screens/Character/Preference/ActivityDictionary.csv
Labels: beta-fix

#3518 Fix trial ownership owner locks disappearing
  BondageClub/Scripts/Validation.js
Labels: beta-fix

#3521 Enable favourite of clothing in Extreme difficulty
  BondageClub/Screens/Character/Appearance/Appearance.js
Labels: improvement

#3513 Fix: SideFluff color gradient
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/HairFront/HairFront22_Tip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_Fluff.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_FrontTip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront22b_Tip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23_Tip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b_FrontTip.png
  BondageClub/Assets/Female3DCG/HairFront/HairFront23b_Tip.png
  BondageClub/Assets/Female3DCG/LayerNames.csv
Labels: feature, asset

#3522 New Zone: ItemTorso2
  BondageClub/Assets/Female3DCG/Female3DCG.csv
  BondageClub/Assets/Female3DCG/Female3DCG.js
  BondageClub/Assets/Female3DCG/Female3DCGExtended.js
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit2_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit2_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit2_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit2_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_LargeDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_NormalDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_SmallDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/Hogtied/LockingSwimsuit_XLargeDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit2_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit2_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit2_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit2_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_Large.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_LargeDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_Normal.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_NormalDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_Small.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_SmallDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_XLarge.png
  BondageClub/Assets/Female3DCG/ItemTorso/LockingSwimsuit_XLargeDull.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/LockingSwimsuit.png
  BondageClub/Assets/Female3DCG/ItemTorso/Preview/LockingSwimsuit2.png
  BondageClub/Screens/Character/Player/Dialog_Player.csv
  BondageClub/Screens/Inventory/ItemTorso/LockingSwimsuit/Dull.png
  BondageClub/Screens/Inventory/ItemTorso/LockingSwimsuit/Shiny.png
  BondageClub/Screens/Inventory/ItemTorso2/FuturisticHarness/FuturisticHarness.js
  BondageClub/Scripts/Typedef.d.ts
  BondageClub/index.html
Labels: feature, asset
